import os, json

BASE_DIR = "vocabulary/de"

def write_js(filepath, lang, data):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    content = f"""// TODO: verify level classification
(function() {{
    const lang = "{lang}";
    const data = {json.dumps(data, ensure_ascii=False, indent=4)};
    window.vocabularyData = window.vocabularyData || {{}};
    window.vocabularyData[lang] = [...(window.vocabularyData[lang] || []), ...data];
}})();
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

de_a1_categories = {
    "animals.js": [
        {"word": "Hund", "level": "starter", "theme": "animals", "emoji": "🐕", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein treues Haustier und Freund des Menschen.", "examples": ["Der Hund läuft im Garten."]}], "lang": "de", "transcription": "hʊnt", "id": "de_starter_animals_001"},
        {"word": "Katze", "level": "starter", "theme": "animals", "emoji": "🐈", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein kleines Haustier mit weichem Fell.", "examples": ["Die Katze schläft auf dem Sofa."]}], "lang": "de", "transcription": "ˈkat͡sə", "id": "de_starter_animals_002"},
        {"word": "Vogel", "level": "starter", "theme": "animals", "emoji": "🐦", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein Tier mit Federn, das in der Luft fliegt.", "examples": ["Der Vogel singt im Baum."]}], "lang": "de", "transcription": "ˈfoːɡl̩", "id": "de_starter_animals_003"},
        {"word": "Fisch", "level": "starter", "theme": "animals", "emoji": "🐟", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein Wassertier, das im Wasser schwimmt.", "examples": ["Der Fisch schwimmt im Fluss."]}], "lang": "de", "transcription": "fɪʃ", "id": "de_starter_animals_004"},
        {"word": "Kuh", "level": "starter", "theme": "animals", "emoji": "🐄", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein großes Bauernhoftier, das Milch gibt.", "examples": ["Die Kuh frisst Gras auf der Wiese."]}], "lang": "de", "transcription": "kuː", "id": "de_starter_animals_005"},
        {"word": "Pferd", "level": "starter", "theme": "animals", "emoji": "🐎", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein starkes Tier, auf dem man reiten kann.", "examples": ["Das Pferd läuft sehr schnell."]}], "lang": "de", "transcription": "pfeːɐ̯t", "id": "de_starter_animals_006"},
        {"word": "Schwein", "level": "starter", "theme": "animals", "emoji": "🐖", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein Rosa Bauernhoftier.", "examples": ["Das Schwein lebt auf dem Bauernhof."]}], "lang": "de", "transcription": "ʃvaɪ̯n", "id": "de_starter_animals_007"},
        {"word": "Schaf", "level": "starter", "theme": "animals", "emoji": "🐑", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein Tier mit weicher Wolle.", "examples": ["Das Schaf steht auf der Wiese."]}], "lang": "de", "transcription": "ʃaːf", "id": "de_starter_animals_008"},
        {"word": "Bär", "level": "starter", "theme": "animals", "emoji": "🐻", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein großes Wildtier im Wald.", "examples": ["Der Bär schläft im Winter."]}], "lang": "de", "transcription": "bɛːɐ̯", "id": "de_starter_animals_009"},
        {"word": "Maus", "level": "starter", "theme": "animals", "emoji": "🖱️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein ganz kleines Tier mit langem Schwanz.", "examples": ["Die Maus isst gerne Käse."]}], "lang": "de", "transcription": "maʊ̯s", "id": "de_starter_animals_010"},
        {"word": "Ente", "level": "starter", "theme": "animals", "emoji": "🦆", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein Wasservogel, der schwimmen kann.", "examples": ["Die Ente schwimmt im See."]}], "lang": "de", "transcription": "ˈɛntə", "id": "de_starter_animals_011"},
        {"word": "Biene", "level": "starter", "theme": "animals", "emoji": "🐝", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein kleines Insekt, das Honig macht.", "examples": ["Die Biene fliegt von Blume zu Blume."]}], "lang": "de", "transcription": "ˈbiːnə", "id": "de_starter_animals_012"}
    ],
    "body.js": [
        {"word": "Kopf", "level": "starter", "theme": "body", "emoji": "🗣️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der oberste Teil des menschlichen Körpers.", "examples": ["Mein Kopf tut weh."]}], "lang": "de", "transcription": "kɔp͡f", "id": "de_starter_body_001"},
        {"word": "Hand", "level": "starter", "theme": "body", "emoji": "✋", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Körperteil zum Greifen von Dingen.", "examples": ["Wasche deine Hände vor dem Essen."]}], "lang": "de", "transcription": "hant", "id": "de_starter_body_002"},
        {"word": "Fuß", "level": "starter", "theme": "body", "emoji": "🦶", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Körperteil zum Gehen.", "examples": ["Ich gehe zu Fuß zur Schule."]}], "lang": "de", "transcription": "fuːs", "id": "de_starter_body_003"},
        {"word": "Auge", "level": "starter", "theme": "body", "emoji": "👁️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Das Organ zum Sehen.", "examples": ["Sie hat blaue Augen."]}], "lang": "de", "transcription": "ˈaʊ̯ɡə", "id": "de_starter_body_004"},
        {"word": "Ohr", "level": "starter", "theme": "body", "emoji": "👂", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Das Organ zum Hören.", "examples": ["Wir hören mit den Ohren."]}], "lang": "de", "transcription": "oːɐ̯", "id": "de_starter_body_005"},
        {"word": "Mund", "level": "starter", "theme": "body", "emoji": "👄", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Das Organ zum Sprechen und Essen.", "examples": ["Öffne bitte den Mund."]}], "lang": "de", "transcription": "mʊnt", "id": "de_starter_body_006"},
        {"word": "Nase", "level": "starter", "theme": "body", "emoji": "👃", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Das Organ zum Riechen.", "examples": ["Meine Nase ist kalt."]}], "lang": "de", "transcription": "ˈnaːzə", "id": "de_starter_body_007"},
        {"word": "Arm", "level": "starter", "theme": "body", "emoji": "💪", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der obere Körperteil zwischen Schulter und Hand.", "examples": ["Er hat starke Arme."]}], "lang": "de", "transcription": "aʁm", "id": "de_starter_body_008"},
        {"word": "Bein", "level": "starter", "theme": "body", "emoji": "🦵", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Körperteil zwischen Hüfte und Fuß.", "examples": ["Meine Beine sind müde."]}], "lang": "de", "transcription": "baɪ̯n", "id": "de_starter_body_009"},
        {"word": "Bauch", "level": "starter", "theme": "body", "emoji": "🫃", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der mittlere Körperteil vorn.", "examples": ["Ich habe Bauchschmerzen."]}], "lang": "de", "transcription": "baʊ̯x", "id": "de_starter_body_010"},
        {"word": "Haar", "level": "starter", "theme": "body", "emoji": "💇", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Bewuchs auf dem Kopf.", "examples": ["Sie hat kurzes blondes Haar."]}], "lang": "de", "transcription": "haːɐ̯", "id": "de_starter_body_011"},
        {"word": "Zahn", "level": "starter", "theme": "body", "emoji": "🦷", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Hartes Teil im Mund zum Kauen.", "examples": ["Putze deine Zähne nach dem Essen."]}], "lang": "de", "transcription": "t͡saːn", "id": "de_starter_body_012"}
    ],
    "clothes.js": [
        {"word": "Hemd", "level": "starter", "theme": "clothes", "emoji": "👔", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Kleidung mit Knöpfen für den Oberkörper.", "examples": ["Ich trage ein weißes Hemd."]}], "lang": "de", "transcription": "hɛmt", "id": "de_starter_clothes_001"},
        {"word": "Hose", "level": "starter", "theme": "clothes", "emoji": "👖", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Kleidung für die Beine.", "examples": ["Er kauft eine blaue Hose."]}], "lang": "de", "transcription": "ˈhoːzə", "id": "de_starter_clothes_002"},
        {"word": "Kleid", "level": "starter", "theme": "clothes", "emoji": "👗", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ein einteiliges Kleidungsstück.", "examples": ["Sie trägt ein schönes Kleid."]}], "lang": "de", "transcription": "klaɪ̯t", "id": "de_starter_clothes_003"},
        {"word": "Jacke", "level": "starter", "theme": "clothes", "emoji": "🧥", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Warme Oberbekleidung für draußen.", "examples": ["Im Herbst brauche ich eine Jacke."]}], "lang": "de", "transcription": "ˈjakə", "id": "de_starter_clothes_004"},
        {"word": "Schuh", "level": "starter", "theme": "clothes", "emoji": "👟", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fußbekleidung zum Schutz der Füße.", "examples": ["Meine neuen Schuhe sind bequem."]}], "lang": "de", "transcription": "ʃuː", "id": "de_starter_clothes_005"},
        {"word": "Hut", "level": "starter", "theme": "clothes", "emoji": "🎩", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Kopfbedeckung gegen Sonne oder Kälte.", "examples": ["Er trägt einen schwarzen Hut."]}], "lang": "de", "transcription": "huːt", "id": "de_starter_clothes_006"},
        {"word": "Mantel", "level": "starter", "theme": "clothes", "emoji": "🧥", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Lange, warme Bekleidung für den Winter.", "examples": ["Im Winter ziehe ich einen Mantel an."]}], "lang": "de", "transcription": "ˈmantl̩", "id": "de_starter_clothes_007"},
        {"word": "Pullover", "level": "starter", "theme": "clothes", "emoji": "🧶", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gestricktes Kleidungsstück für den Oberkörper.", "examples": ["Der Pullover ist sehr warm."]}], "lang": "de", "transcription": "pʊˈloːvɐ", "id": "de_starter_clothes_008"},
        {"word": "Rock", "level": "starter", "theme": "clothes", "emoji": "👗", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Kleidungsstück ab der Taille abwärts.", "examples": ["Sie trägt einen kurzen Rock."]}], "lang": "de", "transcription": "ʁɔk", "id": "de_starter_clothes_009"},
        {"word": "Socke", "level": "starter", "theme": "clothes", "emoji": "🧦", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Bekleidung für den Fuß unter dem Schuh.", "examples": ["Ich brauche warme Socken."]}], "lang": "de", "transcription": "ˈzɔkə", "id": "de_starter_clothes_010"},
        {"word": "Gürtel", "level": "starter", "theme": "clothes", "emoji": "🩲", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Band zum Halten der Hose.", "examples": ["Der Gürtel ist aus Leder."]}], "lang": "de", "transcription": "ˈɡʏʁtl̩", "id": "de_starter_clothes_011"},
        {"word": "T-Shirt", "level": "starter", "theme": "clothes", "emoji": "👕", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Leichtes Hemd mit kurzen Ärmeln.", "examples": ["Im Sommer trage ich ein T-Shirt."]}], "lang": "de", "transcription": "ˈtiːʃœːɐ̯t", "id": "de_starter_clothes_012"}
    ],
    "colours.js": [
        {"word": "schwarz", "level": "starter", "theme": "colours", "emoji": "⬛", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe der Nacht.", "examples": ["Ich habe eine schwarze Katze."]}], "lang": "de", "transcription": "ʃvaʁt͡s", "id": "de_starter_colours_001"},
        {"word": "weiß", "level": "starter", "theme": "colours", "emoji": "⬜", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe von Schnee und Milch.", "examples": ["Der Schnee ist weiß."]}], "lang": "de", "transcription": "vaɪ̯s", "id": "de_starter_colours_002"},
        {"word": "rot", "level": "starter", "theme": "colours", "emoji": "🟥", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe von Feuer und Erdbeeren.", "examples": ["Der Apfel ist rot und süß."]}], "lang": "de", "transcription": "ʁoːt", "id": "de_starter_colours_003"},
        {"word": "blau", "level": "starter", "theme": "colours", "emoji": "🟦", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe des klares Himmels und des Meeres.", "examples": ["Der Himmel ist heute blau."]}], "lang": "de", "transcription": "blaʊ̯", "id": "de_starter_colours_004"},
        {"word": "grün", "level": "starter", "theme": "colours", "emoji": "🟩", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe von Gras und Blättern.", "examples": ["Das Gras im Garten ist grün."]}], "lang": "de", "transcription": "ɡʁyːn", "id": "de_starter_colours_005"},
        {"word": "gelb", "level": "starter", "theme": "colours", "emoji": "🟨", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe der Sonne und von Zitronen.", "examples": ["Die Zitrone ist gelb."]}], "lang": "de", "transcription": "ɡɛlp", "id": "de_starter_colours_006"},
        {"word": "grau", "level": "starter", "theme": "colours", "emoji": "🔘", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe zwischen Schwarz und Weiß.", "examples": ["Der Himmel ist grau und es regnet."]}], "lang": "de", "transcription": "ɡʁaʊ̯", "id": "de_starter_colours_007"},
        {"word": "braun", "level": "starter", "theme": "colours", "emoji": "🟫", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe von Holz und Erde.", "examples": ["Der Bär ist braun."]}], "lang": "de", "transcription": "bʁaʊ̯n", "id": "de_starter_colours_008"},
        {"word": "rosa", "level": "starter", "theme": "colours", "emoji": "🩷", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Helle rote Farbe.", "examples": ["Das Kleid ist rosa."]}], "lang": "de", "transcription": "ˈʁoːza", "id": "de_starter_colours_009"},
        {"word": "orange", "level": "starter", "theme": "colours", "emoji": "🟧", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Die Farbe von Orangen.", "examples": ["Die Karotte ist orange."]}], "lang": "de", "transcription": "oˈʁaːŋʃ", "id": "de_starter_colours_010"},
        {"word": "violett", "level": "starter", "theme": "colours", "emoji": "🟪", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Lila Farbe.", "examples": ["Die Blume ist violett."]}], "lang": "de", "transcription": "vioˈlɛt", "id": "de_starter_colours_011"}
    ],
    "family.js": [
        {"word": "Vater", "level": "starter", "theme": "family", "emoji": "👨", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der männliche Elternteil.", "examples": ["Mein Vater arbeitet im Büro."]}], "lang": "de", "transcription": "ˈfaːtɐ", "id": "de_starter_family_001"},
        {"word": "Mutter", "level": "starter", "theme": "family", "emoji": "👩", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der weibliche Elternteil.", "examples": ["Meine Mutter kocht das Abendessen."]}], "lang": "de", "transcription": "ˈmʊtɐ", "id": "de_starter_family_002"},
        {"word": "Bruder", "level": "starter", "theme": "family", "emoji": "👦", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Männliches Geschwisterteil.", "examples": ["Mein Bruder geht noch zur Schule."]}], "lang": "de", "transcription": "ˈbʁuːdɐ", "id": "de_starter_family_003"},
        {"word": "Schwester", "level": "starter", "theme": "family", "emoji": "👧", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Weibliches Geschwisterteil.", "examples": ["Meine Schwester liest gern Bücher."]}], "lang": "de", "transcription": "ˈʃvɛstɐ", "id": "de_starter_family_004"},
        {"word": "Sohn", "level": "starter", "theme": "family", "emoji": "👶", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Männliches Kind der Eltern.", "examples": ["Unser Sohn ist fünf Jahre alt."]}], "lang": "de", "transcription": "zoːn", "id": "de_starter_family_005"},
        {"word": "Tochter", "level": "starter", "theme": "family", "emoji": "👧", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Weibliches Kind der Eltern.", "examples": ["Ihre Tochter spielt im Garten."]}], "lang": "de", "transcription": "ˈtɔxtɐ", "id": "de_starter_family_006"},
        {"word": "Großvater", "level": "starter", "theme": "family", "emoji": "👴", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Vater von Vater oder Mutter (Opa).", "examples": ["Mein Großvater erzählt Geschichten."]}], "lang": "de", "transcription": "ˈɡʁoːsˌfaːtɐ", "id": "de_starter_family_007"},
        {"word": "Großmutter", "level": "starter", "theme": "family", "emoji": "👵", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Mutter von Vater oder Mutter (Oma).", "examples": ["Meine Großmutter backt Kuchen."]}], "lang": "de", "transcription": "ˈɡʁoːsˌmʊtɐ", "id": "de_starter_family_008"},
        {"word": "Onkel", "level": "starter", "theme": "family", "emoji": "👨", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Bruder von Vater oder Mutter.", "examples": ["Mein Onkel wohnt in Berlin."]}], "lang": "de", "transcription": "ˈɔŋkl̩", "id": "de_starter_family_009"},
        {"word": "Tante", "level": "starter", "theme": "family", "emoji": "👩", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Schwester von Vater oder Mutter.", "examples": ["Meine Tante besucht uns heute."]}], "lang": "de", "transcription": "ˈtantə", "id": "de_starter_family_010"},
        {"word": "Cousine", "level": "starter", "theme": "family", "emoji": "👧", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Tochter von Onkel oder Tante.", "examples": ["Meine Cousine studiert in München."]}], "lang": "de", "transcription": "kuˈziːnə", "id": "de_starter_family_011"},
        {"word": "Kind", "level": "starter", "theme": "family", "emoji": "👶", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Mensch im Kindesalter.", "examples": ["Die Kinder spielen draußen."]}], "lang": "de", "transcription": "kɪnt", "id": "de_starter_family_012"}
    ],
    "food_drink.js": [
        {"word": "Brot", "level": "starter", "theme": "food_drink", "emoji": "🍞", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Grundnahrungsmittel aus Mehl und Wasser.", "examples": ["Ich esse frisches Brot zum Frühstück."]}], "lang": "de", "transcription": "bʁoːt", "id": "de_starter_food_drink_001"},
        {"word": "Milch", "level": "starter", "theme": "food_drink", "emoji": "🥛", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Weißes Getränk von der Kuh.", "examples": ["Er trinkt jeden Morgen Milch."]}], "lang": "de", "transcription": "mɪlç", "id": "de_starter_food_drink_002"},
        {"word": "Wasser", "level": "starter", "theme": "food_drink", "emoji": "💧", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Lebenswichtige durchsichtige Flüssigkeit.", "examples": ["Bitte ein Glas Wasser."]}], "lang": "de", "transcription": "ˈvasɐ", "id": "de_starter_food_drink_003"},
        {"word": "Tee", "level": "starter", "theme": "food_drink", "emoji": "☕", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Warmes Getränk aus Kräutern oder Blättern.", "examples": ["Im Winter trinke ich heißen Tee."]}], "lang": "de", "transcription": "teː", "id": "de_starter_food_drink_004"},
        {"word": "Kaffee", "level": "starter", "theme": "food_drink", "emoji": "☕", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Aromatisches warmes Getränk.", "examples": ["Ein Kaffee mit Milch, bitte."]}], "lang": "de", "transcription": "ˈkafe", "id": "de_starter_food_drink_005"},
        {"word": "Butter", "level": "starter", "theme": "food_drink", "emoji": "🧈", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Streichfett aus Milch.", "examples": ["Ich streiche Butter auf das Brot."]}], "lang": "de", "transcription": "ˈbʊtɐ", "id": "de_starter_food_drink_006"},
        {"word": "Käse", "level": "starter", "theme": "food_drink", "emoji": "🧀", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Milchprodukt in festem Zustand.", "examples": ["Gouda ist ein bekannter Käse."]}], "lang": "de", "transcription": "ˈkɛːzə", "id": "de_starter_food_drink_007"},
        {"word": "Fleisch", "level": "starter", "theme": "food_drink", "emoji": "🥩", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Nahrungsmittel von Tieren.", "examples": ["Isst du gerne Fleisch?"]}], "lang": "de", "transcription": "flaɪ̯ʃ", "id": "de_starter_food_drink_008"},
        {"word": "Apfel", "level": "starter", "theme": "food_drink", "emoji": "🍎", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Beliebte runde Frucht.", "examples": ["Ein roter Apfel ist gesund."]}], "lang": "de", "transcription": "ˈap͡fl̩", "id": "de_starter_food_drink_009"},
        {"word": "Kartoffel", "level": "starter", "theme": "food_drink", "emoji": "🥔", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Wichtige Nutzpflanze und Nahrungsmittel.", "examples": ["Kartoffeln schmecken gut."]}], "lang": "de", "transcription": "kaʁˈtɔfl̩", "id": "de_starter_food_drink_010"},
        {"word": "Reis", "level": "starter", "theme": "food_drink", "emoji": "🍚", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Beliebtes Getreidekorn.", "examples": ["Reis passt gut zu Gemüsegerichten."]}], "lang": "de", "transcription": "ʁaɪ̯s", "id": "de_starter_food_drink_011"},
        {"word": "Banane", "level": "starter", "theme": "food_drink", "emoji": "🍌", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Süße gelbe Tropenfrucht.", "examples": ["Die Banane ist gelb und süß."]}], "lang": "de", "transcription": "baˈnaːnə", "id": "de_starter_food_drink_012"}
    ],
    "furniture.js": [
        {"word": "Tisch", "level": "starter", "theme": "furniture", "emoji": "🪑", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Möbelstück zum Essen oder Arbeiten.", "examples": ["Das Buch liegt auf dem Tisch."]}], "lang": "de", "transcription": "tɪʃ", "id": "de_starter_furniture_001"},
        {"word": "Stuhl", "level": "starter", "theme": "furniture", "emoji": "🪑", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Möbelstück zum Sitzen.", "examples": ["Setzen Sie sich bitte auf den Stuhl."]}], "lang": "de", "transcription": "ʃtuːl", "id": "de_starter_furniture_002"},
        {"word": "Bett", "level": "starter", "theme": "furniture", "emoji": "🛏️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Möbelstück zum Schlafen.", "examples": ["Ich gehe ins Bett, ich bin müde."]}], "lang": "de", "transcription": "bɛt", "id": "de_starter_furniture_003"},
        {"word": "Schrank", "level": "starter", "theme": "furniture", "emoji": "🚪", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Möbelstück zum Aufbewahren von Kleidung.", "examples": ["Die Kleidung hängt im Schrank."]}], "lang": "de", "transcription": "ʃʁaŋk", "id": "de_starter_furniture_004"},
        {"word": "Sofa", "level": "starter", "theme": "furniture", "emoji": "🛋️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Bequemes Sitzmöbel im Wohnzimmer.", "examples": ["Wir sitzen gemütlich auf dem Sofa."]}], "lang": "de", "transcription": "ˈzoːfa", "id": "de_starter_furniture_005"},
        {"word": "Lampe", "level": "starter", "theme": "furniture", "emoji": "💡", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Lichtquelle im Zimmer.", "examples": ["Schalte bitte die Lampe an."]}], "lang": "de", "transcription": "ˈlampə", "id": "de_starter_furniture_006"},
        {"word": "Teppich", "level": "starter", "theme": "furniture", "emoji": "🧶", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Textiler Bodenbelag.", "examples": ["Der Teppich liegt auf dem Boden."]}], "lang": "de", "transcription": "ˈtɛpɪç", "id": "de_starter_furniture_007"},
        {"word": "Regal", "level": "starter", "theme": "furniture", "emoji": "🗄️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Möbelstück für Bücher und Dinge.", "examples": ["Die Bücher stehen im Regal."]}], "lang": "de", "transcription": "ʁeˈɡaːl", "id": "de_starter_furniture_008"},
        {"word": "Bild", "level": "starter", "theme": "furniture", "emoji": "🖼️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Kunstwerk an der Wand.", "examples": ["Ein schönes Bild hängt an der Wand."]}], "lang": "de", "transcription": "bɪlt", "id": "de_starter_furniture_009"}
    ],
    "greetings.js": [
        {"word": "hallo", "level": "starter", "theme": "greetings", "emoji": "👋", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Freundlicher Gruß.", "examples": ["Hallo! Wie geht es dir?"]}], "lang": "de", "transcription": "haˈloː", "id": "de_starter_greetings_001"},
        {"word": "guten Morgen", "level": "starter", "theme": "greetings", "emoji": "🌅", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Morgendlicher Gruß.", "examples": ["Guten Morgen, zusammen!"]}], "lang": "de", "transcription": "ˈɡuːtn̩ ˈmɔʁɡn̩", "id": "de_starter_greetings_002"},
        {"word": "guten Tag", "level": "starter", "theme": "greetings", "emoji": "☀️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gruß am Tag.", "examples": ["Guten Tag, Herr Müller!"]}], "lang": "de", "transcription": "ˈɡuːtn̩ taːk", "id": "de_starter_greetings_003"},
        {"word": "guten Abend", "level": "starter", "theme": "greetings", "emoji": "🌆", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gruß am Abend.", "examples": ["Guten Abend, meine Damen und Herren!"]}], "lang": "de", "transcription": "ˈɡuːtn̩ ˈaːbn̩t", "id": "de_starter_greetings_004"},
        {"word": "gute Nacht", "level": "starter", "theme": "greetings", "emoji": "🌙", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gruß vor dem Schlafen.", "examples": ["Gute Nacht, schlaf gut!"]}], "lang": "de", "transcription": "ˈɡuːtə naxt", "id": "de_starter_greetings_005"},
        {"word": "auf Wiedersehen", "level": "starter", "theme": "greetings", "emoji": "👋", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Formeller Abschiedsgruß.", "examples": ["Auf Wiedersehen und bis bald!"]}], "lang": "de", "transcription": "aʊ̯f ˈviːdɐˌzeːən", "id": "de_starter_greetings_006"},
        {"word": "danke", "level": "starter", "theme": "greetings", "emoji": "🙏", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Ausdruck des Danks.", "examples": ["Vielen Dank für die Hilfe."]}], "lang": "de", "transcription": "ˈdaŋkə", "id": "de_starter_greetings_007"},
        {"word": "bitte", "level": "starter", "theme": "greetings", "emoji": "🤝", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Höfliches Wort bei Bitten oder Antworten.", "examples": ["Ein Wasser, bitte."]}], "lang": "de", "transcription": "ˈbɪtə", "id": "de_starter_greetings_008"},
        {"word": "tschüss", "level": "starter", "theme": "greetings", "emoji": "👋", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Informeller Abschiedsgruß.", "examples": ["Tschüss, bis morgen!"]}], "lang": "de", "transcription": "t͡ʃyːs", "id": "de_starter_greetings_009"},
        {"word": "Entschuldigung", "level": "starter", "theme": "greetings", "emoji": "🙇", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Höfliches Wort zur Entschuldigung.", "examples": ["Entschuldigung, wie spät ist es?"]}], "lang": "de", "transcription": "ɛntˈʃʊldɪɡʊŋ", "id": "de_starter_greetings_010"}
    ],
    "jobs.js": [
        {"word": "Lehrer", "level": "starter", "theme": "jobs", "emoji": "👨‍🏫", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die an einer Schule unterrichtet.", "examples": ["Der Lehrer erklärt die Aufgabe."]}], "lang": "de", "transcription": "ˈleːʁɐ", "id": "de_starter_jobs_001"},
        {"word": "Arzt", "level": "starter", "theme": "jobs", "emoji": "👨‍⚕️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die Kranke behandelt.", "examples": ["Der Arzt untersucht den Patienten."]}], "lang": "de", "transcription": "aːɐ̯t͡st", "id": "de_starter_jobs_002"},
        {"word": "Koch", "level": "starter", "theme": "jobs", "emoji": "👨‍🍳", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die beruflich kocht.", "examples": ["Der Koch bereitet das Essen zu."]}], "lang": "de", "transcription": "kɔx", "id": "de_starter_jobs_003"},
        {"word": "Fahrer", "level": "starter", "theme": "jobs", "emoji": "👨‍✈️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die ein Fahrzeug lenkt.", "examples": ["Der Fahrer steuert den Bus."]}], "lang": "de", "transcription": "ˈfaːʁɐ", "id": "de_starter_jobs_004"},
        {"word": "Ingenieur", "level": "starter", "theme": "jobs", "emoji": "👷", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fachmann für Technik und Konstruktion.", "examples": ["Der Ingenieur baut Brücken."]}], "lang": "de", "transcription": "ɪnʒeˈnjøːɐ̯", "id": "de_starter_jobs_005"},
        {"word": "Student", "level": "starter", "theme": "jobs", "emoji": "🎓", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die an einer Universität studiert.", "examples": ["Der Student lernt in der Bibliothek."]}], "lang": "de", "transcription": "ʃtuˈdɛnt", "id": "de_starter_jobs_006"},
        {"word": "Verkäufer", "level": "starter", "theme": "jobs", "emoji": "🧑‍💼", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die Waren in einem Geschäft verkauft.", "examples": ["Der Verkäufer bedient die Kunden."]}], "lang": "de", "transcription": "fɛɐ̯ˈkɔɪ̯fɐ", "id": "de_starter_jobs_007"},
        {"word": "Kellner", "level": "starter", "theme": "jobs", "emoji": "🧑‍🍳", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, die Gäste im Restaurant bedient.", "examples": ["Der Kellner bringt die Speisekarte."]}], "lang": "de", "transcription": "ˈkɛlnɐ", "id": "de_starter_jobs_008"},
        {"word": "Polizist", "level": "starter", "theme": "jobs", "emoji": "👮", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Mitglied der Polizei.", "examples": ["Der Polizist hilft im Verkehr."]}], "lang": "de", "transcription": "poliˈt͡sɪst", "id": "de_starter_jobs_009"}
    ],
    "nature.js": [
        {"word": "Sonne", "level": "starter", "theme": "nature", "emoji": "☀️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Himmelskörper, der Licht und Wärme gibt.", "examples": ["Die Sonne scheint warm."]}], "lang": "de", "transcription": "ˈzɔnə", "id": "de_starter_nature_001"},
        {"word": "Mond", "level": "starter", "theme": "nature", "emoji": "🌙", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Himmelskörper, der nachts leuchtet.", "examples": ["Der Mond steht am Nachthimmel."]}], "lang": "de", "transcription": "moːnt", "id": "de_starter_nature_002"},
        {"word": "Stern", "level": "starter", "theme": "nature", "emoji": "⭐", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Leuchtender Punkt am Nachthimmel.", "examples": ["Viele Sterne funkeln nachts."]}], "lang": "de", "transcription": "ʃtɛʁn", "id": "de_starter_nature_003"},
        {"word": "Baum", "level": "starter", "theme": "nature", "emoji": "🌳", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Hohe Pflanze mit Stamm und Blättern.", "examples": ["Der Baum im Garten ist sehr alt."]}], "lang": "de", "transcription": "baʊ̯m", "id": "de_starter_nature_004"},
        {"word": "Blume", "level": "starter", "theme": "nature", "emoji": "🌸", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Schöne farbige Pflanze.", "examples": ["Die Blumen duften schön."]}], "lang": "de", "transcription": "ˈbluːmə", "id": "de_starter_nature_005"},
        {"word": "Fluss", "level": "starter", "theme": "nature", "emoji": "🏞️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Natürliches fließendes Gewässer.", "examples": ["Der Rhein ist ein großer Fluss."]}], "lang": "de", "transcription": "flʊs", "id": "de_starter_nature_006"},
        {"word": "Meer", "level": "starter", "theme": "nature", "emoji": "🌊", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Großes Salzgewässer.", "examples": ["Wir machen Urlaub am Meer."]}], "lang": "de", "transcription": "meːɐ̯", "id": "de_starter_nature_007"},
        {"word": "Berg", "level": "starter", "theme": "nature", "emoji": "⛰️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Hohe Erhebung der Landschaft.", "examples": ["Die Alpen sind hohe Berge."]}], "lang": "de", "transcription": "bɛʁk", "id": "de_starter_nature_008"},
        {"word": "Wald", "level": "starter", "theme": "nature", "emoji": "🌲", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Große Fläche mit vielen Bäumen.", "examples": ["Wir spazieren im Wald."]}], "lang": "de", "transcription": "valt", "id": "de_starter_nature_009"},
        {"word": "See", "level": "starter", "theme": "nature", "emoji": "🏞️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Stehendes Binnengewässer.", "examples": ["Der Bodensee ist sehr schön."]}], "lang": "de", "transcription": "zeː", "id": "de_starter_nature_010"},
        {"word": "Wind", "level": "starter", "theme": "nature", "emoji": "💨", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Bewegte Luft draußen.", "examples": ["Heute weht ein starker Wind."]}], "lang": "de", "transcription": "vɪnt", "id": "de_starter_nature_011"},
        {"word": "Regen", "level": "starter", "theme": "nature", "emoji": "🌧️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Niederschlag aus Wassertropfen.", "examples": ["Der Regen fällt vom Himmel."]}], "lang": "de", "transcription": "ˈʁeːɡn̩", "id": "de_starter_nature_012"}
    ],
    "numbers.js": [
        {"word": "eins", "level": "starter", "theme": "numbers", "emoji": "1️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die erste Zahl.", "examples": ["Eins, zwei, drei."]}], "lang": "de", "transcription": "aɪ̯ns", "id": "de_starter_numbers_001"},
        {"word": "zwei", "level": "starter", "theme": "numbers", "emoji": "2️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Eins.", "examples": ["Ich habe zwei Katzen."]}], "lang": "de", "transcription": "t͡svaɪ̯", "id": "de_starter_numbers_002"},
        {"word": "drei", "level": "starter", "theme": "numbers", "emoji": "3️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Zwei.", "examples": ["Drei Bücher liegen auf dem Tisch."]}], "lang": "de", "transcription": "dʁaɪ̯", "id": "de_starter_numbers_003"},
        {"word": "vier", "level": "starter", "theme": "numbers", "emoji": "4️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Drei.", "examples": ["Der Tisch hat vier Beine."]}], "lang": "de", "transcription": "fiːɐ̯", "id": "de_starter_numbers_004"},
        {"word": "fünf", "level": "starter", "theme": "numbers", "emoji": "5️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Vier.", "examples": ["Fünf Finger an einer Hand."]}], "lang": "de", "transcription": "fʏnf", "id": "de_starter_numbers_005"},
        {"word": "sechs", "level": "starter", "theme": "numbers", "emoji": "6️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Fünf.", "examples": ["Das Paket wiegt sechs Kilo."]}], "lang": "de", "transcription": "zɛks", "id": "de_starter_numbers_006"},
        {"word": "sieben", "level": "starter", "theme": "numbers", "emoji": "7️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Sechs.", "examples": ["Die Woche hat sieben Tage."]}], "lang": "de", "transcription": "ˈziːbn̩", "id": "de_starter_numbers_007"},
        {"word": "acht", "level": "starter", "theme": "numbers", "emoji": "8️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Sieben.", "examples": ["Wir frühstücken um acht Uhr."]}], "lang": "de", "transcription": "axt", "id": "de_starter_numbers_008"},
        {"word": "neun", "level": "starter", "theme": "numbers", "emoji": "9️⃣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Acht.", "examples": ["Neun Schüler sind in der Klasse."]}], "lang": "de", "transcription": "nɔɪ̯n", "id": "de_starter_numbers_009"},
        {"word": "zehn", "level": "starter", "theme": "numbers", "emoji": "🔟", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Neun.", "examples": ["Ich habe zehn Euro."]}], "lang": "de", "transcription": "t͡seːn", "id": "de_starter_numbers_010"},
        {"word": "elf", "level": "starter", "theme": "numbers", "emoji": "🔢", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Zehn.", "examples": ["Elf Spieler spielen im Team."]}], "lang": "de", "transcription": "ɛlf", "id": "de_starter_numbers_011"},
        {"word": "zwölf", "level": "starter", "theme": "numbers", "emoji": "🔢", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Die Zahl nach der Elf.", "examples": ["Das Jahr hat zwölf Monate."]}], "lang": "de", "transcription": "t͡svœlf", "id": "de_starter_numbers_012"}
    ],
    "places.js": [
        {"word": "Haus", "level": "starter", "theme": "places", "emoji": "🏠", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gebäude, in dem Menschen wohnen.", "examples": ["Mein Haus steht am Park."]}], "lang": "de", "transcription": "haʊ̯s", "id": "de_starter_places_001"},
        {"word": "Stadt", "level": "starter", "theme": "places", "emoji": "🏙️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Große Siedlung mit vielen Gebäude.", "examples": ["Berlin ist eine schöne Stadt."]}], "lang": "de", "transcription": "ʃtat", "id": "de_starter_places_002"},
        {"word": "Schule", "level": "starter", "theme": "places", "emoji": "🏫", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort zum Lernen für Kinder.", "examples": ["Die Kinder gehen in die Schule."]}], "lang": "de", "transcription": "ˈʃuːlə", "id": "de_starter_places_003"},
        {"word": "Geschäft", "level": "starter", "theme": "places", "emoji": "🏪", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort zum Einkaufen.", "examples": ["Das Geschäft schließt um acht Uhr."]}], "lang": "de", "transcription": "ɡəˈʃɛft", "id": "de_starter_places_004"},
        {"word": "Krankenhaus", "level": "starter", "theme": "places", "emoji": "🏥", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gebäude zur Behandlung von Kranken.", "examples": ["Der Arzt arbeitet im Krankenhaus."]}], "lang": "de", "transcription": "ˈkʁaŋkn̩ˌhaʊ̯s", "id": "de_starter_places_005"},
        {"word": "Park", "level": "starter", "theme": "places", "emoji": "🏞️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Grüne Grünanlage in der Stadt.", "examples": ["Wir spazieren im Park."]}], "lang": "de", "transcription": "paʁk", "id": "de_starter_places_006"},
        {"word": "Bahnhof", "level": "starter", "theme": "places", "emoji": "🚉", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Haltestelle für Züge.", "examples": ["Der Zug kommt am Bahnhof an."]}], "lang": "de", "transcription": "ˈbaːnˌhoːf", "id": "de_starter_places_007"},
        {"word": "Bank", "level": "starter", "theme": "places", "emoji": "🏦", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Finanzinstitut für Geldgeschäfte.", "examples": ["Ich hebe Geld auf der Bank ab."]}], "lang": "de", "transcription": "baŋk", "id": "de_starter_places_008"},
        {"word": "Post", "level": "starter", "theme": "places", "emoji": "🏣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort für Briefe und Pakete.", "examples": ["Ich bringe das Paket zur Post."]}], "lang": "de", "transcription": "pɔst", "id": "de_starter_places_009"},
        {"word": "Restaurant", "level": "starter", "theme": "places", "emoji": "🍽️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort zum Essen gehen.", "examples": ["Wir essen heute im Restaurant."]}], "lang": "de", "transcription": "ʁɛstoˈʁɑ̃ː", "id": "de_starter_places_010"}
    ],
    "school.js": [
        {"word": "Buch", "level": "starter", "theme": "school", "emoji": "📖", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gedrucktes Werk zum Lesen.", "examples": ["Ich lese ein gutes Deutschbuch."]}], "lang": "de", "transcription": "buːx", "id": "de_starter_school_001"},
        {"word": "Heft", "level": "starter", "theme": "school", "emoji": "📓", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Papierseiten zum Schreiben.", "examples": ["Schreibe die Übung ins Heft."]}], "lang": "de", "transcription": "hɛft", "id": "de_starter_school_002"},
        {"word": "Stift", "level": "starter", "theme": "school", "emoji": "🖊️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Schreibgerät mit Tinte oder Minen.", "examples": ["Hast du einen Stift für mich?"]}], "lang": "de", "transcription": "ʃtɪft", "id": "de_starter_school_003"},
        {"word": "Bleistift", "level": "starter", "theme": "school", "emoji": "✏️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Schreibstift mit Graphitmine.", "examples": ["Ich zeichne mit dem Bleistift."]}], "lang": "de", "transcription": "ˈblaɪ̯ˌʃtɪft", "id": "de_starter_school_004"},
        {"word": "Unterricht", "level": "starter", "theme": "school", "emoji": "📝", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Lernzeit in der Schule.", "examples": ["Der Deutschunterricht beginnt um neun Uhr."]}], "lang": "de", "transcription": "ˈʊntɐˌʁɪçt", "id": "de_starter_school_005"},
        {"word": "Klasse", "level": "starter", "theme": "school", "emoji": "🏫", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gruppe von Schülern.", "examples": ["Unsere Klasse ist sehr nett."]}], "lang": "de", "transcription": "ˈklasə", "id": "de_starter_school_006"},
        {"word": "Hausaufgabe", "level": "starter", "theme": "school", "emoji": "📚", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Schularbeit für zu Hause.", "examples": ["Ich mache meine Hausaufgaben."]}], "lang": "de", "transcription": "ˈhaʊ̯sʔaʊ̯fˌɡaːbə", "id": "de_starter_school_007"}
    ],
    "shopping.js": [
        {"word": "Preis", "level": "starter", "theme": "shopping", "emoji": "🏷️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Geldbetrag für eine Ware.", "examples": ["Wie hoch ist der Preis?"]}], "lang": "de", "transcription": "pʁaɪ̯s", "id": "de_starter_shopping_001"},
        {"word": "Geld", "level": "starter", "theme": "shopping", "emoji": "💶", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Zahlungsmittel zum Einkaufen.", "examples": ["Ich habe genug Geld dabei."]}], "lang": "de", "transcription": "ɡɛlt", "id": "de_starter_shopping_002"},
        {"word": "kaufen", "level": "starter", "theme": "shopping", "emoji": "🛒", "form": "verb", "classification": "regular", "countability": "null", "definitions": [{"text": "Ware gegen Geld erwerben.", "examples": ["Ich kaufe Brot im Supermarkt."]}], "lang": "de", "transcription": "ˈkaʊ̯fn̩", "id": "de_starter_shopping_003"},
        {"word": "bezahlen", "level": "starter", "theme": "shopping", "emoji": "💳", "form": "verb", "classification": "regular", "countability": "null", "definitions": [{"text": "Geld für etwas geben.", "examples": ["Kann ich mit Karte bezahlen?"]}], "lang": "de", "transcription": "bəˈt͡saːln̩", "id": "de_starter_shopping_004"},
        {"word": "Supermarkt", "level": "starter", "theme": "shopping", "emoji": "🏪", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Großes Geschäft für Lebensmittel.", "examples": ["Der Supermarkt ist nah."]}], "lang": "de", "transcription": "ˈzuːpɐˌmaʁkt", "id": "de_starter_shopping_005"},
        {"word": "teuer", "level": "starter", "theme": "shopping", "emoji": "💎", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Mit hohem Preis.", "examples": ["Das Auto ist sehr teuer."]}], "lang": "de", "transcription": "ˈtɔɪ̯ɐ", "id": "de_starter_shopping_006"},
        {"word": "billig", "level": "starter", "theme": "shopping", "emoji": "🏷️", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Mit niedrigem Preis.", "examples": ["Die Äpfel sind hier billig."]}], "lang": "de", "transcription": "ˈbɪlɪç", "id": "de_starter_shopping_007"},
        {"word": "Kasse", "level": "starter", "theme": "shopping", "emoji": "🧾", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort zum Bezahlen im Geschäft.", "examples": ["Bitte zahlen Sie an der Kasse."]}], "lang": "de", "transcription": "ˈkasə", "id": "de_starter_shopping_008"}
    ],
    "social.js": [
        {"word": "Freund", "level": "starter", "theme": "social", "emoji": "🧑‍🤝‍🧑", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Nahestehende geliebte Person.", "examples": ["Mein Freund hilft mir gerne."]}], "lang": "de", "transcription": "fʁɔɪ̯nt", "id": "de_starter_social_001"},
        {"word": "Fest", "level": "starter", "theme": "social", "emoji": "🎉", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fröhliche Feier von Menschen.", "examples": ["Wir feiern ein großes Fest."]}], "lang": "de", "transcription": "fɛst", "id": "de_starter_social_002"},
        {"word": "Gespräch", "level": "starter", "theme": "social", "emoji": "💬", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Unterhaltung zwischen Personen.", "examples": ["Wir hatten ein gutes Gespräch."]}], "lang": "de", "transcription": "ɡəˈʃpʁɛːx", "id": "de_starter_social_003"},
        {"word": "Mensch", "level": "starter", "theme": "social", "emoji": "👤", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Person, Individuum.", "examples": ["Viele Menschen sind im Park."]}], "lang": "de", "transcription": "mɛnʃ", "id": "de_starter_social_004"},
        {"word": "Freundschaft", "level": "starter", "theme": "social", "emoji": "🤝", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Beziehung zwischen Freunden.", "examples": ["Unsere Freundschaft ist wichtig."]}], "lang": "de", "transcription": "ˈfʁɔɪ̯ntʃaft", "id": "de_starter_social_005"},
        {"word": "zusammen", "level": "starter", "theme": "social", "emoji": "🧑‍🤝‍🧑", "form": "adjective", "classification": "regular", "countability": "null", "definitions": [{"text": "Gemeinsam mit anderen.", "examples": ["Wir lernen zusammen Deutsch."]}], "lang": "de", "transcription": "t͡suˈzamən", "id": "de_starter_social_006"}
    ],
    "technology.js": [
        {"word": "Computer", "level": "starter", "theme": "technology", "emoji": "💻", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Elektronisches Gerät zum Arbeiten.", "examples": ["Ich arbeite jeden Tag am Computer."]}], "lang": "de", "transcription": "kɔmˈpjuːtɐ", "id": "de_starter_technology_001"},
        {"word": "Telefon", "level": "starter", "theme": "technology", "emoji": "📞", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gerät zum Anrufen.", "examples": ["Das Telefon klingelt."]}], "lang": "de", "transcription": "teleˈfoːn", "id": "de_starter_technology_002"},
        {"word": "Handy", "level": "starter", "theme": "technology", "emoji": "📱", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Mobiles Telefon.", "examples": ["Mein Handy ist neu."]}], "lang": "de", "transcription": "ˈhɛndi", "id": "de_starter_technology_003"},
        {"word": "Internet", "level": "starter", "theme": "technology", "emoji": "🌐", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Weltweites Computernetzwerk.", "examples": ["Ich suche Informationen im Internet."]}], "lang": "de", "transcription": "ˈɪntɐnɛt", "id": "de_starter_technology_004"},
        {"word": "E-Mail", "level": "starter", "theme": "technology", "emoji": "📧", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Elektronische Nachricht.", "examples": ["Ich schreibe eine E-Mail an meine Mutter."]}], "lang": "de", "transcription": "ˈiːmɛɪ̯l", "id": "de_starter_technology_005"}
    ],
    "time.js": [
        {"word": "Tag", "level": "starter", "theme": "time", "emoji": "📅", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Zeitabschnitt von 24 Stunden.", "examples": ["Heute ist ein schöner Tag."]}], "lang": "de", "transcription": "taːk", "id": "de_starter_time_001"},
        {"word": "Nacht", "level": "starter", "theme": "time", "emoji": "🌃", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Dunkle Zeit zum Schlafen.", "examples": ["Die Nacht ist ruhig."]}], "lang": "de", "transcription": "naxt", "id": "de_starter_time_002"},
        {"word": "heute", "level": "starter", "theme": "time", "emoji": "📆", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Der gegenwärtige Tag.", "examples": ["Heute haben wir Deutschunterricht."]}], "lang": "de", "transcription": "ˈhɔɪ̯tə", "id": "de_starter_time_003"},
        {"word": "morgen", "level": "starter", "theme": "time", "emoji": "➡️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Der Tag nach heute.", "examples": ["Morgen fahre ich nach Berlin."]}], "lang": "de", "transcription": "ˈmɔʁɡn̩", "id": "de_starter_time_004"},
        {"word": "gestern", "level": "starter", "theme": "time", "emoji": "⬅️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Der Tag vor heute.", "examples": ["Gestern war das Wetter schön."]}], "lang": "de", "transcription": "ˈɡɛstɐn", "id": "de_starter_time_005"},
        {"word": "Woche", "level": "starter", "theme": "time", "emoji": "🗓️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Zeitraum von sieben Tagen.", "examples": ["Eine Woche hat sieben Tage."]}], "lang": "de", "transcription": "ˈvɔxə", "id": "de_starter_time_006"},
        {"word": "Monat", "level": "starter", "theme": "time", "emoji": "🗓️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Zeitraum von etwa 30 Tagen.", "examples": ["Der Januar ist der erste Monat."]}], "lang": "de", "transcription": "ˈmoːnat", "id": "de_starter_time_007"},
        {"word": "Jahr", "level": "starter", "theme": "time", "emoji": "📆", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Zeitraum von 12 Monaten.", "examples": ["Ein Jahr hat 365 Tage."]}], "lang": "de", "transcription": "jaːɐ̯", "id": "de_starter_time_008"}
    ],
    "travel.js": [
        {"word": "Auto", "level": "starter", "theme": "travel", "emoji": "🚗", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fahrzeug mit vier Rädern.", "examples": ["Wir fahren mit dem Auto nach Italien."]}], "lang": "de", "transcription": "ˈaʊ̯to", "id": "de_starter_travel_001"},
        {"word": "Zug", "level": "starter", "theme": "travel", "emoji": "🚆", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Verkehrsmittel auf Schienen.", "examples": ["Der Zug fährt um neun Uhr ab."]}], "lang": "de", "transcription": "t͡suːk", "id": "de_starter_travel_002"},
        {"word": "Bus", "level": "starter", "theme": "travel", "emoji": "🚌", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Großes öffentliches Fahrzeug.", "examples": ["Der Bus hält an der Station."]}], "lang": "de", "transcription": "bʊs", "id": "de_starter_travel_003"},
        {"word": "Flugzeug", "level": "starter", "theme": "travel", "emoji": "✈️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Verkehrsmittel in der Luft.", "examples": ["Das Flugzeug fliegt nach Spanien."]}], "lang": "de", "transcription": "ˈfluːkˌt͡sɔɪ̯k", "id": "de_starter_travel_004"},
        {"word": "Reise", "level": "starter", "theme": "travel", "emoji": "🧳", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fahrt oder Flug an einen anderen Ort.", "examples": ["Gute Reise!"]}], "lang": "de", "transcription": "ˈʁaɪ̯zə", "id": "de_starter_travel_005"},
        {"word": "Ticket", "level": "starter", "theme": "travel", "emoji": "🎟️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Fahrkarte für Bus oder Zug.", "examples": ["Ich kaufe ein Ticket am Schalter."]}], "lang": "de", "transcription": "ˈtɪkət", "id": "de_starter_travel_006"}
    ]
}

for filename, entries in de_a1_categories.items():
    write_js(os.path.join(BASE_DIR, "A1", filename), "de", entries)

def update_index_json(dirpath):
    files = sorted([f for f in os.listdir(dirpath) if f.endswith('.js')])
    with open(os.path.join(dirpath, "index.json"), "w", encoding="utf-8") as f:
        json.dump(files, f, ensure_ascii=False, indent=2)

update_index_json(os.path.join(BASE_DIR, "A1"))

print("Successfully generated German A1 vocabulary files!")

# Add additional German A1 entries to hit >650 total
more_de_entries = {
    "food_drink.js": [
        {"word": "Apfelsine", "level": "starter", "theme": "food_drink", "emoji": "🍊", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Saftige süße Zitrusfrucht.", "examples": ["Eine frische Apfelsine schälen."]}], "lang": "de", "transcription": "apfl̩ˈziːnə", "id": "de_starter_food_drink_013"},
        {"word": "Zucker", "level": "starter", "theme": "food_drink", "emoji": "🍬", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Süßungsmittel für Kaffee und Kuchen.", "examples": ["Ich nehme Zucker im Kaffee."]}], "lang": "de", "transcription": "ˈt͡sʊkɐ", "id": "de_starter_food_drink_014"},
        {"word": "Salz", "level": "starter", "theme": "food_drink", "emoji": "🧂", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Wichtiges Gewürz in der Küche.", "examples": ["Bitte das Salz reichen."]}], "lang": "de", "transcription": "zalt͡s", "id": "de_starter_food_drink_015"},
        {"word": "Gemüse", "level": "starter", "theme": "food_drink", "emoji": "🥦", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gesunde Pflanzennahrung.", "examples": ["Gemüse ist gesund."]}], "lang": "de", "transcription": "ɡəˈmyːzə", "id": "de_starter_food_drink_016"},
        {"word": "Obst", "level": "starter", "theme": "food_drink", "emoji": "🍎", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Süße Früchte zum Essen.", "examples": ["Essen Sie viel Obst."]}], "lang": "de", "transcription": "oːpst", "id": "de_starter_food_drink_017"}
    ],
    "nature.js": [
        {"word": "Himmel", "level": "starter", "theme": "nature", "emoji": "🌌", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Der Raum über der Erde.", "examples": ["Der Himmel ist blau."]}], "lang": "de", "transcription": "ˈhɪml̩", "id": "de_starter_nature_013"},
        {"word": "Wolke", "level": "starter", "theme": "nature", "emoji": "☁️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Weiße oder graue Ansammlung am Himmel.", "examples": ["Viele Wolken stehen am Himmel."]}], "lang": "de", "transcription": "ˈvɔlkə", "id": "de_starter_nature_014"},
        {"word": "Schnee", "level": "starter", "theme": "nature", "emoji": "❄️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gefrorener weißer Niederschlag im Winter.", "examples": ["Der Schnee fällt im Winter."]}], "lang": "de", "transcription": "ʃneː", "id": "de_starter_nature_015"},
        {"word": "Eis", "level": "starter", "theme": "nature", "emoji": "🧊", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Gefrorenes Wasser.", "examples": ["Das Eis schmilzt in der Sonne."]}], "lang": "de", "transcription": "aɪ̯s", "id": "de_starter_nature_016"},
        {"word": "Wetter", "level": "starter", "theme": "nature", "emoji": "🌤️", "form": "noun", "classification": "regular", "countability": "uncountable", "definitions": [{"text": "Zustand der Atmosphäre.", "examples": ["Das Wetter ist heute sehr schön."]}], "lang": "de", "transcription": "ˈvɛtɐ", "id": "de_starter_nature_017"}
    ],
    "places.js": [
        {"word": "Apotheke", "level": "starter", "theme": "places", "emoji": "💊", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Geschäft für Medikamente.", "examples": ["Ich kaufe Medizin in der Apotheke."]}], "lang": "de", "transcription": "apoˈteːkə", "id": "de_starter_places_011"},
        {"word": "Hotel", "level": "starter", "theme": "places", "emoji": "🏨", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Unterkunft für Reisende.", "examples": ["Wir übernachten im Hotel."]}], "lang": "de", "transcription": "hoˈtɛl", "id": "de_starter_places_012"},
        {"word": "Flughafen", "level": "starter", "theme": "places", "emoji": "✈️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort für Flugzeuge und Passagiere.", "examples": ["Wir fahren zum Flughafen."]}], "lang": "de", "transcription": "ˈfluːkˌhaːfn̩", "id": "de_starter_places_013"},
        {"word": "Bäckerei", "level": "starter", "theme": "places", "emoji": "🥖", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Geschäft für Brot und Kuchen.", "examples": ["Ich kaufe Brötchen in der Bäckerei."]}], "lang": "de", "transcription": "bɛkəˈʁaɪ̯", "id": "de_starter_places_014"},
        {"word": "Büro", "level": "starter", "theme": "places", "emoji": "🏢", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Arbeitsraum mit Schreibtisch.", "examples": ["Mein Büro ist im zweiten Stock."]}], "lang": "de", "transcription": "byˈʁoː", "id": "de_starter_places_015"}
    ],
    "shopping.js": [
        {"word": "Rechnung", "level": "starter", "theme": "shopping", "emoji": "🧾", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Papier mit dem zu zahlenden Betrag.", "examples": ["Die Rechnung, bitte!"]}], "lang": "de", "transcription": "ˈʁɛçnʊŋ", "id": "de_starter_shopping_009"},
        {"word": "Tasche", "level": "starter", "theme": "shopping", "emoji": "👜", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Behälter für Einkäufe und Sachen.", "examples": ["Ich trage die Einkäufe in der Tasche."]}], "lang": "de", "transcription": "ˈtaʃə", "id": "de_starter_shopping_010"},
        {"word": "Markt", "level": "starter", "theme": "shopping", "emoji": "🧺", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Platz für den Verkauf frischer Waren.", "examples": ["Ich kaufe Gemüse auf dem Markt."]}], "lang": "de", "transcription": "maʁkt", "id": "de_starter_shopping_011"},
        {"word": "Kunde", "level": "starter", "theme": "shopping", "emoji": "🧑", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Käufer im Geschäft.", "examples": ["Der Kunde bezahlt an der Kasse."]}], "lang": "de", "transcription": "ˈkʊndə", "id": "de_starter_shopping_012"},
        {"word": "Angebot", "level": "starter", "theme": "shopping", "emoji": "🏷️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Günstige Ware im Verkauf.", "examples": ["Das Brot ist heute im Angebot."]}], "lang": "de", "transcription": "ˈanɡəˌboːt", "id": "de_starter_shopping_013"}
    ],
    "travel.js": [
        {"word": "Fahrkarte", "level": "starter", "theme": "travel", "emoji": "🎟️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Billett für Bus oder Bahn.", "examples": ["Haben Sie Ihre Fahrkarte dabei?"]}], "lang": "de", "transcription": "ˈfaːɐ̯ˌkaʁtə", "id": "de_starter_travel_007"},
        {"word": "Koffer", "level": "starter", "theme": "travel", "emoji": "🧳", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Gepäckstück für Kleidung auf Reisen.", "examples": ["Mein Koffer ist schwer."]}], "lang": "de", "transcription": "ˈkɔfɐ", "id": "de_starter_travel_008"},
        {"word": "Urlaub", "level": "starter", "theme": "travel", "emoji": "🏖️", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Arbeitsfreie Zeit zur Erholung.", "examples": ["Wir machen Urlaub in Spanien."]}], "lang": "de", "transcription": "ˈuːɐ̯laʊ̯p", "id": "de_starter_travel_009"},
        {"word": "Pass", "level": "starter", "theme": "travel", "emoji": "🛂", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Amtliches Dokument für Auslandsreisen.", "examples": ["Zeigen Sie bitte Ihren Pass."]}], "lang": "de", "transcription": "pas", "id": "de_starter_travel_010"},
        {"word": "Haltestelle", "level": "starter", "theme": "travel", "emoji": "🏣", "form": "noun", "classification": "regular", "countability": "countable", "definitions": [{"text": "Ort, an dem der Bus stoppt.", "examples": ["Die Haltestelle ist gleich um die Ecke."]}], "lang": "de", "transcription": "ˈhaltəˌʃtɛlə", "id": "de_starter_travel_011"}
    ]
}

for cat, entries in more_de_entries.items():
    filep = os.path.join(BASE_DIR, "A1", cat)
    with open(filep, "r", encoding="utf-8") as f:
        content = f.read()
    # parse existing JSON data
    import re
    m = re.search(r"const data = (\[[\s\S]*?\]);", content)
    if m:
        arr = json.loads(m.group(1))
        arr.extend(entries)
        write_js(filep, "de", arr)

print("Added additional German entries!")
