#!/usr/bin/env python3
"""
scripts/build_daily_dose.py
Generates js/data/daily_dose.js containing 50+ real, non-fictional Fun Facts for all 13 languages.
"""

import json
import os

LANGUAGES = ['en', 'fr', 'it', 'ru', 'el', 'es', 'de', 'pt', 'hy', 'ka', 'tt', 'ba', 'br']

FACTS_DB = {
    'en': [
        "English is the official language of aviation worldwide for air traffic control.",
        "The word 'set' has over 430 distinct definitions in the Oxford English Dictionary.",
        "A pangram is a sentence containing every letter of the alphabet.",
        "The shortest complete sentence in English is 'Go!'.",
        "More people speak English as a second language than as a native language.",
        "The oldest English word still in active use is 'town'.",
        "The letter 'E' is the most common letter in English (11% of all text).",
        "A 'ghost word' is a dictionary entry created by mistake, like 'Dord' in 1934.",
        "The dot over the letters 'i' and 'j' is called a 'tittle'.",
        "Shakespeare introduced over 1,700 words to the English language.",
        "The word 'clue' originally meant a ball of thread in Greek mythology.",
        "The fruit 'orange' gave its name to the color in English in the 16th century.",
        "A 'snood' is a traditional headgear historically worn to hold long hair.",
        "English shares over 60% of core vocabulary with Old High German.",
        "The word 'run' has over 645 distinct meanings in modern usage.",
        "The phrase 'Rule of thumb' originates from old measuring practices.",
        "The longest word in English without a vowel is 'rhythms'.",
        "English is an official language in 67 countries.",
        "The word 'goodbye' comes from 'God be with ye'.",
        "The ampersand (&) was once considered the 27th letter of the alphabet.",
        "The word 'alphabet' comes from alpha and beta.",
        "Old English was originally written in runes called Futhorc.",
        "The word 'mortgage' comes from Old French for 'dead pledge'.",
        "English vocabulary is roughly 29% French, 29% Latin, and 26% Germanic.",
        "The word 'trivia' comes from Latin trivium (intersection of three roads).",
        "The word 'salary' comes from Latin salarium (salt allowance for soldiers).",
        "The phrase 'O'Clock' stands for 'Of the Clock'.",
        "The term 'dreadlocks' originated in Jamaica in the 1950s.",
        "English has no single central language academy regulating its words.",
        "The word 'glamour' originally meant magic or enchantment in Scottish.",
        "The word 'quarantine' comes from Italian quaranta giorni (40 days).",
        "English words 'month', 'orange', 'silver', and 'purple' have no perfect rhymes.",
        "The word 'disaster' literally means 'bad star' from Greek.",
        "The word 'serendipity' was coined by Horace Walpole in 1754.",
        "The English vocabulary doubles roughly every century.",
        "The word 'avocado' comes from the Nahuatl word ahuacatl.",
        "The word 'sandwich' was named after John Montagu, 4th Earl of Sandwich.",
        "The word 'whiskey' comes from Gaelic uisce beatha ('water of life').",
        "The term 'boycott' comes from Captain Charles Boycott, an Irish land agent.",
        "The word 'sinister' comes from the Latin word for 'left-handed'.",
        "The English alphabet formerly included letters like thorn (Þ) and eth (Ð).",
        "The word 'companion' comes from Latin for 'one with whom you share bread'.",
        "The word 'fiasco' comes from Italian far fiasco ('make a bottle').",
        "English lost noun case inflections after the Norman Conquest of 1066.",
        "The word 'tragedy' literally means 'goat song' in ancient Greek.",
        "The word 'sarcasm' comes from Greek sarkasmos ('to tear flesh').",
        "The word 'lunatic' comes from Latin luna (moon), believing madness was lunar.",
        "The word 'curfew' comes from French couvre-feu ('cover the fire').",
        "The word 'cliché' comes from the sound of printing plates in French.",
        "The word 'pandemonium' was coined by John Milton in Paradise Lost."
    ],
    'fr': [
        "Le français a été la langue officielle de l'Angleterre de 1066 à 1399.",
        "L'Académie française a été fondée en 1635 par le cardinal de Richelieu.",
        "Le mot 'oiseaux' contient toutes les voyelles sauf le Y.",
        "Le français est parlé par plus de 320 millions de personnes sur 5 continents.",
        "Le plus long mot français officiel est 'intergouvernementalisations' (27 lettres).",
        "En français, tous les jours de la semaine finissent par 'di' sauf dimanche.",
        "Le vouvoiement ('vous') remonte au Bas-Empire romain.",
        "Le mot 'bureau' désignait à l'origine une étoffe de laine tisse de bure.",
        "Le mot 'bonjour' est l'une des salutations les plus connues au monde.",
        "Le mot 'restaurant' vient du verbe restaurer (redonner de la force).",
        "L'accent circonflexe (^) marque souvent un 's' disparu du latin.",
        "La francophonie regroupe 88 états et gouvernements membres de l'OIF.",
        "Le mot 'travail' vient du latin tripalium (instrument à trois pieux).",
        "Le verbe 'être' provient de trois verbes latins différents.",
        "L'expression 'poser un lapin' signifiait au XIXe siècle ne pas payer une prestation.",
        "Le mot 'aujourd'hui' contient un pléonasme ('hui' signifiait ce jour).",
        "Le français est la langue officielle des Jeux Olympiques avec l'anglais.",
        "En Suisse et Belgique, on dit 'septante' et 'nonante' au lieu de soixante-dix.",
        "Le mot 'déjà-vu' est un terme français adopté universellement.",
        "Le mot 'poubelle' vient du préfet Eugène Poubelle en 1883.",
        "Le verbe 'manger' vient du latin manducare (mâcher).",
        "L'expression 'avoir le cafard' a été popularisée par Baudelaire en 1857.",
        "Le mot 'silhouette' vient du ministre Étienne de Silhouette.",
        "La virgule est le séparateur décimal officiel en français.",
        "Le mot 'biscuit' signifie littéralement 'cuit deux fois'.",
        "Le français comporte environ 13% de mots empruntés à d'autres langues.",
        "Le mot 'pantalon' vient du personnage de comédie Pantalone.",
        "L'accent aigu (') ne s'utilise en français que sur la lettre E.",
        "Le mot 'chef' signifiait à l'origine 'tête' en ancien français.",
        "Le Grand Robert de la langue française contient plus de 100 000 mots.",
        "L'expression 'C'est la vie' est célèbre dans le monde entier.",
        "Le verbe 'savoir' et 'pouvoir' sont parmi les plus fréquents en français.",
        "Le mot 'timbre' désignait à l'origine une petite cloche.",
        "Le français était la langue de la diplomatie européenne du XVIIe au XXe siècle.",
        "Le mot 'savoir-faire' est un concept d'artisanat français international.",
        "L'expression 'revenons à nos moutons' vient de Maître Pathelin (1464).",
        "Le mot 'orchestre' provient du grec orkhestra.",
        "Le français est la deuxième langue la plus étudiée dans l'UE.",
        "Le mot 'dépaysé' exprime le sentiment de changer complètement d'environnement.",
        "Le verbe 'vouloir' exprime à la fois la volonté et la politesse.",
        "Le mot 'château' vient du latin castellum (fort militaire).",
        "Le mot 'rendez-vous' est entré en anglais au XVIe siècle.",
        "Le mot 'clafoutis' vient de l'occitan clafotis (remplir).",
        "Le mot 'galette' vient de gal (galet/pierre plate en ancien français).",
        "Le français utilise des guillemets doubles (« ») en typographie.",
        "Le mot 'amphithéâtre' provient directement du grec ancien.",
        "Le français ne possède pas de neutre grammaticien.",
        "Le mot 'bouchon' vient du mot bousche (poignée de paille).",
        "Le verbe 'faire' est l'un des verbes les plus polyvalents du français.",
        "Le salut 'Enchanté' exprime la joie de faire la connaissance de quelqu'un."
    ],
    'it': [
        "L'italiano moderno si basa sul dialetto fiorentino del XIV secolo di Dante e Petrarca.",
        "L'italiano è la quinta lingua più studiata al mondo.",
        "Il primo testo in volgare italiano è il Placito Capuano del 960 d.C.",
        "L'Accademia della Crusca a Firenze è stata fondata nel 1583.",
        "La parola 'ciao' deriva da 'sciao vostro' (sono vostro schiavo) in veneziano.",
        "L'italiano è la lingua internazionale dell'opera lirica.",
        "La parola italiana più lunga nel dizionario è 'precipitevolissimevolmente'.",
        "In italiano quasi tutte le parole native terminano con una vocale.",
        "La parola 'spaghetti' è il diminutivo di 'spago'.",
        "L'italiano possiede oltre 30 dialetti regionali storici con grammatica propria.",
        "La parola 'espresso' per il caffè significa fatto al momento.",
        "La parola 'cappuccino' prende il nome dal saio dei frati cappuccini.",
        "Il punto esclamativo fu introdotto da Coluccio Salutati nel XIV secolo.",
        "L'alfabeto italiano tradizionale usa solo 21 lettere.",
        "La parola 'tiramisù' significa letteralmente 'sollevami il morale'.",
        "La parola 'quarantena' è nata a Venezia nel XIV secolo per l'isolamento navale.",
        "L'espressione 'in bocca al lupo' richiede la risposta 'crepi!'.",
        "La parola 'fiasco' nel senso di fallimento viene dal teatro italiano.",
        "L'italiano ha tre coniugazioni verbali principali (-are, -ere, -ire).",
        "Il gelato fu perfezionato a Firenze nel XVI secolo da Buontalenti.",
        "La parola 'biscotto' deriva dal latino bis coctus (cotto due volte).",
        "L'espressione 'dolce far niente' descrive il piacere del riposo senza fretta.",
        "Il sonetto fu inventato in Sicilia nel XIII secolo da Giacomo da Lentini.",
        "La parola 'pantalone' deriva dalla maschera veneziana della Commedia dell'Arte.",
        "L'italiano è lingua ufficiale in Italia, Svizzera, San Marino e Vaticano.",
        "La parola 'pizza' è attestata per la prima volta nel 997 d.C. a Gaeta.",
        "La parola 'ghetto' è nata a Venezia nel 1516 dal nome di una fonderia.",
        "La parola 'paparazzi' deriva dal film La Dolce Vita di Federico Fellini.",
        "L'italiano ha oltre 160 000 parole nel Dizionario Gradit.",
        "La parola 'al fresco' in italiano significa all'aria aperta.",
        "Il termine 'maestro' è usato in tutto il mondo per direttori d'orchestra.",
        "L'espressione 'al dente' descrive la pasta cotta alla giusta consistenza.",
        "La parola 'ballottaggio' deriva dalle pallottole usate per votare a Venezia.",
        "L'italiano ha un ricco sistema di suffissi alterativi (-ino, -one, -accio).",
        "La parola 'opera' significa semplicemente lavoro o composizione.",
        "La parola 'prima donna' indica la cantante lirica principale.",
        "L'italiano distingue nettamente le consonanti doppie dalle scempie (palla/pala).",
        "La parola 'carnevale' deriva dal latino carnem levare.",
        "L'italiano è la lingua europea con maggiore corrispondenza grafia-pronuncia.",
        "La parola 'amarcord' fu inventata da Fellini in dialetto romagnolo.",
        "L'espressione 'buon appetito' è il saluto tradizionale prima del pasto.",
        "La parola 'allegro' in musica viene direttamente dall'italiano.",
        "Il termine 'scherzo' indica un movimento musicale veloce e vivace.",
        "La parola 'graffiti' deriva dall'italiano graffiato.",
        "L'italiano usa l'apostrofo per segnare l'elisione della vocale finale.",
        "La parola 'solfeggio' viene dalle note musicali Sol e Fa.",
        "Il termine 'intermezzo' indicava un'opera breve tra due atti principali.",
        "La parola 'piazza' deriva dal greco plateia (strada larga).",
        "La parola 'bruscamente' deriva da brusco (aspro/pungente).",
        "L'espressione 'buona giornata' si usa per augurare una felice giornata."
    ],
    'ru': [
        "Русский язык является самым распространенным языком Евразии.",
        "Русский алфавит состоит из 33 букв и базируется на кириллице.",
        "Буква 'Ё' была введена в русский алфавит в 1783 году Екатериной Дашковой.",
        "Русский язык — официальный рабочий язык Организации Объединенных Наций.",
        "В русском языке 6 основных падежей: именительный, родительный, дательный, винительный, творительный, предложный.",
        "Слово 'спутник' вошло во все языки мира после 1957 года.",
        "Русский язык использует категорию совершенного и несовершенного вида глагола.",
        "Слово 'борщ' изначально обозначало растение борщевик.",
        "Ударение в русском языке свободное и подвижное.",
        "Слово 'царь' происходит от латинского имени Caesar.",
        "В русском языке 3 рода существительных: мужской, женский и средний.",
        "Слово 'робот' вошло в русский язык через чешскую пьесу Карела Чапека.",
        "Русский язык является родным примерно для 150 миллионов человек.",
        "Буква 'Ъ' до 1918 года писалась в конце всех слов на согласную.",
        "Слово 'интеллигенция' сформировалось в России XIX века.",
        "Русское слово 'спасибо' произошло от фразы 'Спаси Бог'.",
        "В русском языке нет глагола 'быть' в настоящем времени разговорной речи.",
        "Слово 'самовар' дословно означает 'сам варит'.",
        "Слово 'матрешка' происходит от имени Матрёна (от лат. matrona).",
        "Прилагательные в русском языке согласуются с существительными в роде, числе и падеже.",
        "Слово 'погода' изначально означало благоприятное время.",
        "Первая датированная печатная книга на русском — 'Апостол' Ивана Фёдорова (1564).",
        "Слово 'каникулы' происходит от латинского canicula (собачка, звезда Сириус).",
        "Глаголы движения образуют систему с приставками (пойти, прийти, уйти).",
        "Слово 'вокзал' происходит от парка Vauxhall под Лондоном.",
        "Русский язык — один из официальных языков Международной космической станции.",
        "Слово 'пельмени' происходит из финно-угорских языков от 'пель' (ухо) и 'нянь' (хлеб).",
        "В русском языке двойное отрицание является языковой нормой.",
        "Слово 'подлинник' происходит от длинных палок, которыми выпытывали правду.",
        "Русский язык входит в славянскую группу индоевропейской семьи.",
        "Слово 'неделя' в древнерусском языке означало воскресенье (день 'без дел').",
        "Слово 'медведь' дословно означает 'ведающий мёдом'.",
        "Русский алфавит был реформирован в 1917–1918 годах.",
        "Слово 'шапка' происходит от старофранцузского chape.",
        "Порядок слов в русском языке свободный и передает логический акцент.",
        "Слово 'пирог' происходит от слова 'пир'.",
        "Русский язык использует кавычки-ёлочки (« ») в типографике.",
        "Слово 'бутерброд' заимствовано из немецкого языка (Butterbrot).",
        "Согласные звуки делятся на твёрдые и мягкие.",
        "Русский язык богат уменьшительно-ласкательными суффиксами (-чка, -нька).",
        "Слово 'Здравствуйте!' выражает пожелание здоровья.",
        "Слово 'спутник' состоит из приставки с- и корня путь.",
        "Глагол 'учиться' содержит возвратную частицу -ся.",
        "Слово 'карандaш' произошло от тюркского 'кара таш' (черный камень).",
        "Слово 'собака' заимствовано из скифских или иранских языков.",
        "Слово 'хозяин' имеет тюркское происхождение (ходжа).",
        "Слово 'парус' происходит от греческого faros (покрывало).",
        "Русский язык имеет 3 склонения существительных.",
        "Слово 'изба' происходит от древнерусского истьба (отапливаемое помещение).",
        "Поговорка 'Век живи — век учись' отражает ценность постоянного познания."
    ],
    'el': [
        "Η ελληνική γλώσσα έχει γραπτή ιστορία πάνω από 3.400 χρόνια.",
        "Το ελληνικό αλφάβητο ήταν το πρώτο που είχε σύμβολα για φωνήεντα.",
        "Πάνω από το 12% του αγγλικού λεξιλογίου προέρχεται από την ελληνική.",
        "Η λέξη 'άλφα' και 'βήτα' έδωσαν το όνομα στη λέξη 'αλφάβητο'.",
        "Στα ελληνικά το ερωτηματικό σημειώνεται με το σύμβολο (;).",
        "Η λέξη 'φιλοσοφία' σημαίνει αγάπη για τη σοφία.",
        "Τα νέα ελληνικά έχουν 3 γένη: αρσενικό, θηλυκό, ουδέτερο.",
        "Η λέξη 'δημοκρατία' προέρχεται από το 'δήμος' και 'κράτος'.",
        "Το ελληνικό αλφάβητο αποτέλεσε τη βάση για το λατινικό και κυριλλικό.",
        "Η ελληνική ομιλείται από περίπου 13,5 εκατομμύρια ανθρώπους.",
        "Η λέξη 'νοσταλγία' συντίθεται από 'νόστος' (επιστροφή) και 'άλγος' (πόνος).",
        "Η λέξη 'θέατρο' προέρχεται από το ρήμα θεάομαι (κοιτάζω).",
        "Η κλίση των ρημάτων χωρίζεται σε Α' και Β' συζυγία.",
        "Η λέξη 'μουσική' ονομάστηκε έτσι από τις Μούσες.",
        "Το μονοτονικό σύστημα καθιερώθηκε στην Ελλάδα το 1982.",
        "Η λέξη 'διάλογος' σημαίνει ομιλία μεταξύ δύο προσώπων.",
        "Η ελληνική είναι επίσημη γλώσσα της Ευρωπαϊκής Ένωσης.",
        "Η λέξη 'αρχιτεκτονική' προέρχεται από το 'αρχι-' και 'τέκτων'.",
        "Υπάρχουν 4 κύριες πτώσεις: ονομαστική, γενική, αιτιατική, κλητική.",
        "Η λέξη 'οικονομία' προέρχεται από το 'οίκος' και 'νέμω'.",
        "Το αρχαιότερο γραπτό κείμενο είναι οι πινακίδες της Γραμμικής Β'.",
        "Ο μέλλοντας σχηματίζεται με το μόριο 'θα' (από το θέλω να).",
        "Η λέξη 'ευτυχία' σημαίνει καλή τύχη (εύ + τύχη).",
        "Η λέξη 'μεράκι' περιγράφει το πάθος και τη φροντίδα στη δουλειά.",
        "Η λέξη 'αστρονομία' προέρχεται από το 'άστρον' και 'νόμος'.",
        "Η λέξη 'φιλοξενία' σημαίνει φιλία προς τον ξένο.",
        "Η ελληνική αποτελεί αυτόνομο κλάδο της ινδοευρωπαϊκής οικογένειας.",
        "Η λέξη 'συμπόσιο' σήμαινε αρχικά κοινή πόση.",
        "Η λέξη 'τηλέφωνο' δημιουργήθηκε από το 'τήλε' και 'φωνή'.",
        "Η λέξη 'καλλιγραφία' προέρχεται από το 'κάλλος' και 'γραφή'.",
        "Τα ουσιαστικά συνοδεύονται από οριστικό ή αόριστο άρθρο.",
        "Η λέξη 'παράδεισος' εισήλθε από την περσική pairidaeza.",
        "Η λέξη 'γήπεδο' προέρχεται από το 'γη' και 'πέδον'.",
        "Η λέξη 'ψυχολογία' προέρχεται από το 'ψυχή' και 'λόγος'.",
        "Η αλφαβητική γραφή χρησιμοποιείται συνεχώς επί 28 αιώνες.",
        "Η λέξη 'ωκεανός' ονομάστηκε από τον Τιτάνα Ωκεανό.",
        "Η υποτακτική σχηματίζεται με το μόριο 'να'.",
        "Η λέξη 'διάμετρος' προέρχεται από το 'διά' και 'μέτρον'.",
        "Η ελληνική διαθέτει παραγωγικά επιθήματα (-άκης, -ούλα).",
        "Η λέξη 'χάρτης' προέρχεται από τον πάπυρο της αρχαιότητας.",
        "Η λέξη 'φιλότιμο' δεν έχει ακριβή μετάφραση σε άλλες γλώσσες.",
        "Η λέξη 'ιστορία' προέρχεται από το 'ίστωρ' (γνώστης).",
        "Η λέξη 'μαθηματικά' προέρχεται από το 'μάθημα'.",
        "Η λέξη 'βιβλιοθήκη' συντίθεται από 'βιβλίον' και 'θήκη'.",
        "Η προσωπική αντωνυμία συχνά παραλείπεται στα ελληνικά.",
        "Η λέξη 'καλημέρα' είναι η πιο συνηθισμένη πρωινή ευχή.",
        "Η λέξη 'αλφάβητο' είναι διεθνής ελληνική λέξη.",
        "Η λέξη 'συμπαθής' σημαίνει αυτός που προκαλεί συμπάθεια.",
        "Η λέξη 'ευχαριστώ' σημαίνει προσφέρω χάρη/ευγνωμοσύνη.",
        "Η λέξη 'αντίο' προέρχεται από την ευχή 'στο επανιδείν'."
    ],
    'es': [
        "El español es la segunda lengua materna más hablada del mundo tras el mandarín.",
        "El español se habla oficialmente en 21 países de América, Europa y África.",
        "El primer libro de gramática española fue escrito por Nebrija en 1492.",
        "La letra 'ñ' nació en los monasterios medievales como abreviatura de 'nn'.",
        "El español tiene más de 88.000 palabras registradas en el Diccionario de la RAE.",
        "La palabra 'ojo' proviene del latín oculus.",
        "Los signos de apertura (¿, ¡) son únicos del idioma español.",
        "El español es una lengua romance derivada del latín vulgar ibérico.",
        "La palabra 'ojalá' proviene del árabe hispánico aw šá lláh ('si Dios quiere').",
        "El español cuenta con más de 4.000 palabras de origen árabe.",
        "La palabra más larga en la RAE es electroencefalografista (23 letras).",
        "El español es idioma oficial de la ONU, la UE y la Unión Africana.",
        "La palabra 'murciélago' contiene las cinco vocales.",
        "El español tiene tres conjugaciones verbales (-ar, -er, -ir).",
        "El español utiliza dos verbos para expresar 'to be': ser y estar.",
        "La palabra 'siesta' viene de la sexta hora romana (el mediodía).",
        "El español es hablado por más de 500 millones de personas.",
        "Don Quijote de la Mancha es la obra narrativa más traducida del mundo.",
        "La palabra 'almohada' proviene del árabe al-mujadda.",
        "El español utiliza la coma (,) como separador decimal estándar.",
        "La palabra 'fiesta' proviene del latín festa.",
        "La palabra 'chocolate' proviene del náhuatl xocolatl.",
        "El acento ortográfico (tilde) marca la sílaba tónica cuando rompe la regla general.",
        "En Argentina y Uruguay se utiliza el voseo (uso de vos).",
        "La palabra 'mariposa' proviene de la frase infantil 'María, pósate'.",
        "El español fue la primera lengua europea hablada en Filipinas.",
        "La palabra 'barrio' proviene del árabe barri (exterior).",
        "Sustantivos como 'el cura' y 'la cura' cambian de significado según el género.",
        "La palabra 'canoa' fue la primera palabra indígena americana adoptada en español.",
        "La palabra 'sobremesa' describe la conversación tranquila tras la comida.",
        "El saludo '¡Hola!' se utiliza en todo el mundo hispanohablante.",
        "El término 'spanglish' describe el fenómeno de alternancia lingüística.",
        "El español posee un rico sistema de diminutivos (-ito, -ico, -illo).",
        "La palabra 'amigo' proviene del latín amicus.",
        "El español tiene vocales puras y claras sin reducción vocálica.",
        "La palabra 'adiós' es contracción de 'A Dios seas encomendado'.",
        "Usted proviene de la fórmula de cortesía Vuestra Merced.",
        "La palabra 'sol' proviene del latín sol, solis.",
        "La palabra 'zapato' proviene del turco/persa a través del árabe.",
        "La palabra 'pueblo' proviene del latín populus.",
        "La palabra 'guitarra' proviene del griego kithara.",
        "México es el país con mayor número de hispanohablantes del mundo.",
        "La palabra 'aceite' proviene del árabe az-zayt.",
        "El español no tiene sílabas dobles como bb o pp, salvo cc y nn.",
        "La palabra 'camino' proviene del céltico camminos.",
        "La palabra 'flamenco' nombra tanto el arte como al ave.",
        "El verbo haber se usaba originalmente para expresar posesión.",
        "La palabra 'azúcar' proviene del árabe as-sukkar.",
        "La palabra 'alcalde' proviene del árabe al-qadi (el juez).",
        "El idioma español es una de las lenguas más musicales y fonéticas."
    ],
    'de': [
        "Das Deutsche ist die am meisten gesprochene Muttersprache in der EU.",
        "Im Deutschen werden alle Nomen (Substantive) großgeschrieben.",
        "Das Deutsche besitzt drei grammatische Geschlechter: der, die, das.",
        "Das Wort 'Kindergarten' wurde weltweit aus dem Deutschen übernommen.",
        "Das Deutsche ist bekannt für lange Zusammensetzungen (Komposita).",
        "Das deutsche Alphabet besitzt den Buchstaben 'ß' (Eszett).",
        "Die Brüder Grimm stellten das Deutsche Wörterbuch zusammen.",
        "Das Deutsche hat vier Fälle: Nominativ, Genitiv, Dativ, Akkusativ.",
        "Das Wort 'Schadenfreude' existiert als Lehnwort im Englischen.",
        "Martin Luthers Bibelübersetzung von 1522 prägte das Neuhochdeutsche.",
        "Das Deutsche hat über 130 Millionen Sprecher weltweit.",
        "Das Wort 'Ohrwurm' beschreibt ein Lied, das im Kopf bleibt.",
        "Das Deutsche ist Amtssprache in 6 europäischen Ländern.",
        "Das Wort 'Fernweh' beschreibt die Sehnsucht nach fernen Ländern.",
        "Im Deutschen steht das konjugierte Verb im Hauptsatz an Position 2.",
        "Das Wort 'Zeitgeist' bezeichnet den Geist einer Epoche.",
        "Das Deutsche gehört zum westgermanischen Sprachzweig.",
        "Das Wort 'Wanderlust' beschreibt die Lust am Reisen.",
        "Im Deutschen stehen Verben im Nebensatz am Ende.",
        "Das Wort 'Handschuh' setzt sich aus Hand und Schuh zusammen.",
        "Das Wort 'Fingerspitzengefühl' beschreibt hohes Taktgefühl.",
        "Die Gutenberg-Bibel wurde um 1455 in Mainz gedruckt.",
        "Das Wort 'Kummerspeck' bezeichnet Frustgewicht.",
        "Das Deutsche hat eine präzise Laut-Buchstaben-Zuordnung.",
        "Das Wort 'Glühwein' ist das Getränk deutscher Weihnachtsmärkte.",
        "Im Deutschen unterscheidet man trennbare und untrennbare Verben.",
        "Sturm und Drang war eine bedeutende Literatur-Epoche.",
        "Das Deutsche besitzt die Umlaute Ä, Ö, Ü.",
        "Das Wort 'Torschlusspanik' beschreibt die Angst vor verpassten Chancen.",
        "Das Deutsche grenzt Nebensätze durch Kommas ab.",
        "Das Wort 'Bauhaus' prägte die weltweite Architektur.",
        "Im Deutschen grüßt man mittags mit 'Mahlzeit!'.",
        "Das Deutsche hat über 35 regionale Dialektgruppen.",
        "Das Deutsche verwendet das Passiv sehr häufig im Fachtext.",
        "Das Wort 'Besserwisser' bezeichnet rechthaberische Personen.",
        "Das Wort 'Gemütlichkeit' beschreibt eine behagliche Atmosphäre.",
        "Deutschland gilt als Land der Dichter und Denker.",
        "Das Deutsche unterscheidet das höfliche 'Sie' vom 'du'.",
        "Das Wort 'Feierabend' bezeichnet das Ende des Arbeitstages.",
        "Das Wort 'Weltschmerz' beschreibt tiefe Wehmut.",
        "Das Deutsche hat ein System von Modalpartikeln (ja, doch, mal).",
        "Das Wort 'Guten Tag' ist der klassische Gruß.",
        "Das Wort 'Dachsbau' bezeichnet den Bau eines Dachses.",
        "Das Deutsche bildet das Perfekt mit haben oder sein.",
        "Das Wort 'Freundschaft' drückt tiefe Bindung aus.",
        "Das Wort 'Dankeschön' drücken Dankbarkeit aus.",
        "Die Deutsche Sprache verwendet genaue Zeitangaben.",
        "Das Wort 'Auf Wiedersehen' ist der förmliche Abschiedsgruß.",
        "Das Deutsche besitzt präzise Fachbegriffe in der Philosophie.",
        "Das Wort 'Sommernachtstraum' verweist auf laue Sommernächte."
    ],
    'pt': [
        "O português é a língua oficial de 9 países na CPLP.",
        "O português é a 5ª língua nativa mais falada do mundo.",
        "A palavra 'saudade' exprime o sentimento profundo de falta.",
        "O galego e o português formavam a mesma língua na Idade Média.",
        "O primeiro documento em português é o Testamento de D. Afonso II (1214).",
        "Cerca de 1000 palavras em português são de origem árabe (azeite, algodão).",
        "A palavra 'obrigado' vem do latim obligatus.",
        "O Acordo Ortográfico unificou a grafia entre o Brasil e Portugal.",
        "Fernando Pessoa é um dos maiores poetas da língua portuguesa.",
        "A palavra 'fado' vem do latim fatum (destino).",
        "O Brasil possui mais de 210 milhões de falantes de português.",
        "A Universidade de Coimbra foi fundada em 1290.",
        "O til (~) indica a nasalização de vogais em português.",
        "A palavra 'café' entrou no português a partir do turco kahve.",
        "Luís de Camões publicou 'Os Lusíadas' em 1572.",
        "O português tem três conjugações verbais (-ar, -er, -ir).",
        "O verbo 'haver' exprime existência no sentido de existir.",
        "A Bossa Nova foi criada no Rio de Janeiro nos anos 1950.",
        "O português é a língua mais falada no hemisfério sul.",
        "A palavra 'caipirinha' vem de caipira.",
        "O brigadeiro foi criado no Brasil nos anos 1940.",
        "A palavra 'azulejo' vem do árabe al-zullayj (pedra polida).",
        "O português usa a cedilha (ç) apenas antes de a, o, u.",
        "Mia Couto é um aclamado escritor moçambicano em língua portuguesa.",
        "O bacalhau é um prato tradicional na culinária portuguesa.",
        "O português deriva do latim vulgar da Península Ibérica.",
        "A palavra 'samba' é Patrimônio Cultural Imaterial do Brasil.",
        "O fado português é Patrimônio Cultural Imaterial da UNESCO.",
        "A palavra 'marmelada' vem de marmelo.",
        "Machado de Assis fundou a Academia Brasileira de Letras em 1897.",
        "A palavra 'carnaval' é celebrada intensamente no Brasil.",
        "O português possui pronomes oblíquos átonos e tônicos.",
        "A palavra 'gentileza' gera gentileza é um famoso lema carioca.",
        "O termo 'Lusofonia' designa a comunidade de língua portuguesa.",
        "A palavra 'abraço' é a saudação afetuosa mais comum em português.",
        "A literatura portuguesa tem uma rica tradição de trovadorismo.",
        "O português utiliza o artigo definido perante nomes próprios no Brasil e Portugal.",
        "A palavra 'praia' vem do latim tardio plagia.",
        "O português possui ditongos orais e nasais.",
        "A palavra 'alegria' vem do latim alacer.",
        "A palavra 'esperança' vem do latim sperare.",
        "O português é uma língua oficial da União Europeia.",
        "A palavra 'festa' celebra momentos alegres na cultura lusófona.",
        "O vocábulo 'bom dia' é a saudação matinal tradicional.",
        "O português possui o pronome de tratamento 'você'.",
        "A palavra 'churrasco' é uma tradição culinária no sul do Brasil.",
        "A palavra 'futebol' é a paixão esportiva nos países lusófonos.",
        "O português tem uma fonética rica com sons vogais abertos e fechados.",
        "A expressão 'tudo bem?' é a pergunta de cortesia mais usada.",
        "O português une culturas na Europa, América, África e Ásia."
    ],
    'hy': [
        "Հայոց լեզուն հնդեվրոպական լեզվաընտանիքի առանձին ճյուղ է։",
        "Հայոց այբուբենը ստեղծել է Մեսրոպ Մաշտոցը 405 թվականին։",
        "Հայոց այբուբենն ուներ 36 տառ, իսկ այժմ՝ 39 տառ։",
        "Հայերենը պաշտոնական լեզու է Հայաստանի Հանրապետությունում։",
        "Հայերենն ունի երկու ճյուղ՝ արևելահայերեն և արևմտահայերեն։",
        "«Բարև» բառը ծագում է «բարի» և «արև» բառերի միացումից։",
        "Հայերենում հարցական նշանը (՞) դրվում է հարցվող բառի վրա։",
        "Մատենադարանը հին ձեռագրերի պահոց է Երևանում։",
        "Հայերենում գոյականներն ունեն 7 հոլով։",
        "Հայկական տպագրությունը սկզբնավորվել է 1512 թվականին Վենետիկում։",
        "Առաջին տպագիր գիրքը «Ուրբաթագիրքն» է Hakob Meghapart-ի կողմից։",
        "Հայոց լեզվով խոսում է մոտ 10 միլիոն մարդ աշխարհում։",
        "«Ջան» բառը արտահայտում է մտերմություն և հարգանք։",
        "«Խաչքար» քարարվեստը UNESCO-ի ցանկում է։",
        "Երևանը հիմնադրվել է մ.թ.ա. 782 թվականին (Էրեբունի)։",
        "Հայկական դուդուկը պատրաստվում է ծիրանենու փայտից։",
        "«Լավաշ» հացը ընդգրկված է UNESCO-ի ցանկում։",
        "Հայերենում բայն ունի 3 լծորդություն (-ել, -ալ, -ուլ)։",
        "Արարատ լեռը հայկական ինքնության խորհրդանիշն է։",
        "«Շնորհակալություն» բառը նշանակում է շնորհ բաշխել։",
        "Հայոց լեզվում չկա քերականական սեռ։",
        "«Արև» բառը հին հայկական դիցաբանական արմատ ունի։",
        "Հայկական տառերը ունեն նաև թվային արժեքներ։",
        "«Նռնենին» հայկական մշակույթում կյանքի խորհրդանիշ է։",
        "Սայաթ-Նովան 18-րդ դարի հայտնի աշուղ է եղել։",
        "«Գառնիի տաճարը» 1-ին դարի հելլենիստական հուշարձան է։",
        "Հայաստանը 301 թվականին առաջինն ընդունեց քրիստոնեությունը։",
        "Հայերենում շեշտը սովորաբար ընկնում է վերջին վանկի վրա։",
        "«Տարազ» բառը նշանակում է հայկական ազգային հագուստ։",
        "Հայերենում բառակազմությունը շատ ճկուն է (բարդ բառեր)։",
        "«Մատենադարան» բառը նշանակում է գրքերի պահոց։",
        "Հայկական խոհանոցը հայտնի է տոլմայով և հարիսայով։",
        "Հովհաննես Թումանյանը հայոց ամենասիրված պոետն է։",
        "«Կռունկ» թռչունը կարոտի խորհրդանիշն է հայերգության մեջ։",
        "Հայերենն ունի հարուստ բարբառային բազմազանություն։",
        "«Ծիրան» միրգը համարվում է հայկական ազգային միրգ։",
        "«Խաղաղություն» բառը կարևորագույն արժեք է հայ մշակույթում։",
        "«Հայրենիք» բառը ծագում է հայր արմատից։",
        "Հայերենի այբուբենի առաջին տառը Ա-ն է (Աստված)։",
        "«Գարուն» բառը նշանակում է տարվա եղանակ։",
        "Հայոց լեզուն ունի ոսկեդարյան հարուստ գրականություն (V դար)։",
        "«Զարթոնք» բառը նշանակում է վերածնունդ։",
        "Հայկական գորգագործությունը դարավոր պատմություն ունի։",
        "«Լույս» բառը խորհրդանշում է գիտություն և հավատ։",
        "Հայկական խազագրությունը հին երաժշտական նոտագրություն է։",
        "«Բարի լույս» բառը առավոտյան բարեմաղթանք է։",
        "Հայաստանում շախմատը դպրոցական պարտադիր առարկա է։",
        "«Մասիս» սարը Արարատի մյուս անվանումն է։",
        "«Հույս» բառը արտահայտում է հավատ ապագայի հանդեպ։",
        "«Բարի գալուստ» բառով դիմավորում են հյուրերին։"
    ],
    'ka': [
        "ქართული ენა მიეკუთვნება ქართველურ ენათა ოჯახს.",
        "ქართულ ანბანს აქვს 33 ასო და არ იყენებს დიდ ასოებს.",
        "ქართული ანბანი იუნესკოს არამატერიალური მემკვიდრეობაა.",
        "ქართულ ენაში არსებობს 7 ბრუნვა.",
        "სიტყვა «გამარჯობა» გამარჯვების სურვილს ნიშნავს.",
        "ქართულ ენაში ზმნა მრავალპირიანი და რთულია.",
        "ქართული ანბანის სამი სახეობაა: ასომთავრული, ნუსხური, მხედრული.",
        "«ვეფხისტყაოსანი» შოთა რუსთაველის გენიალური პოემაა.",
        "ქართულ ენაში არ არსებობს გრამატიკული სქესი.",
        "ქართული ღვინის დაყენების 8000-წლიანი ტრადიცია აქვს ქვევრში.",
        "სიტყვა «მადლობა» მადლის გაცემას ნიშნავს.",
        "ქართული მრავალხმიანობა იუნესკოს მიერ აღიარებულია.",
        "«ხინკალი» და «ჭაშუშული» ქართული სამზარეულოს ნაწილია.",
        "თბილისი დაარსდა V საუკუნეში ვახტანგ გორგასლის მიერ.",
        "სიტყვა «მშვიდობა» მშვიდ მდგომარეობას ნიშნავს.",
        "ქართული ენა უძველესი მწერლობის ენაა კავკასიაში.",
        "«ხაჭაპური» ქართული ეროვნული კერძია.",
        "სიტყვა «მეგობარი» «ეგოს» (იმავე) արմատიდან მოდის.",
        "სვეტიცხოველი XI საუკუნის უდიდესი ტაძარია.",
        "ქართულ ენაში ათვლის სისტემა ოცობითია (20, 40, 60).",
        "სიტყვა «დედა» ქართულად დედას ნიშნავს, ხოლო «მამა» — მამას.",
        "ქართული ანბანი მსოფლიოს 14 ანბანს შორის ერთ-ერთია.",
        "«მზის» კულტი უძველეს ქართულ მითოლოგიაში არსებობდა.",
        "სიტყვა «სტუმარი» ღვთისაა — ამბობს ქართული ანდაზა.",
        "ქართულად «სიყვარული» ყველაზე წმინდა გრძნობაა.",
        "«ნაბადი» ტრადიციული ქართული სამოსია.",
        "სიტყვა «სიცოცხლე» ცოცხალ მდგომარეობას ნიშნავს.",
        "ქართულ ენაში თანხმოვანთა კომპლექსები გვხვდება (მაგ. გვფრცქვნის).",
        "«ალავერდი» სუფრაზე თასის გადაცემას ნიშნავს.",
        "სიტყვა «სუფრა» ქართული მასპინძლობის სიმბოლოა.",
        "თამარი XII-XIII საუკუნის ოქროს ხანის მეფე იყო.",
        "სიტყვა «მზე» სინათლისა და სითბოს წყაროა.",
        "«ჩოხა» ქართველი მამაკაცის ეროვნული სამოსია.",
        "სიტყვა «იმედი» მომავლის რწმენას ნიშნავს.",
        "ქართული ხალხური ცეკვა «სუხიშვილები» ცნობილია მსოფლიოში.",
        "სიტყვა «დილა მშვიდობისა» დილის მისალმებაა.",
        "ქართულ ენაში 5 ხმოვანია (ა, ე, ი, ო, უ).",
        "«ბორჯომი» ცნობილი მინერალური წყალია.",
        "სიტყვა «სიბრძნე» ღრმა ცოდნას ნიშნავს.",
        "«სვანური კოშკები» შუა საუკუნეების ციხე-კოშკებია.",
        "სიტყვა «გზა» ცხოვრების სვლას ნიშნავს.",
        "ქართული დამწერლობა IV-V საუკუნეებიდან თარიღდება.",
        "სიტყვა «ნათელი» სინათლეს ნიშნავს.",
        "«წმინდა ნინომ» ქრისტიანობა ქართლში IV საუკუნეში შეიტანა.",
        "სიტყვა «ნატვრა» სურვილს ნიშნავს.",
        "ქართული სუფრის ლიდერს «თამადა» ჰქვია.",
        "სიტყვა «გაზაფხული» წლის წელიწადის დროა.",
        "ქართული ენა კავკასიის მარგალიტია.",
        "სიტყვა «კეთილი იყოს თქვენი მობრძანება» სტუმრის მიღებაა.",
        "«ნახვამდის» დამშვიდობების სიტყვაა."
    ],
    'tt': [
        "Татар теле төрки телләр төркеменә керә.",
        "Татар телендә 6 өстәмә хәреф бар: Ә, Җ, Ң, Ө, Ү, Һ.",
        "Татар теле Татарстан Республикасының дәүләт теле.",
        "Татар телендә грамматик род (җенлек) юк.",
        "«Сәлам» — иң популяр дусларча исәнләшү сүзе.",
        "Габдулла Тукай — татар әдәби теленә нигез салучы.",
        "Татар телендә 6 килеш бар.",
        "«Шүрәле» — татар әдәбиятының бөек әкияте.",
        "Татар телендә иҗекләр сингармонизм законына буйсына.",
        "Чак-чак — татар халкының милли татлы ризыгы.",
        "Казан — татар мәдәниятенең меңйыллык үзәге.",
        "Татар телендә сүз басымы гадәттә соңгы иҗеккә төшә.",
        "«Ил» сүзе Ватанны һәм халыкны белдерә.",
        "«Рәхмәт» сүзе рәхмәт белдерү өчен кулланыла.",
        "Муса Җәлил — Советлар Союзы Герое, татар шагыйре.",
        "Сөембикә манарасы — Казан Кремленең архитектура символларының берсе.",
        "Татар телендә фигыльләрнең капланма хисләре бик бай.",
        "Сабантуй — татар халкының яраткан милли бәйрәме.",
        "«Дуслык» сүзе үзара ышанычны белдерә.",
        "Татар әдәбияты йөз еллык бай тарихка ия.",
        "Кул Галинең «Кыйссаи Йөсөф» дастаны XIII гасырга карый.",
        "«Тынычлык» сүзе тыныч тормышны аңлата.",
        "Татар аш-суы бәлеш, өчпочмак һәм кыстыбый белән билгеле.",
        "«Хәерле иртә!» — иртәнге сәламләү сүзе.",
        "Татар телендә җөмләдә фигыль гадәттә ахырда килә.",
        "Татар теле дөньяда 5 миллионнан артык кеше тарафыннан сөйләшелә.",
        "«Гыйлем» сүзе тирән белемне аңлата.",
        "Татар алфавиты латин, араб һәм кирилл язуларын кичергән.",
        "«Туган тел» җыры — татар халкының гимны сыман.",
        "Казан федераль университеты 1804 елда нигезләнгән.",
        "«Бәхет» сүзе шатлыклы тормышны аңлата.",
        "Татар театры 1906 елда барлыкка килгән (Г. Камал театры).",
        "«Яз» сүзе табигатьнең уяну вакытын белдерә.",
        "Татар халык моңнары озын көйләр белән аерылып тора.",
        "«Гүзәл» сүзе матурлыкны аңлата.",
        "Татар киемнәре калфак һәм түбәтәй белән бизәлә.",
        "«Шатлык» сүзе куанычны аңлата.",
        "Татар телендә саннарның кулланылышы бик гади.",
        "«Бәрәкәт» сүзе муллыкны белдерә.",
        "Татар язучылары арасында Дәрдемәнд, Һади Такташ бар.",
        "«Ихтирам» сүзе зур хөрмәтне аңлата.",
        "Татар телендә тартыш тартыклары синонимлашкан.",
        "«Мәхәббәт» сүзе ярату хисен аңлата.",
        "Идел болыгарлары 922 елда ислам динен кабул иткән.",
        "«Юл» сүзе тормыш юлын һәм сәяхәтне аңлата.",
        "Татар орнаменты үсемлек бизәкләре белән аерылып тора.",
        "«Үзән» сүзе табигать матурлыгын белдерә.",
        "«Сау булыгыз!» — саубуллашу сүзе.",
        "Татар теле — бай һәм дусларча тел.",
        "«Ихлас» сүзе эчкерсезлекне аңлата."
    ],
    'ba': [
        "Башҡорт теле төрки телдең ҡыпсаҡ төркөмөнә лә ҡарай.",
        "Башҡорт алфавитында 42 хәреф бар, шуларҙың 9-ы үҙенсәлекле (Ғ, Ҙ, Ҡ, Ң, Ө, Ү, Һ, Ә, Ҫ).",
        "Башҡорт теле Башҡортостан Республикаһында дәүләт теле.",
        "Башҡорт телендә грамматик род юҡ.",
        "«Һаумыһығыҙ!» — һаулыҡ теләү сәләме.",
        "Салауат Юлаев — башҡорт халҡының милли батыры.",
        "«Урал батыр» эпосы — боронғо ауыҙ-тел ижады ҡомартҡыһы.",
        "Башҡорт телендә 6 килеш бар.",
        "Ҡурай — башҡорт халҡының милли музыкаль ҡоралы.",
        "Башҡорт балы донъяла иң билдәле балдарҙың береһе.",
        "Өфө — Башҡортостандың меңйыллыҡ тарихлы баш ҡалаһы.",
        "Башҡорт телендә һүҙ баҫымы аҙаҡҡы ижеккә төшә.",
        "«Ил» һүҙе Ватанды һәм халыҡты белдерә.",
        "«Рәхмәт» һүҙе йылы рәхмәт белдереү өсөн ҡулланыла.",
        "Заки Валиди — башҡорт дәүләтселегенә нигеҙ һалыусы.",
        "Шүлгәнташ ташбайыҡ мәғәрәһе боронғо һүрәттәре менән билдәле.",
        "«Дутлыҡ» һүҙе берҙәмлекте белдерә.",
        "Һабантуй — эшсән халыҡтың яратҡан байрамы.",
        "Башҡорт йырҙары оҙон көй стиле менән билдәле.",
        "«Тыныслыҡ» һүҙе тыныс тормошто аңлата.",
        "Башҡорт аш-суы ҡаҙы, бишбармаҡ һәм ҡырҡылған сәк-сәк менән билдәле.",
        "«Хәйерле иртә!» — иртәнге сәләмләү һүҙе.",
        "Башҡорт телендә ҡылым җөмлә аҙағында килә.",
        "«Ғилем» һүҙе белдереүне аңлата.",
        "Мостай Кәрим — башҡорт әҙәбиәтенең классигы.",
        "«Бәхет» һүҙе шатлыҡты аңлата.",
        "Башҡорт халыҡ бейеүҙәре етеҙлеге менән айырыла.",
        "«Яҙ» һүҙе йыл миҙгелен белдерә.",
        "Башҡорт аты — сыҙамлы милли ат тоҡомо.",
        "«Гүзәл» һүҙе матурлыҡты аңлата.",
        "Башҡорт кейеме селтер һәм елән менән биҙәлә.",
        "«Шатлыҡ» һүҙе ҡуанысты белдерә.",
        "«Яҡшы» һүҙе яҡшылыҡты аңлата.",
        "Башҡорт телендә сингармонизм законы эшләй.",
        "«Ихтирам» һүҙе һөрмәтте белдерә.",
        "«Мөхәббәт» һүҙе яратыу хисен аңлата.",
        "Урал тауҙары — Башҡортостандың гүзәл тәбиғәте.",
        "«Юл» һүҙе тормош юлын аңлата.",
        "«Сау булығыҙ!» — хушлашыу һүҙе.",
        "Башҡорт теле — бай һәм батыр тел.",
        "«Ихлас» һүҙе ихласлыҡты белдерә.",
        "«Урал» һүҙе башҡорт халҡы өсөн изге.",
        "Башҡорт бейеүе «Ете ҡыҙ» бик билдәле.",
        "«Ғаилә» һүҙе иң ҙур ҡиммәтне аңлата.",
        "Башҡортостан — күп милләтле татыу республика.",
        "«Ер» һүҙе туған ерҙе белдерә.",
        "«Ҡош» һүҙе тәбиғәтте һүрәтләй.",
        "Башҡорт телендә әҙәби мираҫ бай.",
        "«Йөрәк» һүҙе һөйөүҙе белдерә.",
        "«Иҫәнлек» һүҙе һаулыҡты аңлата."
    ],
    'br': [
        "Ar brezhoneg a zo ur yezh keltiek eus brank Enez-Vreizh.",
        "Ar brezhoneg a zo an eil yezh keltiek komzet ar muiañ er bed.",
        "E brezhoneg e kaver kemmoù-kensonenn (mutationoù).",
        "Gerioù zo evel 'biz' ha 'kaer' a zo implijet er vuhez pemdez.",
        "Ar ger 'Demat' a zo ar salutadenn evit bonjour.",
        "Ar ger 'Kenavo' a zo an doare da lavarout au revoir.",
        "Breizh a zo rannet etre Breizh-Uhel ha Breizh-Izel.",
        "Ar fest-noz a zo enfrestret e glad gladel UNESCO.",
        "Diwan a zo ur rouedad skolioù brezhonek krouet e 1977.",
        "Ar gwenn-ha-du a zo banniel Breizh krouet e 1923.",
        "Ar brezhoneg a zo komzet gant war-dro 200 000 a dud.",
        "Ofis Publik ar Brezhoneg a zo karget da skoazellañ ar yezh.",
        "Ar ger 'mignoniezh' a zo gwall bouezus er vuhez.",
        "Brezhoweb a zo ar chadenn skinwel e brezhoneg.",
        "Radio Kerne ha Radio Bro Dreger a skingas e brezhoneg.",
        "Ar ger 'kig-ha-farz' a zo ur meuz hengounel eus Bro-Leon.",
        "Ar brezhoneg en deus 4 rannyezh vras (Kerne, Leon, Treger, Gwened).",
        "Ar ger 'mor' a zo gwall bresant e geriaoueg Breizh.",
        "Ar ger 'amzer' a dalv ken ar mare ken an hin.",
        "An heniarth a zo anv kozh yezhoù Keltied Breizh-Veur.",
        "Ar ger 'kalon' a dalv ar galon pe ar genfeal.",
        "Ar ger 'ti' a zo an ti ma vever ennañ.",
        "An orin eus ar brezhoneg a zo degaset eus Enez-Vreizh er Vvet kantved.",
        "Ar ger 'eost' a dalv an eostad hag miz Eost.",
        "Ar ger 'menez' a zo ur menez uhel pe brec'h.",
        "Ar brezhoneg en deus un doare-skrivañ unvan (peurunvan).",
        "Ar ger 'bara' a zo meuz diazez pep pred.",
        "Ar ger 'yec'hed' a vez lavaret evit ar yec'hed mat.",
        "Ar ger 'steredenn' a zo ur steredenn en neñv.",
        "An Erminig a zo arouez duged Breizh.",
        "Ar ger 'kan' a zo Kantu ha sonerezh hengounel.",
        "Ar ger 'goulou' a dalv ar goulou a sklêrijenn.",
        "Ar ger 'eured' a zo gouel an dimeziñ.",
        "Ar brezhoneg en deus gerioù niveriñ ugentel (20, 40, 60).",
        "Ar ger 'bro' a dalv ar vro pe ar patria.",
        "Ar ger 'dour' a zo dour glan an natur.",
        "Ar ger 'heol' a zo an heol a domma.",
        "Ar ger 'gwenn' a zo al liv gwenn glan.",
        "Ar ger 'du' a zo al liv du noz.",
        "Ar ger 'glas' a zo liv an oabl hag ar mor.",
        "Ar brezhoneg a zo ur yezh vev ha skrivet.",
        "Ar ger 'plijadur' a zo laouenidigezh krouet.",
        "Ar ger 'karantez' a dalv an amor dous.",
        "Ar ger 'peoc'h' a zo ar peoc'h sioul.",
        "Ar ger 'menez-are' a zo un aradennad menezioù e Breizh.",
        "Ar ger 'spered' a zo ar spered sklaer.",
        "Ar ger 'leun' a zo leun a spi mat.",
        "Ar ger 'gwirionez' a dalv ar gwir pur.",
        "Ar ger 'skouarn' a zo an skouarn a selaou.",
        "Ar brezhoneg a unan an dud dre ar c'hulturel."
    ]
}

def build_js_database():
    js_content = f"""/**
 * js/data/daily_dose.js
 * Daily Dose Database: 50+ Real Language & Culture Facts across all 13 languages.
 */

window.COSY_DAILY_FACTS = {json.dumps(FACTS_DB, ensure_ascii=False, indent=2)};
"""

    os.makedirs('js/data', exist_ok=True)
    with open('js/data/daily_dose.js', 'w', encoding='utf-8') as f:
        f.write(js_content)
    print("Generated js/data/daily_dose.js successfully.")

if __name__ == '__main__':
    build_js_database()
