import json, os, glob

# Build canonical mapping of Russian curriculum grammar points to topic slugs per CEFR level

LEVEL_TOPICS = {
    "A1": [
        ("alfavit-i-zvuki", "Алфавит, буквы и гласные звуки", "Alphabet, letters, and vowel sounds in Russian"),
        ("reduktsiya-glasnykh", "Редукция гласных и свободное ударение", "Vowel reduction and free stress in Russian"),
        ("tverdye-i-myagkie-soglasnye", "Твёрдые и мягкие согласные", "Hard and soft consonants in Russian"),
        ("zvonkie-i-glukhie-soglasnye", "Звонкие и глухие согласные (оглушение и оозвончение)", "Voiced and voiceless consonants"),
        ("lichnye-mestoimeniya-i-nulevaya-svyazka", "Личные местоимения и нулевая связка", "Personal pronouns and present zero copula"),
        ("konstruktsiya-menya-zovut", "Конструкция «Меня зовут...»", "Introducing yourself with 'My name is...'"),
        ("rod-imyen-sushchestvitelnykh", "Род имён существительных (мужской, женский, средний)", "Grammatical gender of nouns"),
        ("mnozhestvennoe-chislo-sushchestvitelnykh", "Множественное число существительных", "Plural formation of nouns"),
        ("prityazhatelnye-mestoimeniya", "Притяжательные местоимения (мой, твой, его, её, наш, ваш, их)", "Possessive pronouns"),
        ("ukazatelnye-mestoimeniya-etot-eta-eto-eti", "Указательные местоимения (этот, эта, это, эти)", "Demonstrative pronouns"),
        ("kolichestvennye-chislitelnye-1-100", "Количественные числительные (1–100)", "Cardinal numbers 1 to 100"),
        ("poryadkovye-chislitelnye-1-10", "Порядковые числительные (1–10)", "Ordinal numbers 1 to 10"),
        ("voprositelnye-slova-kto-chto-gde-kuda", "Вопросительные слова (Кто, Что, Где, Куда, Откуда)", "Question words"),
        ("konstruktsiya-u-menya-est", "Конструкция «У меня есть...» и её отрицание «У меня нет...»", "Expressing possession and absence"),
        ("nastoyashchee-vremya-spryazhenie-1", "Настоящее время: 1-е спряжение глаголов (-ать, -ять)", "Present tense First Conjugation verbs"),
        ("nastoyashchee-vremya-spryazhenie-2", "Настоящее время: 2-е спряжение глаголов (-ить, -еть)", "Present tense Second Conjugation verbs"),
        ("osobye-glagoly-zhit-pisat-pit", "Особые глаголы настоящего времени (жить, писать, пить, петь)", "Irregular present tense verbs"),
        ("glagoly-moch-i-umet", "Модальные глаголы «мочь» и «уметь»", "Modal verbs for ability"),
        ("glagol-khotet", "Особый глагол «хотеть» и конструкция «я хотел бы»", "Expressing desire with хотеть and хотел бы"),
        ("predlozhnyy-padezh-mesto", "Предложный падеж: местоположение (где? в/на)", "Prepositional case for location"),
        ("predlozhnyy-padezh-o-kom-o-chem", "Предложный падеж: объект мысли и речи (о ком? о чём?)", "Prepositional case for topic of speech/thought"),
        ("vinitelnyy-padezh-neodushevlennye", "Винительный падеж: неодушевлённые существительные (что?)", "Accusative case for inanimate objects"),
        ("vinitelnyy-padezh-odushevlennye", "Винительный падеж: одушевлённые существительные (кого?)", "Accusative case for animate objects"),
        ("vinitelnyy-padezh-napravlenie", "Винительный падеж направления (куда? в/на)", "Accusative case for direction and motion"),
        ("roditelnyy-padezh-prinadlezhnost", "Родительный падеж: принадлежность и отсутствие (кого? чего? нет...)", "Genitive case for possession and absence"),
        ("roditelnyy-padezh-chislitelnye", "Согласование существительных с числительными (1, 2-4, 5-20)", "Nouns with numerals in Genitive case"),
        ("datelnyy-padezh-vozrast-i-adresat", "Дательный падеж: возраст (мне... лет) и адресат (кому?)", "Dative case for age and indirect object"),
        ("tvoritelnyy-padezh-sovmestnost", "Творительный падеж: совместность действий (с кем? с чем?)", "Instrumental case with prepositions 'с'"),
        ("tvoritelnyy-padezh-professii", "Творительный падеж: профессии и интересы (быть/работать/заниматься)", "Instrumental case for professions and hobbies"),
        ("glagoly-dvizheniya-idti-ekhat", "Глаголы движения без приставок: «идти» vs «ехать»", "Unprefixed verbs of motion: walking vs vehicle"),
        ("glagoly-dvizheniya-khodit-ezdit", "Глаголы движения: многонаправленные «ходить» и «ездить»", "Multidirectional verbs of motion"),
        ("proshedshee-vremya-glagolov", "Прошедшее время глаголов: образование и согласование в роде", "Past tense formation and gender agreement"),
        ("proshedshee-vremya-glagola-byt", "Прошедшее время глагола «быть» (был, была, было, были)", "Past tense of 'to be'"),
        ("budushchee-vremya-slozhashchee", "Сложное будущее время (буду + инфинитив)", "Compound future tense"),
        ("povelitelnoe-naklonenie-imperativ", "Повелительное наклонение (Императив: читай! читайте!)", "Imperative mood"),
        ("soglasovanie-prilagatelnykh", "Согласование прилагательных в роде и числе", "Adjective agreement in gender and number"),
        ("poryadok-slov-v-predlozhenii", "Порядок слов в русском предложении и логическое ударение", "Word order and logical emphasis"),
        ("narechiya-chastoty", "Наречия частоты (всегда, обычно, иногда, никогда не)", "Adverbs of frequency"),
        ("narechiya-mesta-i-napravleniya", "Наречия места и направления (здесь/сюда, там/туда, дома/домой)", "Adverbs of place vs direction"),
        ("narechiya-obraza-deystviya", "Наречия образа действия на -о (хорошо, быстро, медленно)", "Adverbs of manner ending in -o"),
        ("soyuzy-i-a-no", "Соединительные и противительные союз (и, а, но)", "Conjunctions и, а, но"),
        ("soyuzy-prichiny-potomu-chto-tak-kak", "Союзы причины: «потому что» и «так как»", "Causal conjunctions because / as"),
        ("soyuzy-tseli-chtoby", "Союз цели «чтобы» + инфинитив", "Purpose conjunction щоб / ताकि / in order to"),
        ("vremya-i-chasy", "Обозначение времени и часов (Который час? Во сколько?)", "Telling the time and schedule"),
        ("dni-nedeli-i-mesyatsy", "Дни недели, месяца и времена года с предлогами", "Days of the week, months, and seasons"),
        ("konstruktsii-mozhno-nelzya-nuzhno", "Безличные конструкции: «можно», «нельзя», «нужно / надо»", "Impersonal expressions for permission, prohibition, necessity"),
        ("konstruktsiya-nravitsya-lyubit", "Различие конструкций «любить» и «нравиться»", "Difference between любить and нравиться"),
        ("konstruktsii-skuchno-veselo-interesno", "Предикативные наречия состояния (мне скучно, интересно, жарко)", "State predicates with Dative case"),
        ("vezhlivye-prosby-i-poveleniya", "Формулы вежливости и просьбы (Скажите, пожалуйста / Будьте добры)", "Polite requests and social formulas"),
        ("sravnitelnaya-stepen-bolee-i-sufiks-ee", "Сравнительная степень прилагательных (более... / -ее)", "Comparative adjectives"),
        ("prevoskhodnaya-stepen-samyy", "Превосходная степень прилагательных (самый + прилагательное)", "Superlative adjectives with самый"),
        ("otNegative-mestoimeniya-nikto-nishto", "Отрицательные местоимения и наречия (никто, ничто, никогда)", "Negative pronouns and double negation"),
        ("vvodnye-slova-kazhetsya-po-moemu", "Вводные слова мнения (по-моему, кажется, конечно)", "Introductory words expressing opinion")
    ],
    "A2": [
        ("proshedshee-vremya-osobennosti", "Прошедшее время: особенные глаголы и беглые гласные", "Irregular past tense forms"),
        ("vidy-glagola-osnovy-nsv-sv", "Виды глагола: значение НСВ (процесс, повтор) и СВ (результат, факт)", "Aspects of the verb: Imperfective vs Perfective"),
        ("vidovye-pary-glagolov", "Образование видов: суффиксы и приставки видов пар", "Aspectual verb pairs formation"),
        ("vidy-glagola-v-proshedshem-vremeni", "Употребление видов глагола в прошедшем времени", "Aspects in the past tense"),
        ("vidy-glagola-v-budushchem-vremeni", "Будущее время: НСВ (буду делать) vs СВ (сделаю)", "Aspects in the future tense"),
        ("vidy-glagola-v-povelitelnom-naklonenii", "Виды глагола в повелительном наклонении (делай! / сделай!)", "Aspects in the imperative mood"),
        ("vinityelnyy-padezh-prilagatelnykh-i-mestoimeniy", "Винительный падеж прилагательных и притяжательных местоимений", "Accusative case of adjectives and pronouns"),
        ("roditelnyy-padezh-prilagatelnykh-i-mestoimeniy", "Родительный падеж прилагательных и местоимений", "Genitive case of adjectives and pronouns"),
        ("roditelnyy-padezh-mnozhestvennogo-chisla", "Родительный падеж множественного числа существительных", "Genitive plural of nouns"),
        ("roditelnyy-padezh-predlogi-iz-ot-do-dlya-bez", "Предлоги родительного падежа (из, от, до, для, без, около, после)", "Genitive prepositions"),
        ("datelnyy-padezh-prilagatelnykh-i-mestoimeniy", "Дательный падеж прилагательных и местоимений", "Dative case of adjectives and pronouns"),
        ("datelnyy-padezh-predlogi-k-i-po", "Предлоги дательного падежа «к» и «по»", "Dative prepositions к and по"),
        ("datelnyy-padezh-bezlichnye-predlozheniya", "Безличные предложения с дательным падежом (мне холодно, ей надо)", "Impersonal Dative constructions"),
        ("tvoritelnyy-padezh-prilagatelnykh-i-mestoimeniy", "Творительный падеж прилагательных и местоимений", "Instrumental case of adjectives and pronouns"),
        ("tvoritelnyy-padezh-predlogi-za-pod-nad-peryed", "Пространственные предлоги творительного падежа (за, под, над, перед, между)", "Instrumental spatial prepositions"),
        ("predlozhnyy-padezh-prilagatelnykh-i-mestoimeniy", "Предложный падеж прилагательных и местоимений", "Prepositional case of adjectives and pronouns"),
        ("predlozhnyy-padezh-vtoroy-predlozhnyy-na-u", "Второй предложный падеж на -у/-ю (в лесу, на мосту, в аэропорту)", "Second Prepositional locative ending -u/-yu"),
        ("vse-padezhi-mnozhestvennoe-chislo-obzor", "Падежные окончания множественного числа (полный обзор)", "Plural case declension review"),
        ("glagoly-dvizheniya-s-pristavkami-po-pri-u", "Глаголы движения с приставками по-, при-, у- (пойти, приехать, уйти)", "Prefixed motion verbs po-, pri-, u-"),
        ("glagoly-dvizheniya-s-pristavkami-v-vy-dop-pere", "Глаголы движения с приставками в-, вы-, до-, пере-, под-, от-", "Motion verbs with directional prefixes"),
        ("vozvratnye-glagoly-na-sya", "Возвратные глаголы на -ся/-сь (умываться, встречаться, нравиться)", "Reflexive verbs ending in -sya/-sy"),
        ("vremenni-soyuzy-kogda-poka-posle-togo-kak", "Временные союзы (когда, пока, после того как, перед тем как)", "Time conjunctions"),
        ("uslovnye-predlozheniya-esli-esli-by", "Условные предложения: реальное «если» и нереальное «если бы»", "Real and counterfactual conditionals"),
        ("ustupitelnye-soyuzy-khotya-nesmotrya-na", "Уступительные конструкции («хотя», «несмотря на то что»)", "Concessive clauses"),
        ("mestoimenie-kotoryy", "Определительное местоимение «который» и его склонение", "Relative pronoun который across cases"),
        ("mestoimeniya-kto-to-chto-to-kto-nibud", "Неопределённые местоимения с -то и -нибудь", "Indefinite pronouns with -то and -нибудь"),
        ("kratkie-prilagatelnye", "Краткие прилагательные (рад, должен, занят, достоин)", "Short-form adjectives"),
        ("kratkie-prichastiya-vvedenie", "Краткие страдательные причастия в простом контексте (открыт, закрыт)", "Short passive participles"),
        ("chislitelnye-sostavnye-i-drobi", "Составные количественные и порядковые числительные", "Compound cardinal and ordinal numbers"),
        ("soglasovanie-chislitelnykh-s-prilagatelnymi", "Согласование числительных 2, 3, 4 с прилагательными", "Noun and adjective agreement with numerals 2, 3, 4"),
        ("soyuzy-prichiny-i-sledstviya-poetomu-tak-kak", "Причинно-следственные связи: «поэтому», «так как», «из-за»", "Cause and effect connectors"),
        ("kosvennaya-rech-vvedenie", "Перевод прямой речи в косвенную (он сказал, что... / спросил, ли...)", "Reported speech basics"),
        ("glagolnye-konstruktsii-soit-zanimatsya", "Глагольные конструкции предпочтения и интересов (увлекаться, заниматься)", "Verbal constructions of hobbies and interests"),
        ("sravnenie-s-soyuzom-chem-i-roditelnym-padezhem", "Конструкции сравнения с союзом «чем» и без него", "Comparative structures with чем and Genitive"),
        ("prevochodnaya-stepen-naibolee-samyy", "Способы выражения превосходной степени (наиболее, наименее)", "Advanced superlative structures"),
        ("povelitelnoe-naklonenie-pust-pust-davaite", "Побудительные конструкции («Давай!», «Пусть...», «Давайте...»)", "Exhortative constructions with let us / let them"),
        ("substantivirovannye-prilagatelnye", "Субстантивированные прилагательные (столовая, ванная, больной)", "Substantivized adjectives"),
        ("mestoimeniya-ves-kazhdyy-lyuboy-sam", "Определительные местоимения (весь, каждый, любой, сам)", "Definite pronouns весь, каждый, любой, сам"),
        ("ot отрицательные-mestoimeniya-s-predlogami", "Отрицательные местоимения с предлогами (ни с кем, ни о чём)", "Negative pronouns split by prepositions"),
        ("bezlichnye-glagoly-mne-ne-seditsya", "Безличные глаголы состояния и ощущения (мне не сидится, темнеет)", "Impersonal state verbs"),
        ("vyrazhenie-doba-i-chasa-vremeni", "Точное выражение времени, дат и лет (в двух тысяча двадцать четвёртом году)", "Expressing exact years, dates and time"),
        ("poryadok-slov-tema-rema-a2", "Актуальное членение предложения: Тема и Рема", "Topic-comment word order in Russian"),
        ("vvodnye-slova-i-frazy-a2", "Вводные слова для структурирования речи (во-первых, во-вторых)", "Discourse markers for structuring talk"),
        ("konstruktsii-dolzhen-obyazan-nado", "Выражение должествования: «должен», «обязан», «приходится»", "Modal obligation variants"),
        ("glagoly-chuvstv-i-vospriyatiya", "Глаголы чувств и восприятия (слышать/увидеть, казаться)", "Verbs of perception and feeling"),
        ("povelitelnaya-mnojestvennaya-forma", "Совместное действие и вежливый императив", "Joint action and polite imperatives")
    ],
    "B1": [
        ("vidy-glagola-v-infinitive", "Виды глагола при инфинитиве (надо сделать / не надо делать)", "Aspect choice in infinitive constructions"),
        ("vidy-glagola-повторяющиеся-действия", "Виды глагола при выражении повторяющихся и однократных действий", "Aspects in repeated vs single actions"),
        ("glagoly-dvizheniya-s-pristavkami-obzor", "Система приставочных глаголов движения (пере-, про-, об-, за-)", "System of prefixed motion verbs"),
        ("glagoly-dvizheniya-perezatno-perenostnoe-znachenie", "Переносные значения глаголов движения (время идёт, речь идёт)", "Metaphorical meanings of motion verbs"),
        ("deeprichastie-nesovershennogo-vida", "Деепричастия несовершенного вида (-ая/-яя, -учи/-ючи)", "Imperfective verbal adverbs / gerunds"),
        ("deeprichastie-sovershennogo-vida", "Деепричастия совершенного вида (-в/-вши, -ши)", "Perfective verbal adverbs / gerunds"),
        ("deeprichastnyy-oborot-i-ego-normy", "Деепричастный оборот и правила его употребления", "Verbal adverbial clauses and syntax rules"),
        ("действительные-prichastiya-nastoyashchego-i-proshedshego", "Действительные причастия настоящего и прошедшего времени", "Active participles (present and past)"),
        ("stradatelnye-prichastiya-nastoyashchego-i-proshedshego", "Страдательные причастия настоящего и прошедшего времени", "Passive participles (present and past)"),
        ("prichastnyy-oborot-i-punktuatsiya", "Причастный оборот, его согласование и пунктуация", "Participle clauses and punctuation"),
        ("kratkie-stradatelnye-prichastiya", "Краткие страдательные причастия и пассивный залог", "Short passive participles and passive voice"),
        ("passivnyy-zalog-tvoritnyy-subyekt", "Пассивные конструкции с творительным падежом субъекта", "Passive constructions with Instrumental subject"),
        ("mestoimennie-sebya-i-svoy", "Возвратно-притяжательное местоимение «свой» и местоимение «себя»", "Reflexive possessive 'свой' vs 'себя'"),
        ("vzaimnye-mestoimeniya-drug-druga", "Взаимно-возвратное местоимение «друг друга» во всех падежах", "Reciprocal pronoun 'друг друга' across cases"),
        ("otnositeilnye-mestoimeniya-chey-kakoy-kakov", "Относительные местоимения «чей», «какой», «каков»", "Relative pronouns чей, какой, каков"),
        ("chislitelnye-sklonenie-kolichestvennykh", "Склонение простых и составных количественных числительных", "Declension of cardinal numbers"),
        ("chislitelnye-sklonenie-poryadkovykh", "Склонение порядковых числительных и дат", "Declension of ordinal numbers and dates"),
        ("sobiratelnye-chislitelnye-dvoe-troe", "Собирательные числительные (двое, трое, четверо) и их синтаксис", "Collective numerals двое, трое, четверо"),
        ("drobnye-i-drobno-kolichestvennye-chislitelnye", "Дробные и смешанные числительные (полтора, полтораста)", "Fractional numerals and полтора"),
        ("bezlichnye-predlozheniya-s-kratkimi-stradatelynymi", "Безличные предложения («сказано», «написано», «принято»)", "Impersonal structures with short participles"),
        ("soyuzy-prichiny-blagodarya-iz-za-vvidu", "Причинные союзы и предлоги (благодаря, из-за, ввиду, в связи с)", "Causal prepositions and conjunctions"),
        ("soyuzy-ustupki-nesmotrya-na-vopreki", "Уступительные конструкции (несмотря на, вопреки, хотя)", "Concessive constructions"),
        ("soyuzy-usloviya-pri-uslovii-esli-by", "Сложные условные союзы (при условии если, в случае если)", "Complex conditional conjunctions"),
        ("soyuzy-tseli-dlya-togo-chtoby", "Союзы цели (для того чтобы, с тем чтобы)", "Purpose conjunctions для того чтобы"),
        ("kosvennaya-rech-izmenenie-mestoimeniy-i-glagolov", "Трансформация прямой речи в косвенную: союзы что, чтобы, ли", "Complex reported speech rules"),
        ("kosvennyy-vopros-chastitsa-li", "Косвенный вопрос с частицей «ли»", "Indirect questions with particle 'ли'"),
        ("vvodnye-slova-stepen-dostovernosti", "Вводные слова степени достоверности (безусловно, вероятно, едва ли)", "Epistemic modal markers"),
        ("vvodnye-slova-poryadok-mysley", "Вводные слова структуры текста (следовательно, таким образом)", "Discourse connectors and text structure"),
        ("roditelnyy-padezh-chasti-s-predlogom-iz-za", "Родительный падеж части целого (чашка чаю, килограмм сахара)", "Partitive Genitive (-u/-yu)"),
        ("datelnyy-padezh-subyekta-otsenki", "Дательный падеж субъекта оценки (мне кажется, ему видится)", "Dative subject of evaluation"),
        ("tvoritelnyy-padezh-vremeni-i-mesta", "Творительный падеж времени и пространства (утром, дорогой, зимой)", "Instrumental of time and path"),
        ("predlogi-mesta-iz-pod-iz-za", "Составные предлоги места (из-под, из-за)", "Compound spatial prepositions"),
        ("otnegalnye-mestoimeniya-nekovo-nechego", "Отрицательные местоимения «некого», «нечего» и их синтаксис", "Negative pronouns некого, нечего"),
        ("slozhnosochinennye-predlozheniya-tozhe-takzhe", "Сложносочинённые предложения с союзами «тоже», «также», «зато»", "Coordinate clauses with тоже, также, зато"),
        ("sloznopodchinennye-izyasnitelnye-s-soyuzom-chto-chtoby", "Сложноподчинённые изъяснительные предложения", "Complex noun clauses with что and чтобы"),
        ("otglagolnye-sushchestvitelnye-vvedenie", "Отглагольные существительные на -ние/-тие и их синтаксис", "Verbal nouns ending in -ние/-тие"),
        ("sravnitelnye-oboroty-kak-budto-slovno", "Сравнительные обороты с союзами «как будто», «словно», «точно»", "Comparative clauses with как будто, словно"),
        ("frazeologizmy-i-ustoychivye-sochetaniya-b1", "Устойчивые глагольно-именные сочетания (принимать решение, иметь значение)", "Verb-noun collocations"),
        ("glagolnyy-upravlenie-predlogi-v-na-o-k", "Глагольное управление: сложные предложные связи", "Verb government and prepositional regimes"),
        ("substantivatsiya-i-perekhod-chastey-rechi", "Субстантивация и переход частей речи в русский синтаксис", "Substantivization in syntax"),
        ("poryadok-slov-emfatiko-b1", "Эмфатический порядок слов и вынос инверсии", "Emphatic word order and inversion"),
        ("povelitelnoe-naklonenie-vezhlivaya-prosba", "Формы косвенного побуждения и вежливые модальные обороты", "Indirect requests and polite modals"),
        ("glagoly-myshleniya-i-rechi", "Глаголы речи и мысли в научном и деловом стиле", "Verbs of speech and cognition"),
        ("slozhnosokrashchennye-slova-i-abbreviatury", "Сложносокращённые слова, аббревиатуры и их род", "Acronyms, abbreviations and their gender"),
        ("poyasnitelnye-konstruktsii-to-est-a-imenno", "Пояснительные конструкции (то есть, а именно, другими словами)", "Explanatory markers то есть, а именно"),
        ("chastitsy-zhe-ved-daje-li", "Усилительные частицы (же, ведь, даже, -то)", "Emphatic particles же, ведь, даже"),
        ("sinonimiya-sintaksicheskikh-konstruktsiy", "Синтаксическая синонимия причастных и придаточных предложений", "Syntactic synonymy: participle clauses vs relative clauses")
    ],
    "B2": [
        ("slozhnyy-sintaksis-prichastiy-i-deeprichastiy", "Причастные и деепричастные обороты в аналитических текстах", "Complex participle and gerund clauses"),
        ("poryadok-slov-сmyslovoy-tsentr", "Смысловой центр предложения и инверсия подлежащего/сказуемого", "Information structure, theme-rheme, focus inversion"),
        ("substantivatsiya-szhatie-informatsii", "Номинализация (сжатие информации отглагольными существительными)", "Nominalization and information compression"),
        ("slozhnye-uslovnye-konstruktsii-s-by", "Сложные гипотетические условия с частицей «бы» (если бы... то бы...)", "Complex hypothetical conditionals"),
        ("vvodnye-slova-kategorii-dostovernosti", "Градации уверенности и категории эвфемизмов в публичной речи", "Gradations of certainty and hedging devices"),
        ("konstruktsii-distantsirovaniya", "Конструкции дистанцирования («бытует мнение», «утверждается, что»)", "Distancing passives and reporting structures"),
        ("kosvennaya-rech-ritoricheskie-priemy", "Косвенная речь в официальном стиле и цитирование", "Reported speech in formal discourse"),
        ("sinonimiya-soyuznykh-i-bessoyuznykh-svyazey", "Бессоюзные сложные предложения (двоеточие и тире)", "Asyndetic complex sentences with colon and dash"),
        ("soyuzy-protivopostavleniya-mezhdu-tem-kak", "Союзы противопоставления и сопоставления (между тем как, в то время как)", "Adversive conjunctions"),
        ("soyuzy-ustupki-kak-by-ni-skolko-by-ni", "Уступительные конструкции с частицей «ни» (как бы ни, сколько бы ни)", "Concessive clauses with 'ни'"),
        ("bezlichnye-i-neopredelenno-lichnye-predlozheniya-b2", "Неопределённо-личные и безличные конструкции в аналитическом стиле", "Impersonal and indefinite-personal constructions"),
        ("frazeologiya-ofitsialno-delovogo-stilya", "Официально-деловой синтаксис и канцеляризмы", "Formal business discourse syntax"),
        ("poyasnitelnye-i-vstavnye-konstruktsii", "Вставные предложения и грамматические паузы", "Parenthetical and inserted clauses"),
        ("morfologicheskaya-stilistika-glagola", "Стилистические варианты глагольных форм (инфинитив, наклонения)", "Stylistic variations of verb forms"),
        ("morfologicheskaya-stilistika-sushchestvitelnyh", "Стилистические варианты падежных окончаний существительных", "Stylistic variations of noun endings"),
        ("morfologicheskaya-stilistika-prilagatelnyh", "Полные и краткие формы прилагательных в книжной речи", "Full vs short adjectives in academic register"),
        ("poryadkovye-i-kolichestvennye-chislitelnye-v-delovoy-rechi", "Синтаксис числительных в юриспруденции и экономике", "Numerals in legal and economic syntax"),
        ("glagolnoe-upravlenie-divergentsiya", "Вариативность глагольного управления и синонимия предлогов", "Variations in verb government"),
        ("subyektno-obyektnye-otnosheniya-v-slozhnom-predlozhenii", "Субъектно-объектные отношения в многосоставном предложении", "Subject-object relationships in complex clauses"),
        ("stilisticheskaya-inversiya-i-ritm-frazy", "Риторическая инверсия и ритмическая организация текста", "Rhetorical inversion and phrase rhythm"),
        ("substantivnye-konstruktsii-s-roditelnym-padezhem", "Цепочки родительного падежа (род.п. низания)", "Genitive chains nominal structures"),
        ("modalnye-slova-i-glagoly-dovoda", "Модальные обороты аргументации (следует признать, невозможно отрицать)", "Argumentative modal expressions"),
        ("chastitsy-obosobleniya-i-vydeleniya", "Выделительно-ограничительные частицы (именно, лишь, исключительно)", "Focusing and restrictive particles"),
        ("intonatsionnye-konstruktsii-ik-1-ik-5", "Интонационные конструкции русского языка (ИК-1 – ИК-5)", "Intonational contours IK-1 to IK-5"),
        ("lexicheskaya-i-sintaksicheskaya-izbytochnost", "Плеоназм, тавтология и нормы синтаксической полноты", "Syntactic economy vs pleonasm"),
        ("sintaksicheskaya-svyaznost-abzatsa", "Средства межфразовой и межабзацной связности", "Cohesion devices between paragraphs"),
        ("metaforicheskiy-перенос-в-грамматике", "Грамматиказиция метафор и фразеологизированные схемы", "Grammaticalized metaphors"),
        ("deeprichastiya-ot-glagolov-dvizheniya", "Деепричастия приставочных глаголов движения", "Gerunds of prefixed motion verbs"),
        ("predlogi-otglagolnogo-proiskhozhdeniya", "Отглагольные предлоги (включая, спустя, благодаря, исходя из)", "Prepositions of verbal origin"),
        ("predlogi-otimennogo-proiskhozhdeniya", "Отыменные предлоги (в течение, в продолжение, ввиду, вплоть до)", "Prepositions of nominal origin"),
        ("vyrazhenie-vremennoy-soshedshosti", "Синхронность и последовательность событий в сложном синтаксисе", "Temporal simultaneity and sequence"),
        ("sintaksis-sravnitelynykh-stipeney", "Синтаксические конструкции с градацией и параллельным изменением", "Proportional comparative clauses (чем... тем...)"),
        ("sintaksis-diplomaticheskoy-peregovornoy-rechi", "Дипломатический синтаксис: эвфемизмы и косвенное выражение", "Diplomatic and negotiation syntax"),
        ("otsenochnyy-sintaksis-i-ekspressivnyy-poryadok", "Экспрессивные синтаксические конструкции публицистики", "Expressive syntax in rhetoric"),
        ("sintaksis-nauchnogo-doklada", "Синтаксические нормы академической презентации и дискуссии", "Academic presentation syntax"),
        ("itogovaya-sintaksicheskaya-norma-b2", "Нормы согласования и распространенные ошибки синтаксиса B2", "Comprehensive B2 syntactic accuracy rules")
    ],
    "C1": [
        ("akademicheskoe-smyagchenie-hedging", "Конструкции академического смягчения утверждений (hedging)", "Academic hedging and stance devices"),
        ("tema-rema-i-informatsionnaya-upakovka", "Организация информации Тема-Рема и выделительные конструкции", "Theme-Rheme and information packaging"),
        ("modalnost-i-veroyatnost-v-nauchnykh-gipotezakh", "Модальность вероятности и гипотетичности в исследовании", "Modality for scientific hypotheses"),
        ("emfaticheskaya-inversiya-i-poryadok-slov", "Эмфатическая инверсия (Не только..., но и... / Едва ли...)", "Emphatic inversion and negative adverbials"),
        ("slozhno-soslagatelnyy-sintaksis-diplomatii", "Сослагательное наклонение в официальных актах и нотах", "Subjunctive in statutory and diplomatic acts"),
        ("otrushenie-subyekta-i-passivnyy-distantsirovannyi-sintaksis", "Пассивные и неопределённо-личные структуры дистанцирования", "Distancing passives and impersonal structures"),
        ("vydelitelnye-cleft-konstruktsii", "Выделительные конструкции («Что нас действительно волнует, так это...»)", "Russian cleft-like focus constructions"),
        ("inversiya-usloviya-v-ofitsialnoy-diskussii", "Инверсия условий в официальной речи («Будь у нас X, мы бы...»)", "Inverted conditionals in negotiation"),
        ("ellipsis-i-lexicheskaya-zamena", "Связность, эллипсис и лексическая замена в научном монологе", "Ellipsis and lexical substitution"),
        ("otglagolnye-sushchestvitelnye-v-ritme-publitsistiki", "Конденсированная номинализация и ритм литературного обзора", "Nominalization in essayistic prose"),
        ("vvodnye-konstruktsii-avtorskogo-kommentariya", "Вводные конструкции авторского комментария и рефлексии", "Authorial reflection markers"),
        ("slozhnye-poyasnitelnye-pridatochnye", "Сложные пояснительные придаточные с союзами «насколько», «постольку»", "Explanatory clauses with насколько/постольку"),
        ("modalnost-uverennosti-i-filosofskogo-poiska", "Модальность эпистемического поиска и каденция размышления", "Epistemic stance in essay writing"),
        ("knizhnye-soyuzy-i-stilisticheskie-svyazki", "Книжные союзы (невероятно, но..., коль скоро, постольку поскольку)", "High-register literary conjunctions"),
        ("sbalansirovannye-trekhchlennye-konstruktsii-trikolon", "Параллелизм и триколон (Правило трёх элементов в риторике)", "Rhetorical tricolons and parallelism"),
        ("perekluchenie-registrov-i-stilisticheskaya-gibkost", "Морфосинтаксические правила переключения регистров", "Code-switching and register shifts"),
        ("zarechnye-modifikatory-registra", "Наречные модификаторы регистра и лексико-синтаксический тон", "Register modifying adverbials"),
        ("kosvennaya-vezhlivost-i-evfemizmy", "Косвенная вежливость, эвфемизмы и дипломатический протокол", "Indirect politeness and euphemisms"),
        ("akusticheskaya-adaptivnost-i-govor", "Фонетико-синтаксические особенности публичной монологической речи", "Prosodic-syntactic adaptations"),
        ("spontannaya-sintaksicheskaya-svyaznost", "Спонтанная синтаксическая связность экспромтного монолога", "Spontaneous monologue cohesion"),
        ("prichastnye-konstruktsii-v-ekspromte", "Причастные конструкции в устных ответах под давлением", "Participle clauses in oral defense"),
        ("modalnye-glagoly-zanizheniya-riskov", "Модальные глаголы заверения и минимизации рисков", "Risk minimization modal verbs"),
        ("ritm-periodicheskogo-predlozheniya", "Ритм периодического предложения в ораторской речи", "Periodic sentence rhythm in oratory"),
        ("razvernutaya-metafora-v-sintaksise", "Развёрнутая метафора и её синтаксическое развёртывание", "Extended metaphor syntax"),
        ("priemy-ustnogo-ukhoda-ot-provokatsiy", "Приёмы устного ухода от провокаций («Хотя X, суть в Y»)", "Evasion syntax in media interviews"),
        ("inversionnye-ustupki-v-spore", "Инверсионные уступки в публичных дебатах", "Inverted concessions in debates"),
        ("sintez-akademichskogo-i-ritoricheskogo-sintaksisa", "Синтез риторических, академических и экспромтных синтаксических структур C1", "Comprehensive C1 syntactic mastery"),
        ("poyasnitelnye-vstavki-v-retsezii", "Пояснительные вставки и стилистические паузы в критика", "Explanatory parentheticals in critique")
    ],
    "C2": [
        ("stilisticheskaya-inversiya-hudozhestvennoy-prozy", "Стилистическая инверсия подлежащего и сказуемого в прозе", "Stylistic inversion in literary prose"),
        ("parallelizm-hiasm-i-ritm-mnogosostavnogo-predlozheniya", "Параллелизм, хиазм и ритмика многосоставного периода", "Parallelism, chiasmus, and period cadence"),
        ("morfosintaksicheskie-varianty-vysshego-registra", "Морфосинтаксические варианты высшего книжного регистра", "High-register morphosyntactic variants"),
        ("smyslovye-sdvigi-poryadka-slov", "Смысловые сдвиги порядка слов и тончайшие акценты", "Word order semantic nuance and emphasis"),
        ("epistemicheskaya-modalnost-filosofskogo-diskursa", "Эпистемическая модальность философского дискурса", "Epistemic modality in philosophical prose"),
        ("litota-dvoynoe-otritsanie-i-knizhnye-soyuzy", "Литота, двойное отрицание и книжные союзы", "Litotes, double negation, and archaic conjunctions"),
        ("sintaksis-ofitsialno-delovogo-i-yuridicheskogo-stilya", "Синтаксис официально-делового и юридического стиля", "Statutory, legal, and administrative syntax"),
        ("slozhnye-gipoteticheskie-sintaksicheskie-seti", "Сложные гипотетические синтаксические сети", "Multi-tiered hypothetical syntactic networks"),
        ("transformatsiya-stilisticheskikh-registrov", "Мгновенная трансформация стилистических регистров", "Fluid register shifting from formal to oral"),
        ("tochnyy-kontrol-sfery-deystviya-chastits", "Точный контроль сферы действия с помощью частиц (именно, едва ли)", "Focus scope control with particles"),
        ("inversiya-soslagatelnogo-nakloneniya-v-makroekonomike", "Инверсия сослагательного наклонения в моделировании", "Subjunctive inversion in economic modeling"),
        ("extrapozitsiya-pridatochnykh-izyasnitelnykh", "Экстрапозиция придаточных изъяснительных и относных", "Extraposition of noun clauses"),
        ("plotnaya-administrativno-pravovaya-nominalizatsiya", "Плотная административно-правовая номинализация", "Dense administrative nominalization"),
        ("deonticheskaya-modalnost-ustavnykh-dokumentov", "Деонтическая модальность уставных документов", "Deontic modality in statutory drafting"),
        ("sintaksis-takticheskogo-rychaga-v-peregovorakh", "Синтаксис тактического рычага давления и деэскалации", "Tactical leverage and de-escalation syntax"),
        ("prosodicheskie-intonatsionnye-konstruktsii-ik-6-ik-7", "Интонационные конструкции ИК-6, ИК-7 и подтекст", "Prosodic IK-6 and IK-7 intonation contours"),
        ("subversivnaya-inversiya-i-ironicheskiy-freming", "Субверсивная инверсия и ироническое фреймирование", "Subversive inversion and ironic framing"),
        ("sintaksis-sokraticheskogo-dialoga-i-dekonstruktsii", "Синтаксис сократического диалога и деконструкции", "Socratic dialogue and conceptual deconstruction"),
        ("literaturnye-allyuzii-i-podtekstovaya-podrazumevaemost", "Литературные аллюзии и подтекстовая подразумеваемость", "Literary allusions and implicit subtext"),
        ("absolutnyy-c2-sintez-vsekh-sintaksicheskikh-struktur", "Абсолютный C2 синтез всех устных и письменных синтаксических структур", "Mastery of all C2 syntactic structures")
    ]
}

os.makedirs('data', exist_ok=True)

with open('data/ru_grammar_topics_map.json', 'w', encoding='utf-8') as f:
    json.dump(LEVEL_TOPICS, f, ensure_ascii=False, indent=2)

print("Saved data/ru_grammar_topics_map.json successfully!")
for lvl, top_list in LEVEL_TOPICS.items():
    print(f"Level {lvl}: {len(top_list)} topics")
