# Authentic C1 Word Dictionary
# Contains vocabulary words with (word, pos, domain, subcategory, sub_subcategory, ipa, emoji, subtext, definition, example, synonyms, antonyms)

C1_DICTIONARY = [
    # LAW Nouns
    ("adjudication", "noun", "LAW", "Legal_System", "Judicial_Process", "əˌdʒuːdɪˈkeɪʃn", "⚖️", "formal adjudication / binding adjudication", "Formal judgment or decision in a legal or official matter.", "The adjudication of complex corporate disputes requires specialized legal expertise.", ["judgment", "arbitration"], ["indecision"]),
    ("indictment", "noun", "LAW", "Legal_System", "Judicial_Process", "ɪnˈdaɪtmənt", "🏛️", "criminal indictment / formal indictment", "A formal charge or accusation of a serious crime.", "The grand jury handed down a multi-count indictment against the executive.", ["accusation", "charge"], ["acquittal"]),
    ("subpoena", "noun", "LAW", "Legal_System", "Judicial_Process", "səˈpiːnə", "📑", "issue a subpoena / comply with subpoena", "A writ ordering a person to attend a court.", "The defense attorney issued a subpoena for the financial records.", ["writ", "summons"], []),
    ("affidavit", "noun", "LAW", "Legal_System", "Judicial_Process", "ˌæfəˈdeɪvɪt", "✍️", "sworn affidavit / submit affidavit", "A written statement confirmed by oath or affirmation.", "The witness submitted a sworn affidavit testifying to the events.", ["declaration", "testimony"], []),
    ("plaintiff", "noun", "LAW", "Legal_System", "Judicial_Process", "ˈpleɪntɪf", "🧑‍⚖️", "lead plaintiff / plaintiff's attorney", "A person who brings a case against another in a court of law.", "The plaintiff sought monetary damages for breach of contract.", ["complainant", "litigant"], ["defendant"]),
    ("litigation", "noun", "LAW", "Legal_System", "Judicial_Process", "ˌlɪtɪˈɡeɪʃn", "💼", "civil litigation / pending litigation", "The process of taking legal action.", "Commercial litigation can prove prohibitively expensive for small businesses.", ["lawsuit", "proceedings"], ["settlement"]),
    ("injunction", "noun", "LAW", "Legal_System", "Judicial_Process", "ɪnˈdʒʌŋkʃn", "🛑", "court injunction / seek injunction", "A judicial order restraining a person from beginning or continuing an action.", "The judge granted a preliminary injunction preventing publication.", ["prohibition", "restraining order"], []),
    ("arbitration", "noun", "LAW", "Legal_System", "Judicial_Process", "ˌɑːbɪˈtreɪʃn", "🤝", "binding arbitration / seek arbitration", "The hearing and determining of a dispute by an impartial referee.", "Both parties agreed to binding arbitration to resolve the commercial breach.", ["mediation", "adjudication"], []),
    ("appellant", "noun", "LAW", "Legal_System", "Judicial_Process", "əˈpelənt", "🏛️", "appellant's brief / primary appellant", "A person who applies to a higher court for a reversal of a lower court decision.", "The appellant argued that procedural irregularities invalidated the verdict.", ["petitioner"], ["respondent"]),
    ("deposition", "noun", "LAW", "Legal_System", "Judicial_Process", "ˌdepəˈzɪʃn", "📜", "sworn deposition / take deposition", "The giving of testimony under oath, recorded for use in court.", "Key witness testimony was secured through a formal pre-trial deposition.", ["testimony", "statement"], []),
    ("arraignment", "noun", "LAW", "Legal_System", "Judicial_Process", "əˈreɪnmənt", "🏛️", "formal arraignment / schedule arraignment", "A hearing in which a suspect is charged and pleads guilty or not guilty.", "The defendant entered a plea of not guilty during his morning arraignment.", ["hearing", "charge"], []),
    ("docket", "noun", "LAW", "Legal_System", "Judicial_Process", "ˈdɒkɪt", "📋", "court docket / crowded docket", "A calendar or list of cases for trial.", "The case was added to the supreme court's fall docket.", ["calendar", "schedule"], []),
    ("extradition", "noun", "LAW", "Legal_System", "Judicial_Process", "ˌekstrəˈdɪʃn", "✈️", "extradition treaty / face extradition", "The action of extraditing a person accused or convicted of a crime.", "The suspect contested her extradition to face trial in Europe.", ["deportation", "surrender"], []),
    ("acquittal", "noun", "LAW", "Legal_System", "Judicial_Process", "əˈkwɪtl", "🕊️", "full acquittal / secure acquittal", "A judgment that a person is not guilty of the crime charged.", "The trial ended in a complete acquittal on all felony counts.", ["exoneration", "clearance"], ["conviction"]),
    ("recusal", "noun", "LAW", "Legal_System", "Judicial_Process", "rɪˈkjuːzl", "⚖️", "judicial recusal / demand recusal", "The withdrawal of a judge or prosecutor from a case due to conflict.", "The judge announced her recusal due to personal ties with the defendant.", ["disqualification"], []),
    ("restitution", "noun", "LAW", "Contracts", "Liability_Obligations", "ˌrestɪˈtjuːʃn", "💰", "full restitution / order restitution", "The restoration of something lost or stolen to its proper owner; compensation.", "The court ordered the fraudster to pay full restitution to all victims.", ["compensation", "reimbursement"], []),
    ("perjury", "noun", "LAW", "Legal_System", "Judicial_Process", "ˈpɜːdʒəri", "🤥", "commit perjury / charge with perjury", "The offense of willfully telling an untruth in a court after taking an oath.", "She was convicted of perjury after lying about her whereabouts under oath.", ["false testimony"], ["truthfulness"]),
    ("malfeasance", "noun", "LAW", "Legal_System", "General_Law", "mælˈfiːzəns", "⚠️", "official malfeasance / corporate malfeasance", "Wrongdoing, especially by a public official.", "An independent audit uncovered widespread official malfeasance.", ["misconduct", "impropriety"], ["probity"]),
    ("jurisconsult", "noun", "LAW", "Legal_System", "Jurisprudence", "ˌdʒʊərɪskənˈsʌlt", "🧑‍⚖️", "eminent jurisconsult / expert jurisconsult", "An expert in law who gives opinions on legal questions.", "The government appointed an eminent jurisconsult to draft constitutional revisions.", ["legal expert", "jurist"], []),
    ("statute", "noun", "LAW", "Constitutional_Law", "Legislation", "ˈstætʃuːt", "⚖️", "federal statute / statutory provision", "A written law passed by a legislative body.", "The statute of limitations prevents prosecution after five years.", ["law", "act"], [])
]

print("C1 Dictionary module ready. Seed count:", len(C1_DICTIONARY))
