
const enhancementData = {
    "big": { "opposite": "small", "emoji": "🐘", "oppEmoji": "🐭",
        "en": { "comp": "bigger", "sup": "the biggest" },
        "ru": { "comp": "больше", "sup": "самый большой" },
        "fr": { "comp": "plus grand", "sup": "le plus grand" },
        "it": { "comp": "più grande", "sup": "il più grande" },
        "el": { "comp": "μεγαλύτερος", "sup": "ο μεγαλύτερος" }
    },
    "small": { "opposite": "big", "emoji": "🐭", "oppEmoji": "🐘",
        "en": { "comp": "smaller", "sup": "the smallest" },
        "ru": { "comp": "меньше", "sup": "самый маленький" },
        "fr": { "comp": "plus petit", "sup": "le plus petit" },
        "it": { "comp": "più piccolo", "sup": "il più piccolo" },
        "el": { "comp": "μικρότερος", "sup": "ο μικρότερος" }
    },
    "tall": { "opposite": "short", "emoji": "🦒", "oppEmoji": "📏",
        "en": { "comp": "taller", "sup": "the tallest" },
        "ru": { "comp": "выше", "sup": "самый высокий" },
        "fr": { "comp": "plus grand", "sup": "le plus grand" },
        "it": { "comp": "più alto", "sup": "il più alto" },
        "el": { "comp": "ψηλότερος", "sup": "ο ψηλότερος" }
    },
    "short": { "opposite": "tall", "emoji": "📏", "oppEmoji": "🦒",
        "en": { "comp": "shorter", "sup": "the shortest" },
        "ru": { "comp": "ниже", "sup": "самый короткий" },
        "fr": { "comp": "plus court", "sup": "le plus court" },
        "it": { "comp": "più corto", "sup": "il più corto" },
        "el": { "comp": "κοντύτερος", "sup": "ο κοντύτερος" }
    },
    "hot": { "opposite": "cold", "emoji": "🔥", "oppEmoji": "❄️",
        "en": { "comp": "hotter", "sup": "the hottest" },
        "ru": { "comp": "горячее", "sup": "самый горячий" },
        "fr": { "comp": "plus chaud", "sup": "le plus chaud" },
        "it": { "comp": "più caldo", "sup": "il più caldo" },
        "el": { "comp": "ζεστότερος", "sup": "ο ζεστότερος" }
    },
    "cold": { "opposite": "hot", "emoji": "❄️", "oppEmoji": "🔥",
        "en": { "comp": "colder", "sup": "the coldest" },
        "ru": { "comp": "холоднее", "sup": "самый холодный" },
        "fr": { "comp": "plus froid", "sup": "le plus froid" },
        "it": { "comp": "più fredδο", "sup": "il più freddo" },
        "el": { "comp": "κρυότερος", "sup": "ο κρυότερος" }
    },
    "good": { "opposite": "bad", "emoji": "👍", "oppEmoji": "👎",
        "en": { "comp": "better", "sup": "the best" },
        "ru": { "comp": "лучше", "sup": "самый хороший" },
        "fr": { "comp": "meilleur", "sup": "le meilleur" },
        "it": { "comp": "migliore", "sup": "il migliore" },
        "el": { "comp": "καλύτερος", "sup": "ο καλύτερος" }
    },
    "bad": { "opposite": "good", "emoji": "👎", "oppEmoji": "👍",
        "en": { "comp": "worse", "sup": "the worst" },
        "ru": { "comp": "хуже", "sup": "самый плохой" },
        "fr": { "comp": "pire", "sup": "le pire" },
        "it": { "comp": "peggiore", "sup": "il peggiore" },
        "el": { "comp": "χειρότερος", "sup": "ο χειρότερος" }
    },
    "happy": { "opposite": "sad", "emoji": "😊", "oppEmoji": "😢",
        "en": { "comp": "happier", "sup": "the happiest" },
        "ru": { "comp": "счастливее", "sup": "самый счастливый" },
        "fr": { "comp": "plus heureux", "sup": "le plus heureux" },
        "it": { "comp": "più felice", "sup": "il più felice" },
        "el": { "comp": "ευτυχέστερος", "sup": "ο ευτυχέστερος" }
    },
    "sad": { "opposite": "happy", "emoji": "😢", "oppEmoji": "😊",
        "en": { "comp": "sadder", "sup": "the saddest" },
        "ru": { "comp": "грустнее", "sup": "самый грустный" },
        "fr": { "comp": "plus triste", "sup": "le plus triste" },
        "it": { "comp": "più triste", "sup": "il più triste" },
        "el": { "comp": "λυπηρότερος", "sup": "ο λυπηρότερος" }
    },
    "easy": { "opposite": "difficult", "emoji": "✅", "oppEmoji": "❌",
        "en": { "comp": "easier", "sup": "the easiest" },
        "ru": { "comp": "легче", "sup": "самый легкий" },
        "fr": { "comp": "plus facile", "sup": "le plus facile" },
        "it": { "comp": "più facile", "sup": "il più facile" },
        "el": { "comp": "ευκολότερος", "sup": "ο ευκολότερος" }
    },
    "difficult": { "opposite": "easy", "emoji": "❌", "oppEmoji": "✅",
        "en": { "comp": "more difficult", "sup": "the most difficult" },
        "ru": { "comp": "труднее", "sup": "самый трудный" },
        "fr": { "comp": "plus difficile", "sup": "le plus difficile" },
        "it": { "comp": "più difficile", "sup": "il più difficile" },
        "el": { "comp": "δυσκολότερος", "sup": "ο δυσκολότερος" }
    },
    "expensive": { "opposite": "cheap", "emoji": "💎", "oppEmoji": "🏷️",
        "en": { "comp": "more expensive", "sup": "the most expensive" },
        "ru": { "comp": "дороже", "sup": "самый дорогой" },
        "fr": { "comp": "plus cher", "sup": "le plus cher" },
        "it": { "comp": "più costoso", "sup": "il più costoso" },
        "el": { "comp": "ακριβότερος", "sup": "ο ακριβότερος" }
    },
    "cheap": { "opposite": "expensive", "emoji": "🏷️", "oppEmoji": "💎",
        "en": { "comp": "cheaper", "sup": "the cheapest" },
        "ru": { "comp": "дешевле", "sup": "самый дешевый" },
        "fr": { "comp": "moins cher", "sup": "le moins cher" },
        "it": { "comp": "più economico", "sup": "il più economico" },
        "el": { "comp": "φτηνότερος", "sup": "ο φτηνότερος" }
    },
    "fast": { "opposite": "slow", "emoji": "⚡", "oppEmoji": "🐢",
        "en": { "comp": "faster", "sup": "the fastest" },
        "ru": { "comp": "быстрее", "sup": "самый быстрый" },
        "fr": { "comp": "plus rapide", "sup": "le plus rapide" },
        "it": { "comp": "più veloce", "sup": "il più veloce" },
        "el": { "comp": "γρηγορότερος", "sup": "ο γρηγορότερος" }
    },
    "slow": { "opposite": "fast", "emoji": "🐢", "oppEmoji": "⚡",
        "en": { "comp": "slower", "sup": "the slowest" },
        "ru": { "comp": "медленнее", "sup": "самый медленный" },
        "fr": { "comp": "plus lent", "sup": "le plus lent" },
        "it": { "comp": "più lento", "sup": "il più lento" },
        "el": { "comp": "αργότερος", "sup": "ο αργότερος" }
    },
    "beautiful": { "opposite": "ugly", "emoji": "✨", "oppEmoji": "👹",
        "en": { "comp": "more beautiful", "sup": "the most beautiful" },
        "ru": { "comp": "красивее", "sup": "самый красивый" },
        "fr": { "comp": "plus beau", "sup": "le plus beau" },
        "it": { "comp": "più bello", "sup": "il più bello" },
        "el": { "comp": "ομορφότερος", "sup": "ο ομορφότερος" }
    },
    "clever": { "opposite": "stupid", "emoji": "🧠", "oppEmoji": "🤡",
        "en": { "comp": "cleverer", "sup": "the cleverest" },
        "ru": { "comp": "умнее", "sup": "самый умный" },
        "fr": { "comp": "plus intelligent", "sup": "le plus intelligent" },
        "it": { "comp": "più intelligente", "sup": "il più intelligente" },
        "el": { "comp": "εξυπνότερος", "sup": "ο εξυπνότερος" }
    }
    // ... more will be added dynamically by the global script to cover all 119
};
