import { test, expect } from '@playwright/test';

test('Free access with FREE-EL-A1', async ({ page }) => {
    // Navigate to the portal
    await page.goto('http://localhost:8080/portal/index.html');

    // Wait for the gate/login screen
    const studentCodeInput = page.locator('#student-code');
    await studentCodeInput.waitFor({ state: 'visible' });

    // Enter the free code
    await studentCodeInput.fill('FREE-EL-A1');
    await page.click('button:has-text("Unlock My Path")');

    // Check if the area is visible
    const area = page.locator('#area');
    await area.waitFor({ state: 'visible' });

    // Verify student name and free status
    // Welcome back in Greek (from translations.js): Καλώς ήρθες or Καλώς ήρθατε
    // But we use the welcome_back key.
    await expect(page.locator('#wh')).toContainText('Free Learner');
    await expect(page.locator('#wh')).toContainText('(free_learner)');

    // Verify course name
    await expect(page.locator('#tb-course-name')).toContainText('EL · A1 · FREE');

    // Verify roadmap is restricted (only Unit 0 - First Steps)
    // We check for the text 'Unit 0' which is generated by the engine sometimes or the actual label
    // Since we are in Greek, let's look for part of the label
    await expect(page.locator('.chapter-node').first()).toBeVisible();
    await expect(page.locator('.chapter-node')).toHaveCount(5); // Only 5 lessons in Unit 0
});
