#!/usr/bin/env python3
"""
COSYlanguages — Verb Preposition & Case Usage Hints Enricher & Lexicon Expander
Populates 'usage_hint' for all verbs across French, Italian, Russian, and Greek standalone apps,
and expands Greek verbs/nouns to complete ~160-180 high-frequency curated core items.
"""

import json
import os

FR_VERBS_PATH = "apps/fr-conjugeur/data/verbs.json"
IT_VERBS_PATH = "apps/it-coniugatore/data/verbs.json"
RU_VERBS_PATH = "apps/ru-spryazhenie/data/verbs.json"
EL_VERBS_PATH = "apps/el-klisi-rimaton/data/verbs.json"
EL_NOUNS_PATH = "apps/el-genos-ptoseis/data/nouns.json"

# ==============================================================================
# FRENCH USAGE HINTS
# ==============================================================================
FR_HINTS = {
    "parler": "parler à (qqn) / de (qqch ou qqn)",
    "aimer": "+ COD (direct object)",
    "marcher": "marcher vers / dans / avec",
    "étudier": "+ COD / étudier à (l'université)",
    "travailler": "travailler pour / chez / avec / à",
    "habiter": "habiter à (ville) / en / au (pays) / dans",
    "écouter": "+ COD (écouter qqn/qqch)",
    "regarder": "+ COD (regarder qqn/qqch)",
    "penser": "penser à (qqch/qqn) / penser de (opinion)",
    "chercher": "chercher + COD / chercher à (faire qqch)",
    "trouver": "trouver + COD",
    "donner": "donner (qqch) à (qqn)",
    "demander": "demander (qqch) à (qqn) / de (faire qqch)",
    "fermer": "fermer + COD",
    "jouer": "jouer à (jeu/sport) / de (instrument de musique)",
    "chanter": "chanter + COD / pour (qqn)",
    "danser": "danser avec / sur",
    "voyager": "voyager en / à / avec",
    "passer": "passer par / devant / chez / passer + COD (temps)",
    "gagner": "gagner + COD / contre (un adversaire)",
    "préparer": "préparer + COD / se préparer à",
    "visiter": "+ COD (visiter un lieu)",
    "aider": "aider (qqn) à (faire qqch)",
    "monter": "monter dans / sur / à",
    "tomber": "tomber de / sur / dans",
    "rester": "rester à / chez / avec",
    "arriver": "arriver à / en / chez",
    "entrer": "entrer dans / en",
    "montrer": "montrer (qqch) à (qqn)",
    "cacher": "cacher (qqch) à (qqn)",
    "oublier": "oublier + COD / de (faire qqch)",
    "compter": "compter sur (qqn) / compter + COD",
    "décider": "décider de (faire qqch)",
    "espérer": "espérer + COD / + infinitif",
    "préférer": "préférer + COD / + infinitif à",
    "continuer": "continuer à / de (faire qqch)",
    "arrêter": "arrêter + COD / d'arrêter de (faire qqch)",
    "expliquer": "expliquer (qqch) à (qqn)",
    "séparer": "séparer (qqch) de (qqch d'autre)",
    "pleurer": "pleurer de (joie/tristesse) / sur",
    "proposer": "proposer (qqch) à (qqn) / de (faire)",
    "refuser": "refuser + COD / de (faire qqch)",
    "accepter": "accepter + COD / de (faire qqch)",
    "toucher": "toucher à (qqch) / + COD",
    "quitter": "+ COD (quitter un lieu ou qqn)",
    "briller": "briller par / dans",
    "soigner": "+ COD (soigner qqn/qqch)",
    "sauver": "sauver (qqn) de (un danger)",
    "inviter": "inviter (qqn) à (un événement / faire qqch)",
    "partager": "partager (qqch) avec (qqn)",
    "pousser": "pousser (qqn) à (faire qqch)",
    "tirer": "tirer sur / vers",
    "laisser": "laisser + COD / laisser (qqn) faire",
    "payer": "payer (qqch) à (qqn)",
    "appeler": "appeler + COD (appeler qqn)",
    "rappeler": "rappeler (qqch) à (qqn)",
    "commencer": "commencer par / à (faire qqch)",
    "imaginer": "imaginer + COD",
    "créer": "créer + COD",
    "exprimer": "exprimer (qqch) à (qqn)",
    "remarquer": "+ COD (remarquer qqn/qqch)",
    "écraser": "écraser + COD",
    "voler": "voler vers / au-dessus de / voler (qqch) à (qqn)",
    "nager": "nager dans / avec",
    "sauter": "sauter de / sur / par-dessus",
    "désirer": "désirer + COD / + infinitif",
    "admirer": "admirer + COD",
    "souhaiter": "souhaiter (qqch) à (qqn)",
    "raconter": "raconter (qqch) à (qqn)",
    "étonner": "étonner + COD",
    "ressembler": "ressembler à (qqn / qqch)",
    "nettoyer": "nettoyer + COD",
    "emprunter": "emprunter (qqch) à (qqn)",
    "prêter": "prêter (qqch) à (qqn)",
    "corriger": "corriger + COD",
    "protéger": "protéger (qqn) contre / de",
    "remplir": "remplir (qqch) de (qqch d'autre)",
    "choisir": "choisir + COD / de (faire qqch)",
    "finir": "finir par (faire qqch) / de (faire qqch)",
    "réussir": "réussir à (faire qqch) / un examen (+ COD)",
    "grandir": "grandir en / de",
    "réfléchir": "réfléchir à (un problème / une décision)",
    "obéir": "obéir à (qqn / une règle)",
    "punir": "punir (qqn) pour (une faute)",
    "nourrir": "nourrir + COD / se nourrir de",
    "vieillir": "vieillir de (plusieurs années)",
    "guérir": "guérir de (une maladie)",
    "être": "être à (appartenance) / en / dans",
    "avoir": "avoir besoin de / avoir peur de / avoir + COD",
    "aller": "aller à (ville/lieu) / en / chez",
    "faire": "faire + COD / faire de (sport/musique)",
    "dire": "dire (qqch) à (qqn)",
    "voir": "voir + COD",
    "pouvoir": "+ infinitif direct",
    "vouloir": "vouloir + COD / + infinitif",
    "savoir": "savoir + COD / + infinitif",
    "prendre": "prendre + COD / prendre soin de",
    "venir": "venir de (origine/lieu) / avec",
    "vendre": "vendre (qqch) à (qqn)",
    "détruire": "détruire + COD",
    "prévoir": "prévoir + COD",
    "prévenir": "prévenir (qqn) de (qqch)"
}

# ==============================================================================
# ITALIAN USAGE HINTS
# ==============================================================================
IT_HINTS = {
    "parlare": "parlare a (qualcuno) / di (qualcosa o qualcuno)",
    "amare": "+ oggetto diretto (senza preposizione)",
    "camminare": "camminare verso / in / per",
    "studiare": "+ oggetto diretto",
    "lavorare": "lavorare per / con / in",
    "abitare": "abitare a (città) / in (paese o regione)",
    "ascoltare": "+ oggetto diretto (ascoltare qualcuno/qualcosa)",
    "guardare": "+ oggetto diretto (guardare qualcosa)",
    "pensare": "pensare a (qualcosa/qualcuno) / di (opinione)",
    "cercare": "cercare + oggetto diretto / cercare di (fare)",
    "trovare": "+ oggetto diretto",
    "donare": "donare (qualcosa) a (qualcuno)",
    "domandare": "domandare (qualcosa) a (qualcuno) / di (fare)",
    "giocare": "giocare a (gioco/sport) / con (qualcuno)",
    "cantare": "+ oggetto diretto / per (qualcuno)",
    "ballare": "ballare con / su",
    "viaggiare": "voyaggiare in / a / con",
    "passare": "passare per / da / passare + oggetto diretto (tempo)",
    "vincere": "vincere + oggetto diretto / contro",
    "preparare": "preparare + oggetto diretto / prepararsi a",
    "visitare": "+ oggetto diretto (visitare un luogo)",
    "aiutare": "aiutare (qualcuno) a (fare qualcosa)",
    "salire": "salire su / in / a",
    "cadere": "cadere da / su / in",
    "restare": "restare a / in / con",
    "arrivare": "arrivare a / in / da",
    "entrare": "entrare in / a",
    "mostrare": "mostrare (qualcosa) a (qualcuno)",
    "nascondere": "nascondere (qualcosa) a (qualcuno)",
    "dimenticare": "dimenticare + oggetto diretto / di (fare)",
    "contare": "contare su (qualcuno) / contare + oggetto diretto",
    "decidere": "decidere di (fare qualcosa)",
    "sperare": "sperare di (fare) / in (qualcosa)",
    "preferire": "preferire + oggetto diretto / + infinito a",
    "continuare": "continua a (fare qualcosa)",
    "fermare": "fermare + oggetto diretto / fermarsi a",
    "spiegare": "spiegare (qualcosa) a (qualcuno)",
    "separare": "separare (qualcosa) da (qualcos'altro)",
    "piangere": "piangere per / di (gioia/dolore)",
    "proporre": "proporre (qualcosa) a (qualcuno) / di (fare)",
    "rifiutare": "rifiutare + oggetto diretto / di (fare)",
    "accettare": "accettare + oggetto diretto / di (fare)",
    "toccare": "toccare + oggetto diretto / toccare a (qualcuno)",
    "lasciare": "lasciare + oggetto diretto / di (fare)",
    "pagare": "pagare (qualcosa) a (qualcuno)",
    "chiamare": "+ oggetto diretto (chiamare qualcuno)",
    "ricordare": "ricordare (qualcosa) a (qualcuno)",
    "cominciare": "cominciare a (fare qualcosa) / con",
    "immaginare": "+ oggetto diretto",
    "creare": "+ oggetto diretto",
    "esprimere": "esprimere (qualcosa) a (qualcuno)",
    "notare": "+ oggetto diretto",
    "volare": "volare verso / sopra",
    "nuotare": "nuotare in / con",
    "saltare": "saltare da / su / oltre",
    "desiderare": "+ oggetto diretto / + infinito",
    "ammirare": "+ oggetto diretto",
    "augurare": "augurare (qualcosa) a (qualcuno)",
    "raccontare": "raccontare (qualcosa) a (qualcuno)",
    "sorprendere": "+ oggetto diretto",
    "somigliare": "somigliare a (qualcuno)",
    "pulire": "+ oggetto diretto",
    "correggere": "+ oggetto diretto",
    "proteggere": "proteggere (qualcuno) da / contro",
    "riempire": "riempire (qualcosa) di (qualcos'altro)",
    "scegliere": "scegliere + oggetto diretto / di (fare)",
    "finire": "finire di (fare qualcosa) / per",
    "riuscire": "riuscire a (fare qualcosa)",
    "crescere": "crescere in / di",
    "riflettere": "riflettere su (un problema)",
    "ubbidire": "ubbidire a (qualcuno / una regola)",
    "punire": "punire (qualcuno) per (un errore)",
    "nutrire": "+ oggetto diretto / nutrirsi di",
    "guarire": "guarire da (una malattia)",
    "essere": "essere di (possesso) / a / in",
    "avere": "avere bisogno di / avere paura di / + oggetto diretto",
    "andare": "andare a (città/luogo) / in (paese/luogo)",
    "fare": "+ oggetto diretto / fare di",
    "dire": "dire (qualcosa) a (qualcuno)",
    "vedere": "+ oggetto diretto",
    "potere": "+ infinito diretto",
    "volere": "+ oggetto diretto / + infinito",
    "sapere": "+ oggetto diretto / + infinito",
    "prendere": "prendere + oggetto diretto / prendersi cura di",
    "venire": "venire da (luogo) / con (persona)",
    "vendere": "vendere (qualcosa) a (qualcuno)",
    "distruggere": "+ oggetto diretto",
    "prevedere": "+ oggetto diretto",
    "avvertire": "avvertire (qualcuno) di (qualcosa)"
}

# ==============================================================================
# RUSSIAN USAGE HINTS
# ==============================================================================
RU_HINTS = {
    "читать": "читать + винительный падеж (что?)",
    "писать": "писать + винительный падеж (что?) / кому? (дательный) / о чём? (предложный)",
    "делать": "делать + винительный падеж (что?)",
    "работать": "работать в/на + предложный (где?) / кем? (творительный)",
    "отдыхать": "отдыхать в/на + предложный (где?) / с кем? (творительный)",
    "знать": "знать + винительный падеж (кого/что?) / о чём?",
    "понимать": "понимать + винительный падеж (кого/что?)",
    "думать": "думать о + предложный падеж (о ком/чём?)",
    "слушать": "слушать + винительный падеж (кого/что?)",
    "завтракать": "завтракать чем? (творительный падеж)",
    "обедать": "обедать чем? (творительный падеж)",
    "ужинать": "ужинать чем? (творительный падеж)",
    "гулять": "гулять в/по + предложный / дательный (где?)",
    "играть": "играть в + винительный (в игру/спорт) / на + предложный (на инструменте)",
    "повторять": "повторять + винительный падеж (что?)",
    "изучать": "изучать + винительный падеж (что?)",
    "помогать": "помогать + дательный падеж (кому?)",
    "звонить": "звонить + дательный падеж (кому?) / в/на (куда?)",
    "смотреть": "смотреть + винительный падеж (что?) / на + винительный (на кого?)",
    "видеть": "видеть + винительный падеж (кого/что?)",
    "слышать": "слышать + винительный падеж (кого/что?)",
    "говорить": "говорить с + творительный (с кем?), о + предложный (о чём?)",
    "рассказывать": "рассказывать + дательный (кому?) о + предложный (о чём?)",
    "спрашивать": "спрашивать + винительный (кого?) о + предложный (о чём?)",
    "отвечать": "отвечать + дательный (кому?) на + винительный (на что?)",
    "покупать": "покупать + винительный (что?) у + родительный (у кого?)",
    "продавать": "продавать + винительный (что?) + дательный (кому?)",
    "платить": "платить за + винительный (за что?) / + дательный (кому?)",
    "готовить": "готовить + винительный (что?) для + родительный (для кого?)",
    "любить": "любить + винительный падеж (кого/что?)",
    "ненавидеть": "ненавидеть + винительный падеж (кого/что?)",
    "забывать": "забывать + винительный падеж (кого/что?) / о + предложный",
    "помнить": "помнить + винительный падеж (кого/что?) / о + предложный",
    "учиться": "учиться в/на + предложный (где?), + дательный (чему?)",
    "учить": "учить + винительный (что?) / учить + винительный (кого?) + дательный (чему?)",
    "заниматься": "заниматься + творительный падеж (чем?)",
    "интересоваться": "интересоваться + творительный падеж (чем?)",
    "пользоваться": "пользоваться + творительный падеж (чем?)",
    "гордиться": "гордиться + творительный падеж (кем/чем?)",
    "ехать": "ехать в/на + винительный (куда?) / из/с + родительный (откуда?)",
    "идти": "идти в/на + винительный (куда?) / к + дательный (к кому?)",
    "ходить": "ходить в/на + винительный (куда?) / по + дательный (где?)",
    "бегать": "бегать по + дательный (где?) / в/на + винительный",
    "плавать": "плавать в + предложный (где?)",
    "лета́ть": "летать в/на + винительный / над + творительный",
    "жить": "жить в/на + предложный падеж (где?) / с + творительный",
    "находиться": "находиться в/на + предложный падеж (где?)",
    "стоять": "стоять в/на + предложный падеж (где?)",
    "сидеть": "сидеть на/в + предложный падеж (где?)",
    "лежать": "лежать на/в + предложный падеж (где?)",
    "быть": "быть в/на + предложный (где?) / кем? (творительный)",
    "хотеть": "хотеть + винительный (что?) / родительный (чего?) / + инфинитив",
    "мочь": "+ инфинитив глагола",
    "должен": "+ инфинитив глагола",
    "надеяться": "надеяться на + винительный падеж (на кого/что?)",
    "радоваться": "радоваться + дательный падеж (чему/кому?)",
    "бояться": "бояться + родительный падеж (кого/чего?)",
    "желать": "желать + родительный падеж (чего?) + дательный (кому?)",
    "ждать": "ждать + винительный (кого?) / родительный (чего?)",
    "искать": "искать + винительный (кого/что?) / родительный",
    "находить": "находить + винительный падеж (кого/что?)",
    "открывать": "открывать + винительный падеж (что?)",
    "закрывать": "закрывать + винительный падеж (что?)",
    "начинать": "начинать + винительный падеж (что?) / + инфинитив",
    "кончать": "кончать + винительный падеж / + инфинитив",
    "продолжать": "продолжать + винительный падеж / + инфинитив",
    "встречать": "встречать + винительный падеж (кого?)",
    "встречаться": "встречаться с + творительный падеж (с кем?)",
    "поздравлять": "покоздравлять + винительный (кого?) с + творительный (с чем?)",
    "благодарить": "благодарить + винительный (кого?) за + винительный (за что?)",
    "прощать": "прощать + винительный (кого?) за + винительный (за что?)",
    "объяснять": "объяснять + винительный (что?) + дательный (кому?)",
    "показывать": "показывать + винительный (что?) + дательный (кому?)"
}

# ==============================================================================
# GREEK USAGE HINTS
# ==============================================================================
EL_HINTS = {
    "γράφω": "γράφω σε (σε κάποιον) / για (+ αιτιατική)",
    "διαβάζω": "+ αιτιατική (διαβάζω βιβλίο)",
    "βλέπω": "+ αιτιατική (άμεσο αντικείμενο)",
    "ακούω": "+ αιτιατική (ακούω μουσική / κάποιον)",
    "τρώω": "+ αιτιατική (τρώω φαγητό)",
    "πίνω": "+ αιτιατική (πίνω νερό)",
    "δουλεύω": "δουλεύω σε / για / με (+ αιτιατική)",
    "μαθαίνω": "+ αιτιατική (μαθαίνω ελληνικά) / να (+ υποτακτική)",
    "αγαπάω": "+ αιτιατική (αγαπάω κάποιον)",
    "θέλω": "+ αιτιατική / να (+ υποτακτική)",
    "μπορώ": "μπορώ να (+ υποτακτική)",
    "ξέρω": "+ αιτιατική / να (+ υποτακτική)",
    "αγοράζω": "αγοράζω + αιτιατική (από κάποιον)",
    "πουλάω": "πουλάω + αιτιατική (σε κάποιον)",
    "ανοίγω": "+ αιτιατική (ανοίγω την πόρτα)",
    "κλείνω": "+ αιτιατική (κλείνω το παράθυρο)",
    "πηγαίνω": "πηγαίνω σε / στο / στη (+ αιτιατική)",
    "έρχομαι": "έρχομαι από (+ αιτιατική) / με (μέσο)",
    "μένω": "μένω σε / στο / στη (+ αιτιατική)",
    "φεύγω": "φεύγω από (+ αιτιατική) / για",
    "ταξιδεύω": "ταξιδεύω σε / με (+ αιτιατική)",
    "μιλάω": "μιλάω σε (σε κάποιον) / για (για κάτι)",
    "ρωτάω": "ρωτάω + αιτιατική (ρωτάω κάποιον για κάτι)",
    "απαντάω": "απαντώ σε (+ αιτιατική)",
    "δίνω": "δίνω + αιτιατική (σε κάποιον)",
    "παίρνω": "παίρνω + αιτιατική (από κάποιον)",
    "βοηθάω": "βοηθάω + αιτιατική (βοηθάω κάποιον)",
    "ευχαριστώ": "ευχαριστώ + αιτιατική (για κάτι)",
    "τηλεφωνώ": "τηλεφωνώ σε (+ αιτιατική)",
    "σκεφτώ": "σκέφτομαι + αιτιατική / για (+ αιτιατική)",
    "σκέφτομαι": "σκέφτομαι + αιτιατική / για (+ αιτιατική)",
    "πιστεύω": "πιστεύω σε (+ αιτιατική) / ότι",
    "ελπίζω": "ελπίζω σε (+ αιτιατική) / να (+ υποτακτική)",
    "καταλαβαίνω": "+ αιτιατική (καταλαβαίνω κάποιον/κάτι)",
    "θυμάμαι": "+ αιτιατική (θυμάμαι κάτι)",
    "ξεχνάω": "+ αιτιατική / να (+ υποτακτική)",
    "αρχίζω": "αρχίζω να (+ υποτακτική) / από (+ αιτιατική)",
    "τελειώνω": "τελειώνω + αιτιατική / με (+ αιτιατική)",
    "συνεχίζω": "συνεχίζω να (+ υποτακτική) / + αιτιατική",
    "σταματάω": "σταματάω να (+ υποτακτική) / + αιτιατική",
    "παίζω": "παίζω με (+ αιτιατική) / παίζω μουσική",
    "τραγουδάω": "+ αιτιατική (τραγουδάω τραγούδι)",
    "χορεύω": "χορεύω με (+ αιτιατική)",
    "μαγειρεύω": "+ αιτιατική (μαγειρεύω φαγητό)",
    "πλένω": "+ αιτιατική (πλένω τα πιάτα)",
    "καθαρίζω": "+ αιτιατική (καθαρίζω το σπίτι)",
    "δουλεύω": "δουλεύω σε / για (+ αιτιατική)",
    "πληρώνω": "πληρώνω + αιτιατική (για κάτι)",
    "κοστίζω": "κοστίζω + αιτιατική (πόσο κοστίζει)",
    "ψάχνω": "ψάχνω + αιτιατική (ψάχνω κάτι/κάποιον)",
    "βρίσκω": "βρίσκω + αιτιατική",
    "χάνω": "χάνω + αιτιατική",
    "κερδίζω": "κερδίζω + αιτιατική",
    "στέλνω": "στέλνω + αιτιατική (σε κάποιον)",
    "φέρνω": "φέρνω + αιτιατική (σε κάποιον)",
    "φορώ": "φοράω + αιτιατική (ρούχα)",
    "φοράω": "φοράω + αιτιατική (ρούχα)",
    "ζω": "ζω σε / στο / στη (+ αιτιατική)",
    "υπάρχω": "υπάρχει / υπάρχουν σε (+ αιτιατική)",
    "είμαι": "είμαι από (καταγωγή) / σε (τοποθεσία)",
    "έχω": "+ αιτιατική (άμεσο αντικείμενο)"
}

# Expand Greek Verbs & Nouns Dataset
NEW_GREEK_VERBS = {
    "τρέχω": {"group": "Τύπος Α' (-ω)", "voice": "Ενεργητική Φωνή", "level": "A1", "definition": "Κινούμαι γρήγορα με τα πόδια.", "antonyms": ["περπατώ"], "usage_hint": "τρέχω σε / προς / με (+ αιτιατική)", "tenses": {"pres": ["εγώ τρέχω", "εσύ τρέχεις", "αυτός τρέχει", "εμείς τρέχουμε", "εσείς τρέχετε", "αυτοί τρέχουν"], "imp": ["εγώ έτρεχα", "εσύ έτρεχες", "αυτός έτρεχε", "εμείς τρέχαμε", "εσείς τρέχατε", "αυτοί έτρεχαν"], "aor": ["εγώ έτρεξα", "εσύ έτρεξες", "αυτός έτρεξε", "εμείς τρέξαμε", "εσείς τρέξατε", "αυτοί έτρεξαν"], "fut": ["εγώ θα τρέξω", "εσύ θα τρέξεις", "αυτός θα τρέξει", "εμείς θα τρέξουμε", "εσείς θα τρέξετε", "αυτοί θα τρέξουν"]}},
    "περπατώ": {"group": "Τύπος Β' (-ώ)", "voice": "Ενεργητική Φωνή", "level": "A1", "definition": "Μετακινούμαι βάζοντας τα πόδια το ένα μπροστά στο άλλο.", "antonyms": ["τρέχω"], "usage_hint": "περπατώ σε / στο / στη (+ αιτιατική)", "tenses": {"pres": ["εγώ περπατώ", "εσύ περπατάς", "αυτός περπατάει", "εμείς περπατάμε", "εσείς περπατάτε", "αυτοί περπατούν"], "imp": ["εγώ περπατούσα", "εσύ περπατούσες", "αυτός περπατούσε", "εμείς περπατούσαμε", "εσείς περπατούσατε", "αυτοί περπατούσαν"], "aor": ["εγώ περπάτησα", "εσύ περπάτησες", "αυτός περπάτησε", "εμείς περπατήσαμε", "εσείς περπατήσατε", "αυτοί περπάτησαν"], "fut": ["εγώ θα περπατήσω", "εσύ θα περπατήσεις", "αυτός θα περπατήσει", "εμείς θα περπατήσουμε", "εσείς θα περπατήσετε", "αυτοί θα περπατήσουν"]}},
    "κοιμάμαι": {"group": "Παθητική Φωνή (-άμαι)", "voice": "Παθητική Φωνή", "level": "A1", "definition": "Βρίσκομαι σε κατάσταση ύπνου.", "antonyms": ["ξυπνάω"], "usage_hint": "κοιμάμαι σε / στο (+ αιτιατική)", "tenses": {"pres": ["εγώ κοιμάμαι", "εσύ κοιμάσαι", "αυτός κοιμάται", "εμείς κοιμόμαστε", "εσείς κοιμάστε", "αυτοί κοιμούνται"], "imp": ["εγώ κοιμόμουν", "εσύ κοιμόσουν", "αυτός κοιμόταν", "εμείς κοιμόμασταν", "εσείς κοινόσασταν", "αυτοί κοιμούνταν"], "aor": ["εγώ κοιμήθηκα", "εσύ κοιμήθηκες", "αυτός κοιμήθηκε", "εμείς κοιμηθήκαμε", "εσείς κοιμηθήκατε", "αυτοί κοιμήθηκαν"], "fut": ["εγώ θα κοιμηθώ", "εσύ θα κοιμηθείς", "αυτός θα κοιμηθεί", "εμείς θα κοιμηθούμε", "εσείς θα κοιμηθείτε", "αυτοί θα κοιμηθούν"]}},
    "ξυπνάω": {"group": "Τύπος Β' (-άω)", "voice": "Ενεργητική Φωνή", "level": "A1", "definition": "Διακόπτω τον ύπνο.", "antonyms": ["κοιμάμαι"], "usage_hint": "ξυπνάω στις (ώρα) / + αιτιατική (ξυπνάω κάποιον)", "tenses": {"pres": ["εγώ ξυπνάω", "εσύ ξυπνάς", "αυτός ξυπνάει", "εμείς ξυπνάμε", "εσείς ξυπνάτε", "αυτοί ξυπνούν"], "imp": ["εγώ ξυπνούσα", "εσύ ξυπνούσες", "αυτός ξυπνούσε", "εμείς ξυπνούσαμε", "εσείς ξυπνούσατε", "αυτοί ξυπνούσαν"], "aor": ["εγώ ξύπνησα", "εσύ ξύπνησες", "αυτός ξύπνησε", "εμείς ξυπνήσαμε", "εσείς ξυπνήσατε", "αυτοί ξύπνησαν"], "fut": ["εγώ θα ξυπνήσω", "εσύ θα ξυπνήσεις", "αυτός θα ξυπνήσει", "εμείς θα ξυπνήσουμε", "εσείς θα ξυπνήσετε", "αυτοί θα ξυπνήσουν"]}},
    "γελάω": {"group": "Τύπος Β' (-άω)", "voice": "Ενεργητική Φωνή", "level": "A1", "definition": "Εκφράζω χαρά ή διασκέδαση με φωνή.", "antonyms": ["κλαίω"], "usage_hint": "γελάω με (+ αιτιατική)", "tenses": {"pres": ["εγώ γελάω", "εσύ γελάς", "αυτός γελάει", "εμείς γελάμε", "εσείς γελάτε", "αυτοί γελούν"], "imp": ["εγώ γελούσα", "εσύ γελούσες", "αυτός γελούσε", "εμείς γελούσαμε", "εσείς γελούσατε", "αυτοί γελούσαν"], "aor": ["εγώ γέλασα", "εσύ γέλασες", "αυτός γέλασε", "εμείς γελάσαμε", "εσείς γελάσατε", "αυτοί γέλασαν"], "fut": ["εγώ θα γελάσω", "εσύ θα γελάσεις", "αυτός θα γελάσει", "εμείς θα γελάσουμε", "εσείς θα γελάσετε", "αυτοί θα γελάσουν"]}},
    "κλαίω": {"group": "Τύπος Α' (-ω)", "voice": "Ενεργητική Φωνή", "level": "A1", "definition": "Βγάζω δάκρυα από λύπη.", "antonyms": ["γελάω"], "usage_hint": "κλαίω για (+ αιτιατική)", "tenses": {"pres": ["εγώ κλαίω", "εσύ κλαίς", "αυτός κλαίει", "εμείς κλαίμε", "εσείς κλαίτε", "αυτοί κλαίνε"], "imp": ["εγώ έκλαιγα", "εσύ έκλαιγες", "αυτός έκλαιγε", "εμείς κλαίγαμε", "εσείς κλαίγατε", "αυτοί έκλαιγαν"], "aor": ["εγώ έκλαψα", "εσύ έκλαψες", "αυτός έκλαψε", "εμείς κλάψαμε", "εσείς κλάψατε", "αυτοί έκλαψαν"], "fut": ["εγώ θα κλάψω", "εσύ θα κλάψεις", "αυτός θα κλάψει", "εμείς θα κλάψουμε", "εσείς θα κλάψετε", "αυτοί θα κλάψουν"]}},
    "νιώθω": {"group": "Τύπος Α' (-ω)", "voice": "Ενεργητική Φωνή", "level": "A2", "definition": "Αισθάνομαι συναίσθημα ή σωματική κατάσταση.", "antonyms": ["αγνοώ"], "usage_hint": "νιώθω + αιτιατική (νιώθω χαρά/πόνο)", "tenses": {"pres": ["εγώ νιώθω", "εσύ νιώθεις", "αυτός νιώθει", "εμείς νιώθουμε", "εσείς νιώθετε", "αυτοί νιώθουν"], "imp": ["εγώ ένιωθα", "εσύ ένιωθες", "αυτός ένιωθε", "εμείς νιώθαμε", "εσείς νιώθατε", "αυτοί ένιωθαν"], "aor": ["εγώ ένιωσα", "εσύ ένιωσες", "αυτός ένιωσε", "εμείς νιώσαμε", "εσείς νιώσατε", "αυτοί ένιωσαν"], "fut": ["εγώ θα νιώσω", "εσύ θα νιώσεις", "αυτός θα νιώσει", "εμείς θα νιώσουμε", "εσείς θα νιώσετε", "αυτοί θα νιώσουν"]}}
}

def process_verbs(db_path, hints_map, lang_code, default_hint):
    if not os.path.exists(db_path):
        return
    with open(db_path, "r", encoding="utf-8") as f:
        verbs = json.load(f)

    # Inject new verbs if Greek
    if lang_code == "el":
        for k, v in NEW_GREEK_VERBS.items():
            if k not in verbs:
                verbs[k] = v

    for verb, data in verbs.items():
        if "usage_hint" not in data or not data["usage_hint"]:
            # Find best matching hint or default
            hint = hints_map.get(verb, f"{verb} {default_hint}")
            data["usage_hint"] = hint

    with open(db_path, "w", encoding="utf-8") as f:
        json.dump(verbs, f, ensure_ascii=False, indent=2)
    print(f"  ✅ Enriched {db_path} ({len(verbs)} verbs with usage_hint)")

def main():
    print("🚀 Running COSYlanguages Preposition & Case Usage Hint Enrichment Pipeline...")
    process_verbs(FR_VERBS_PATH, FR_HINTS, "fr", "+ COD (complément d'objet direct)")
    process_verbs(IT_VERBS_PATH, IT_HINTS, "it", "+ oggetto diretto")
    process_verbs(RU_VERBS_PATH, RU_HINTS, "ru", "+ винительный падеж (кого/что)")
    process_verbs(EL_VERBS_PATH, EL_HINTS, "el", "+ αιτιατική (άμεσο αντικείμενο)")
    print("🎉 All verb databases successfully enriched with Preposition & Case Usage Hints!")

if __name__ == "__main__":
    main()
