const fs = require('fs');
const path = require('path');

// Ported from scripts/enrich_etymology.js
const etymDict = {
    "en": {
        "arm": { "origin_lang": "Proto-Germanic", "origin_word": "armaz" },
        "water": { "origin_lang": "Proto-Germanic", "origin_word": "watōr" },
        "house": { "origin_lang": "Proto-Germanic", "origin_word": "hūsą" },
        "bread": { "origin_lang": "Proto-Germanic", "origin_word": "braudą" },
        "hand": { "origin_lang": "Proto-Germanic", "origin_word": "handuz" },
        "sun": { "origin_lang": "Proto-Germanic", "origin_word": "sunnō" },
        "moon": { "origin_lang": "Proto-Germanic", "origin_word": "mēnô" },
        "mother": { "origin_lang": "Proto-Germanic", "origin_word": "mōdēr" },
        "father": { "origin_lang": "Proto-Germanic", "origin_word": "fader" },
        "brother": { "origin_lang": "Proto-Germanic", "origin_word": "brōþēr" },
        "sister": { "origin_lang": "Proto-Germanic", "origin_word": "swestēr" },
        "son": { "origin_lang": "Proto-Germanic", "origin_word": "sunuz" },
        "daughter": { "origin_lang": "Proto-Germanic", "origin_word": "duhtēr" },
        "be": { "origin_lang": "Proto-Germanic", "origin_word": "beun" },
        "have": { "origin_lang": "Proto-Germanic", "origin_word": "habjaną" },
        "go": { "origin_lang": "Proto-Germanic", "origin_word": "ganganą" },
        "eat": { "origin_lang": "Proto-Germanic", "origin_word": "etaną" },
        "drink": { "origin_lang": "Proto-Germanic", "origin_word": "drinkaną" },
        "speak": { "origin_lang": "Proto-Germanic", "origin_word": "sprekaną" },
        "foot": { "origin_lang": "Proto-Germanic", "origin_word": "fōts" },
        "eye": { "origin_lang": "Proto-Germanic", "origin_word": "augô" },
        "nose": { "origin_lang": "Proto-Germanic", "origin_word": "nasō" },
        "mouth": { "origin_lang": "Proto-Germanic", "origin_word": "munþaz" },
        "ear": { "origin_lang": "Proto-Germanic", "origin_word": "auzon" },
        "heart": { "origin_lang": "Proto-Germanic", "origin_word": "hertō" },
        "see": { "origin_lang": "Proto-Germanic", "origin_word": "sehwan" },
        "hear": { "origin_lang": "Proto-Germanic", "origin_word": "hauzjan" },
        "head": { "origin_lang": "Proto-Germanic", "origin_word": "haubidą" },
        "one": { "origin_lang": "Proto-Germanic", "origin_word": "ainaz" },
        "two": { "origin_lang": "Proto-Germanic", "origin_word": "twai" },
        "three": { "origin_lang": "Proto-Germanic", "origin_word": "þrijiz" },
        "four": { "origin_lang": "Proto-Germanic", "origin_word": "fedwōr" },
        "five": { "origin_lang": "Proto-Germanic", "origin_word": "fimf" },
        "six": { "origin_lang": "Proto-Germanic", "origin_word": "sehs" },
        "seven": { "origin_lang": "Proto-Germanic", "origin_word": "sibun" },
        "eight": { "origin_lang": "Proto-Germanic", "origin_word": "ahtōu" },
        "nine": { "origin_lang": "Proto-Germanic", "origin_word": "newun" },
        "ten": { "origin_lang": "Proto-Germanic", "origin_word": "tehun" },
        "red": { "origin_lang": "Proto-Germanic", "origin_word": "raudaz" },
        "blue": { "origin_lang": "Proto-Germanic", "origin_word": "blēwaz" },
        "green": { "origin_lang": "Proto-Germanic", "origin_word": "grōniz" },
        "white": { "origin_lang": "Proto-Germanic", "origin_word": "hwītaz" },
        "black": { "origin_lang": "Proto-Germanic", "origin_word": "blakaz" },
        "yellow": { "origin_lang": "Proto-Germanic", "origin_word": "gelwaz" },
        "good": { "origin_lang": "Proto-Germanic", "origin_word": "gōdaz" },
        "bad": { "origin_lang": "Middle English", "origin_word": "badde" },
        "big": { "origin_lang": "Middle English", "origin_word": "bigge" },
        "small": { "origin_lang": "Proto-Germanic", "origin_word": "smalaz" },
        "together": { "origin_lang": "Proto-Germanic", "origin_word": "gaduri" },
        "friend": { "origin_lang": "Proto-Germanic", "origin_word": "frijōndz" },
        "dog": { "origin_lang": "Old English", "origin_word": "docga" },
        "cat": { "origin_lang": "Latin", "origin_word": "cattus" },
        "fish": { "origin_lang": "Proto-Germanic", "origin_word": "fiskaz" },
        "bird": { "origin_lang": "Old English", "origin_word": "bridd" },
        "tree": { "origin_lang": "Proto-Germanic", "origin_word": "trewą" },
        "sky": { "origin_lang": "Old Norse", "origin_word": "ský" },
        "rain": { "origin_lang": "Proto-Germanic", "origin_word": "rigną" },
        "fire": { "origin_lang": "Proto-Germanic", "origin_word": "fōr" },
        "long": { "origin_lang": "Proto-Germanic", "origin_word": "langaz" },
        "cold": { "origin_lang": "Proto-Germanic", "origin_word": "kaldaz" },
        "new": { "origin_lang": "Proto-Germanic", "origin_word": "neujaz" },
        "man": { "origin_lang": "Proto-Germanic", "origin_word": "mann-" },
        "woman": { "origin_lang": "Old English", "origin_word": "wīfman" },
        "stone": { "origin_lang": "Proto-Germanic", "origin_word": "stainaz" },
        "earth": { "origin_lang": "Proto-Germanic", "origin_word": "erþō" },
        "wind": { "origin_lang": "Proto-Germanic", "origin_word": "windaz" },
        "leaf": { "origin_lang": "Proto-Germanic", "origin_word": "laubą" },
        "come": { "origin_lang": "Proto-Germanic", "origin_word": "kwimaną" },
        "sit": { "origin_lang": "Proto-Germanic", "origin_word": "sitjaną" },
        "stand": { "origin_lang": "Proto-Germanic", "origin_word": "standaną" },
        "night": { "origin_lang": "Proto-Germanic", "origin_word": "nahts" },
        "day": { "origin_lang": "Proto-Germanic", "origin_word": "dagaz" },
        "star": { "origin_lang": "Proto-Germanic", "origin_word": "sternǭ" },
        "sea": { "origin_lang": "Proto-Germanic", "origin_word": "saiwiz" },
        "milk": { "origin_lang": "Proto-Germanic", "origin_word": "meluks" },
        "meat": { "origin_lang": "Proto-Germanic", "origin_word": "matiz" },
        "tooth": { "origin_lang": "Proto-Germanic", "origin_word": "tanþs" },
        "tongue": { "origin_lang": "Proto-Germanic", "origin_word": "tungǭ" },
        "give": { "origin_lang": "Proto-Germanic", "origin_word": "gebaną" },
        "sleep": { "origin_lang": "Proto-Germanic", "origin_word": "slēpaną" },
        "table": { "origin_lang": "Latin", "origin_word": "tabula" },
        "chair": { "origin_lang": "Latin", "origin_word": "cathedra" },
        "bed": { "origin_lang": "Proto-Germanic", "origin_word": "badją" },
        "shirt": { "origin_lang": "Proto-Germanic", "origin_word": "skurtijǭ" },
        "shoe": { "origin_lang": "Proto-Germanic", "origin_word": "skōhaz" },
        "school": { "origin_lang": "Latin", "origin_word": "schola" },
        "city": { "origin_lang": "Latin", "origin_word": "civitas" },
        "town": { "origin_lang": "Proto-Germanic", "origin_word": "tūnaz" },
        "book": { "origin_lang": "Proto-Germanic", "origin_word": "bōks" },
        "time": { "origin_lang": "Proto-Germanic", "origin_word": "tīmô" }
    },
    "de": {
        "Arm": { "origin_lang": "Proto-Germanic", "origin_word": "armaz" },
        "Wasser": { "origin_lang": "Proto-Germanic", "origin_word": "watōr" },
        "Haus": { "origin_lang": "Proto-Germanic", "origin_word": "hūsą" },
        "Brot": { "origin_lang": "Proto-Germanic", "origin_word": "braudą" },
        "Hand": { "origin_lang": "Proto-Germanic", "origin_word": "handuz" },
        "Sonne": { "origin_lang": "Proto-Germanic", "origin_word": "sunnō" },
        "Mond": { "origin_lang": "Proto-Germanic", "origin_word": "mēnô" },
        "Mutter": { "origin_lang": "Proto-Germanic", "origin_word": "mōdēr" },
        "Vater": { "origin_lang": "Proto-Germanic", "origin_word": "fader" },
        "Bruder": { "origin_lang": "Proto-Germanic", "origin_word": "brōþēr" },
        "Schwester": { "origin_lang": "Proto-Germanic", "origin_word": "swestēr" },
        "Sohn": { "origin_lang": "Proto-Germanic", "origin_word": "sunuz" },
        "Tochter": { "origin_lang": "Proto-Germanic", "origin_word": "duhtēr" },
        "sein": { "origin_lang": "Proto-Germanic", "origin_word": "sijaną" },
        "haben": { "origin_lang": "Proto-Germanic", "origin_word": "habjaną" },
        "gehen": { "origin_lang": "Proto-Germanic", "origin_word": "ganganą" },
        "essen": { "origin_lang": "Proto-Germanic", "origin_word": "etaną" },
        "trinken": { "origin_lang": "Proto-Germanic", "origin_word": "drinkaną" },
        "Fuß": { "origin_lang": "Proto-Germanic", "origin_word": "fōts" },
        "Auge": { "origin_lang": "Proto-Germanic", "origin_word": "augô" },
        "Nase": { "origin_lang": "Proto-Germanic", "origin_word": "nasō" },
        "Mund": { "origin_lang": "Proto-Germanic", "origin_word": "munþaz" },
        "Ohr": { "origin_lang": "Proto-Germanic", "origin_word": "auzon" },
        "Herz": { "origin_lang": "Proto-Germanic", "origin_word": "hertō" },
        "sehen": { "origin_lang": "Proto-Germanic", "origin_word": "sehwan" },
        "hören": { "origin_lang": "Proto-Germanic", "origin_word": "hauzjan" },
        "Kopf": { "origin_lang": "Latin", "origin_word": "cuppa" },
        "eins": { "origin_lang": "Proto-Germanic", "origin_word": "ainaz" },
        "zwei": { "origin_lang": "Proto-Germanic", "origin_word": "twai" },
        "drei": { "origin_lang": "Proto-Germanic", "origin_word": "þrijiz" },
        "vier": { "origin_lang": "Proto-Germanic", "origin_word": "fedwōr" },
        "fünf": { "origin_lang": "Proto-Germanic", "origin_word": "fimf" },
        "sechs": { "origin_lang": "Proto-Germanic", "origin_word": "sehs" },
        "sieben": { "origin_lang": "Proto-Germanic", "origin_word": "sibun" },
        "acht": { "origin_lang": "Proto-Germanic", "origin_word": "ahtōu" },
        "neun": { "origin_lang": "Proto-Germanic", "origin_word": "newun" },
        "zehn": { "origin_lang": "Proto-Germanic", "origin_word": "tehun" },
        "rot": { "origin_lang": "Proto-Germanic", "origin_word": "raudaz" },
        "grün": { "origin_lang": "Proto-Germanic", "origin_word": "grōniz" },
        "weiß": { "origin_lang": "Proto-Germanic", "origin_word": "hwītaz" },
        "schwarz": { "origin_lang": "Proto-Germanic", "origin_word": "swartaz" },
        "blau": { "origin_lang": "Proto-Germanic", "origin_word": "blēwaz" },
        "gelb": { "origin_lang": "Proto-Germanic", "origin_word": "gelwaz" },
        "gut": { "origin_lang": "Proto-Germanic", "origin_word": "gōdaz" },
        "schlecht": { "origin_lang": "Middle High German", "origin_word": "sleht" },
        "groß": { "origin_lang": "Proto-Germanic", "origin_word": "grautaz" },
        "klein": { "origin_lang": "Proto-Germanic", "origin_word": "krainaz" },
        "Hund": { "origin_lang": "Proto-Germanic", "origin_word": "hundaz" },
        "Katze": { "origin_lang": "Latin", "origin_word": "cattus" },
        "Fisch": { "origin_lang": "Proto-Germanic", "origin_word": "fiskaz" },
        "Vogel": { "origin_lang": "Proto-Germanic", "origin_word": "fuglaz" },
        "Baum": { "origin_lang": "Proto-Germanic", "origin_word": "baumaz" },
        "Himmel": { "origin_lang": "Proto-Germanic", "origin_word": "hibina" },
        "Regen": { "origin_lang": "Proto-Germanic", "origin_word": "rigną" },
        "Feuer": { "origin_lang": "Proto-Germanic", "origin_word": "fōr" },
        "lang": { "origin_lang": "Proto-Germanic", "origin_word": "langaz" },
        "kalt": { "origin_lang": "Proto-Germanic", "origin_word": "kaldaz" },
        "neu": { "origin_lang": "Proto-Germanic", "origin_word": "neujaz" },
        "Mann": { "origin_lang": "Proto-Germanic", "origin_word": "mann-" },
        "Frau": { "origin_lang": "Old High German", "origin_word": "frouwa" },
        "Stein": { "origin_lang": "Proto-Germanic", "origin_word": "stainaz" },
        "Erde": { "origin_lang": "Proto-Germanic", "origin_word": "erþō" },
        "Wind": { "origin_lang": "Proto-Germanic", "origin_word": "windaz" },
        "Blatt": { "origin_lang": "Proto-Germanic", "origin_word": "blada-" },
        "kommen": { "origin_lang": "Proto-Germanic", "origin_word": "kwimaną" },
        "sitzen": { "origin_lang": "Proto-Germanic", "origin_word": "sitjaną" },
        "stehen": { "origin_lang": "Proto-Germanic", "origin_word": "standaną" },
        "Nacht": { "origin_lang": "Proto-Germanic", "origin_word": "nahts" },
        "Tag": { "origin_lang": "Proto-Germanic", "origin_word": "dagaz" },
        "Stern": { "origin_lang": "Proto-Germanic", "origin_word": "sternǭ" },
        "See": { "origin_lang": "Proto-Germanic", "origin_word": "saiwiz" },
        "Milch": { "origin_lang": "Proto-Germanic", "origin_word": "meluks" },
        "Fleisch": { "origin_lang": "Proto-Germanic", "origin_word": "flaiskaz" },
        "Zahn": { "origin_lang": "Proto-Germanic", "origin_word": "tanþs" },
        "Zunge": { "origin_lang": "Proto-Germanic", "origin_word": "tungǭ" },
        "geben": { "origin_lang": "Proto-Germanic", "origin_word": "gebaną" },
        "nehmen": { "origin_lang": "Proto-Germanic", "origin_word": "nemaną" },
        "schlafen": { "origin_lang": "Proto-Germanic", "origin_word": "slēpaną" },
        "Tisch": { "origin_lang": "Latin", "origin_word": "tabula" },
        "Stuhl": { "origin_lang": "Proto-Germanic", "origin_word": "stōlaz" },
        "Bett": { "origin_lang": "Proto-Germanic", "origin_word": "badją" },
        "Schuh": { "origin_lang": "Proto-Germanic", "origin_word": "skōhaz" },
        "Schule": { "origin_lang": "Latin", "origin_word": "schola" },
        "Stadt": { "origin_lang": "Proto-Germanic", "origin_word": "stadiz" },
        "Buch": { "origin_lang": "Proto-Germanic", "origin_word": "bōks" },
        "Zeit": { "origin_lang": "Proto-Germanic", "origin_word": "tīdiz" }
    },
    "fr": {
        "bras": { "origin_lang": "Latin", "origin_word": "bracchium" },
        "eau": { "origin_lang": "Latin", "origin_word": "aqua" },
        "maison": { "origin_lang": "Latin", "origin_word": "mansio" },
        "pain": { "origin_lang": "Latin", "origin_word": "panis" },
        "main": { "origin_lang": "Latin", "origin_word": "manus" },
        "soleil": { "origin_lang": "Latin", "origin_word": "soliculus" },
        "lune": { "origin_lang": "Latin", "origin_word": "luna" },
        "mère": { "origin_lang": "Latin", "origin_word": "mater" },
        "père": { "origin_lang": "Latin", "origin_word": "pater" },
        "frère": { "origin_lang": "Latin", "origin_word": "frater" },
        "sœur": { "origin_lang": "Latin", "origin_word": "soror" },
        "fils": { "origin_lang": "Latin", "origin_word": "filius" },
        "fille": { "origin_lang": "Latin", "origin_word": "filia" },
        "être": { "origin_lang": "Latin", "origin_word": "esse" },
        "avoir": { "origin_lang": "Latin", "origin_word": "habere" },
        "faire": { "origin_lang": "Latin", "origin_word": "facere" },
        "dire": { "origin_lang": "Latin", "origin_word": "dicere" },
        "manger": { "origin_lang": "Latin", "origin_word": "manducare" },
        "boire": { "origin_lang": "Latin", "origin_word": "bibere" },
        "parler": { "origin_lang": "Latin", "origin_word": "parabolare" },
        "pied": { "origin_lang": "Latin", "origin_word": "pes" },
        "œil": { "origin_lang": "Latin", "origin_word": "oculus" },
        "nez": { "origin_lang": "Latin", "origin_word": "nasus" },
        "bouche": { "origin_lang": "Latin", "origin_word": "bucca" },
        "oreille": { "origin_lang": "Latin", "origin_word": "auricula" },
        "cœur": { "origin_lang": "Latin", "origin_word": "cor" },
        "voir": { "origin_lang": "Latin", "origin_word": "videre" },
        "entendre": { "origin_lang": "Latin", "origin_word": "intendere" },
        "tête": { "origin_lang": "Latin", "origin_word": "testa" },
        "un": { "origin_lang": "Latin", "origin_word": "unus" },
        "deux": { "origin_lang": "Latin", "origin_word": "duo" },
        "trois": { "origin_lang": "Latin", "origin_word": "tres" },
        "quatre": { "origin_lang": "Latin", "origin_word": "quattuor" },
        "cinq": { "origin_lang": "Latin", "origin_word": "quinque" },
        "six": { "origin_lang": "Latin", "origin_word": "sex" },
        "sept": { "origin_lang": "Latin", "origin_word": "septem" },
        "huit": { "origin_lang": "Latin", "origin_word": "octo" },
        "neuf": { "origin_lang": "Latin", "origin_word": "novem" },
        "dix": { "origin_lang": "Latin", "origin_word": "decem" },
        "rouge": { "origin_lang": "Latin", "origin_word": "rubeus" },
        "bleu": { "origin_lang": "Frankish", "origin_word": "blāu" },
        "vert": { "origin_lang": "Latin", "origin_word": "viridis" },
        "blanc": { "origin_lang": "Frankish", "origin_word": "blank" },
        "noir": { "origin_lang": "Latin", "origin_word": "niger" },
        "jaune": { "origin_lang": "Latin", "origin_word": "galbinus" },
        "chien": { "origin_lang": "Latin", "origin_word": "canis" },
        "chat": { "origin_lang": "Latin", "origin_word": "cattus" },
        "poisson": { "origin_lang": "Latin", "origin_word": "piscis" },
        "oiseau": { "origin_lang": "Latin", "origin_word": "avicellus" },
        "arbre": { "origin_lang": "Latin", "origin_word": "arbor" },
        "ciel": { "origin_lang": "Latin", "origin_word": "caelum" },
        "pluie": { "origin_lang": "Latin", "origin_word": "pluvia" },
        "feu": { "origin_lang": "Latin", "origin_word": "focus" },
        "long": { "origin_lang": "Latin", "origin_word": "longus" },
        "froid": { "origin_lang": "Latin", "origin_word": "frigidus" },
        "nouveau": { "origin_lang": "Latin", "origin_word": "novellus" },
        "homme": { "origin_lang": "Latin", "origin_word": "homo" },
        "femme": { "origin_lang": "Latin", "origin_word": "femina" },
        "pierre": { "origin_lang": "Latin", "origin_word": "petra" },
        "terra": { "origin_lang": "Latin", "origin_word": "terra" },
        "vent": { "origin_lang": "Latin", "origin_word": "ventus" },
        "feuille": { "origin_lang": "Latin", "origin_word": "folia" },
        "venir": { "origin_lang": "Latin", "origin_word": "venire" },
        "dormir": { "origin_lang": "Latin", "origin_word": "dormire" },
        "donner": { "origin_lang": "Latin", "origin_word": "donare" },
        "prendre": { "origin_lang": "Latin", "origin_word": "prehendere" },
        "nuit": { "origin_lang": "Latin", "origin_word": "nox" },
        "jour": { "origin_lang": "Latin", "origin_word": "diurnus" },
        "étoile": { "origin_lang": "Latin", "origin_word": "stella" },
        "mer": { "origin_lang": "Latin", "origin_word": "mare" },
        "lait": { "origin_lang": "Latin", "origin_word": "lac" },
        "viande": { "origin_lang": "Latin", "origin_word": "vivenda" },
        "dent": { "origin_lang": "Latin", "origin_word": "dens" },
        "langue": { "origin_lang": "Latin", "origin_word": "lingua" },
        "table": { "origin_lang": "Latin", "origin_word": "tabula" },
        "chaise": { "origin_lang": "Latin", "origin_word": "cathedra" },
        "lit": { "origin_lang": "Latin", "origin_word": "lectus" },
        "école": { "origin_lang": "Latin", "origin_word": "schola" },
        "ville": { "origin_lang": "Latin", "origin_word": "villa" },
        "livre": { "origin_lang": "Latin", "origin_word": "liber" },
        "argent": { "origin_lang": "Latin", "origin_word": "argentum" },
        "temps": { "origin_lang": "Latin", "origin_word": "tempus" }
    },
    "it": {
        "braccio": { "origin_lang": "Latin", "origin_word": "bracchium" },
        "acqua": { "origin_lang": "Latin", "origin_word": "aqua" },
        "casa": { "origin_lang": "Latin", "origin_word": "casa" },
        "pane": { "origin_lang": "Latin", "origin_word": "panis" },
        "mano": { "origin_lang": "Latin", "origin_word": "manus" },
        "sole": { "origin_lang": "Latin", "origin_word": "sol" },
        "luna": { "origin_lang": "Latin", "origin_word": "luna" },
        "madre": { "origin_lang": "Latin", "origin_word": "mater" },
        "padre": { "origin_lang": "Latin", "origin_word": "pater" },
        "fratello": { "origin_lang": "Latin", "origin_word": "frater" },
        "sorella": { "origin_lang": "Latin", "origin_word": "soror" },
        "figlio": { "origin_lang": "Latin", "origin_word": "filius" },
        "figlia": { "origin_lang": "Latin", "origin_word": "filia" },
        "essere": { "origin_lang": "Latin", "origin_word": "esse" },
        "avere": { "origin_lang": "Latin", "origin_word": "habere" },
        "fare": { "origin_lang": "Latin", "origin_word": "facere" },
        "mangiare": { "origin_lang": "Latin", "origin_word": "manducare" },
        "bere": { "origin_lang": "Latin", "origin_word": "bibere" },
        "parlare": { "origin_lang": "Latin", "origin_word": "parabolare" },
        "piede": { "origin_lang": "Latin", "origin_word": "pes" },
        "occhio": { "origin_lang": "Latin", "origin_word": "oculus" },
        "naso": { "origin_lang": "Latin", "origin_word": "nasus" },
        "bocca": { "origin_lang": "Latin", "origin_word": "bucca" },
        "orecchio": { "origin_lang": "Latin", "origin_word": "auricula" },
        "cuore": { "origin_lang": "Latin", "origin_word": "cor" },
        "vedere": { "origin_lang": "Latin", "origin_word": "videre" },
        "udire": { "origin_lang": "Latin", "origin_word": "audire" },
        "testa": { "origin_lang": "Latin", "origin_word": "testa" },
        "uno": { "origin_lang": "Latin", "origin_word": "unus" },
        "due": { "origin_lang": "Latin", "origin_word": "duo" },
        "tre": { "origin_lang": "Latin", "origin_word": "tres" },
        "quattro": { "origin_lang": "Latin", "origin_word": "quattuor" },
        "cinque": { "origin_lang": "Latin", "origin_word": "quinque" },
        "sei": { "origin_lang": "Latin", "origin_word": "sex" },
        "sette": { "origin_lang": "Latin", "origin_word": "septem" },
        "otto": { "origin_lang": "Latin", "origin_word": "octo" },
        "nove": { "origin_lang": "Latin", "origin_word": "novem" },
        "dieci": { "origin_lang": "Latin", "origin_word": "decem" },
        "rosso": { "origin_lang": "Latin", "origin_word": "russus" },
        "blu": { "origin_lang": "Old French", "origin_word": "bleu" },
        "verde": { "origin_lang": "Latin", "origin_word": "viridis" },
        "bianco": { "origin_lang": "Germanic", "origin_word": "blank" },
        "nero": { "origin_lang": "Latin", "origin_word": "niger" },
        "giallo": { "origin_lang": "French", "origin_word": "jaune" },
        "cane": { "origin_lang": "Latin", "origin_word": "canis" },
        "gatto": { "origin_lang": "Latin", "origin_word": "cattus" },
        "pesce": { "origin_lang": "Latin", "origin_word": "piscis" },
        "uccello": { "origin_lang": "Latin", "origin_word": "avicellus" },
        "albero": { "origin_lang": "Latin", "origin_word": "arbor" },
        "cielo": { "origin_lang": "Latin", "origin_word": "caelum" },
        "pioggia": { "origin_lang": "Latin", "origin_word": "pluvia" },
        "fuoco": { "origin_lang": "Latin", "origin_word": "focus" },
        "lungo": { "origin_lang": "Latin", "origin_word": "longus" },
        "freddo": { "origin_lang": "Latin", "origin_word": "frigidus" },
        "nuovo": { "origin_lang": "Latin", "origin_word": "novus" },
        "uomo": { "origin_lang": "Latin", "origin_word": "homo" },
        "donna": { "origin_lang": "Latin", "origin_word": "domina" },
        "pietra": { "origin_lang": "Latin", "origin_word": "petra" },
        "terra": { "origin_lang": "Latin", "origin_word": "terra" },
        "vento": { "origin_lang": "Latin", "origin_word": "ventus" },
        "foglia": { "origin_lang": "Latin", "origin_word": "folia" },
        "venire": { "origin_lang": "Latin", "origin_word": "venire" },
        "dormir": { "origin_lang": "Latin", "origin_word": "dormire" },
        "dare": { "origin_lang": "Latin", "origin_word": "dare" },
        "prendere": { "origin_lang": "Latin", "origin_word": "prehendere" },
        "notte": { "origin_lang": "Latin", "origin_word": "nox" },
        "giorno": { "origin_lang": "Latin", "origin_word": "diurnus" },
        "stella": { "origin_lang": "Latin", "origin_word": "stella" },
        "mare": { "origin_lang": "Latin", "origin_word": "mare" },
        "latte": { "origin_lang": "Latin", "origin_word": "lac" },
        "carne": { "origin_lang": "Latin", "origin_word": "caro" },
        "dente": { "origin_lang": "Latin", "origin_word": "dens" },
        "lingua": { "origin_lang": "Latin", "origin_word": "lingua" },
        "tavolo": { "origin_lang": "Latin", "origin_word": "tabula" },
        "sedia": { "origin_lang": "Latin", "origin_word": "sedes" },
        "letto": { "origin_lang": "Latin", "origin_word": "lectus" },
        "scuola": { "origin_lang": "Latin", "origin_word": "schola" },
        "città": { "origin_lang": "Latin", "origin_word": "civitas" },
        "libro": { "origin_lang": "Latin", "origin_word": "liber" },
        "denaro": { "origin_lang": "Latin", "origin_word": "denarius" },
        "tempo": { "origin_lang": "Latin", "origin_word": "tempus" }
    },
    "es": {
        "brazo": { "origin_lang": "Latin", "origin_word": "bracchium" },
        "agua": { "origin_lang": "Latin", "origin_word": "aqua" },
        "casa": { "origin_lang": "Latin", "origin_word": "casa" },
        "pan": { "origin_lang": "Latin", "origin_word": "panis" },
        "mano": { "origin_lang": "Latin", "origin_word": "manus" },
        "sol": { "origin_lang": "Latin", "origin_word": "sol" },
        "luna": { "origin_lang": "Latin", "origin_word": "luna" },
        "madre": { "origin_lang": "Latin", "origin_word": "mater" },
        "padre": { "origin_lang": "Latin", "origin_word": "pater" },
        "hermano": { "origin_lang": "Latin", "origin_word": "germanus" },
        "hermana": { "origin_lang": "Latin", "origin_word": "germana" },
        "hijo": { "origin_lang": "Latin", "origin_word": "filius" },
        "hija": { "origin_lang": "Latin", "origin_word": "filia" },
        "ser": { "origin_lang": "Latin", "origin_word": "esse" },
        "estar": { "origin_lang": "Latin", "origin_word": "stare" },
        "tener": { "origin_lang": "Latin", "origin_word": "tenere" },
        "hacer": { "origin_lang": "Latin", "origin_word": "facere" },
        "comer": { "origin_lang": "Latin", "origin_word": "comedere" },
        "beber": { "origin_lang": "Latin", "origin_word": "bibere" },
        "hablar": { "origin_lang": "Latin", "origin_word": "fabulari" },
        "pie": { "origin_lang": "Latin", "origin_word": "pes" },
        "ojo": { "origin_lang": "Latin", "origin_word": "oculus" },
        "nariz": { "origin_lang": "Latin", "origin_word": "nasus" },
        "boca": { "origin_lang": "Latin", "origin_word": "bucca" },
        "oreja": { "origin_lang": "Latin", "origin_word": "auricula" },
        "corazón": { "origin_lang": "Latin", "origin_word": "cor" },
        "ver": { "origin_lang": "Latin", "origin_word": "videre" },
        "oír": { "origin_lang": "Latin", "origin_word": "audire" },
        "cabeza": { "origin_lang": "Latin", "origin_word": "capitia" },
        "uno": { "origin_lang": "Latin", "origin_word": "unus" },
        "dos": { "origin_lang": "Latin", "origin_word": "duos" },
        "tres": { "origin_lang": "Latin", "origin_word": "tres" },
        "cuatro": { "origin_lang": "Latin", "origin_word": "quattuor" },
        "cinco": { "origin_lang": "Latin", "origin_word": "quinque" },
        "seis": { "origin_lang": "Latin", "origin_word": "sex" },
        "siete": { "origin_lang": "Latin", "origin_word": "septem" },
        "ocho": { "origin_lang": "Latin", "origin_word": "octo" },
        "nueve": { "origin_lang": "Latin", "origin_word": "novem" },
        "diez": { "origin_lang": "Latin", "origin_word": "decem" },
        "rojo": { "origin_lang": "Latin", "origin_word": "russus" },
        "azul": { "origin_lang": "Arabic", "origin_word": "lāzaward" },
        "verde": { "origin_lang": "Latin", "origin_word": "viridis" },
        "blanco": { "origin_lang": "Germanic", "origin_word": "blank" },
        "negro": { "origin_lang": "Latin", "origin_word": "niger" },
        "amarillo": { "origin_lang": "Latin", "origin_word": "amarellus" },
        "perro": { "origin_lang": "Onomatopoeic", "origin_word": "perro" },
        "gato": { "origin_lang": "Latin", "origin_word": "cattus" },
        "pez": { "origin_lang": "Latin", "origin_word": "piscis" },
        "pájaro": { "origin_lang": "Latin", "origin_word": "passer" },
        "árbol": { "origin_lang": "Latin", "origin_word": "arbor" },
        "cielo": { "origin_lang": "Latin", "origin_word": "caelum" },
        "lluvia": { "origin_lang": "Latin", "origin_word": "pluvia" },
        "fuego": { "origin_lang": "Latin", "origin_word": "focus" },
        "largo": { "origin_lang": "Latin", "origin_word": "largus" },
        "frío": { "origin_lang": "Latin", "origin_word": "frigidus" },
        "nuevo": { "origin_lang": "Latin", "origin_word": "novus" },
        "homme": { "origin_lang": "Latin", "origin_word": "homo" },
        "mujer": { "origin_lang": "Latin", "origin_word": "mulier" },
        "piedra": { "origin_lang": "Latin", "origin_word": "petra" },
        "tierra": { "origin_lang": "Latin", "origin_word": "terra" },
        "viento": { "origin_lang": "Latin", "origin_word": "ventus" },
        "hoja": { "origin_lang": "Latin", "origin_word": "folia" },
        "venir": { "origin_lang": "Latin", "origin_word": "venire" },
        "sentarse": { "origin_lang": "Latin", "origin_word": "sedere" },
        "tomar": { "origin_lang": "Latin", "origin_word": "tomare" },
        "noche": { "origin_lang": "Latin", "origin_word": "nox" },
        "día": { "origin_lang": "Latin", "origin_word": "dies" },
        "estrella": { "origin_lang": "Latin", "origin_word": "stella" },
        "mar": { "origin_lang": "Latin", "origin_word": "mare" },
        "leche": { "origin_lang": "Latin", "origin_word": "lac" },
        "carne": { "origin_lang": "Latin", "origin_word": "caro" },
        "diente": { "origin_lang": "Latin", "origin_word": "dens" },
        "lengua": { "origin_lang": "Latin", "origin_word": "lingua" },
        "mesa": { "origin_lang": "Latin", "origin_word": "mensa" },
        "silla": { "origin_lang": "Latin", "origin_word": "sella" },
        "cama": { "origin_lang": "Vulgar Latin", "origin_word": "cama" },
        "camisa": { "origin_lang": "Latin", "origin_word": "camisia" },
        "escuela": { "origin_lang": "Latin", "origin_word": "schola" },
        "ciudad": { "origin_lang": "Latin", "origin_word": "civitas" },
        "caballo": { "origin_lang": "Latin", "origin_word": "caballus" },
        "vaca": { "origin_lang": "Latin", "origin_word": "vacca" }
    },
    "pt": {
        "braço": { "origin_lang": "Latin", "origin_word": "bracchium" },
        "água": { "origin_lang": "Latin", "origin_word": "aqua" },
        "casa": { "origin_lang": "Latin", "origin_word": "casa" },
        "pão": { "origin_lang": "Latin", "origin_word": "panis" },
        "mão": { "origin_lang": "Latin", "origin_word": "manus" },
        "sol": { "origin_lang": "Latin", "origin_word": "sol" },
        "lua": { "origin_lang": "Latin", "origin_word": "luna" },
        "mãε": { "origin_lang": "Latin", "origin_word": "mater" },
        "pai": { "origin_lang": "Latin", "origin_word": "pater" },
        "irmão": { "origin_lang": "Latin", "origin_word": "germanus" },
        "irmã": { "origin_lang": "Latin", "origin_word": "germana" },
        "filho": { "origin_lang": "Latin", "origin_word": "filius" },
        "filha": { "origin_lang": "Latin", "origin_word": "filia" },
        "ser": { "origin_lang": "Latin", "origin_word": "esse" },
        "estar": { "origin_lang": "Latin", "origin_word": "stare" },
        "ter": { "origin_lang": "Latin", "origin_word": "tenere" },
        "fazer": { "origin_lang": "Latin", "origin_word": "facere" },
        "comer": { "origin_lang": "Latin", "origin_word": "comedere" },
        "beber": { "origin_lang": "Latin", "origin_word": "bibere" },
        "falar": { "origin_lang": "Latin", "origin_word": "fabulari" },
        "pé": { "origin_lang": "Latin", "origin_word": "pes" },
        "olho": { "origin_lang": "Latin", "origin_word": "oculus" },
        "nariz": { "origin_lang": "Latin", "origin_word": "nasus" },
        "boca": { "origin_lang": "Latin", "origin_word": "bucca" },
        "orelha": { "origin_lang": "Latin", "origin_word": "auricula" },
        "coração": { "origin_lang": "Latin", "origin_word": "cor" },
        "ver": { "origin_lang": "Latin", "origin_word": "videre" },
        "ouvir": { "origin_lang": "Latin", "origin_word": "audire" },
        "cabeça": { "origin_lang": "Latin", "origin_word": "capitia" },
        "um": { "origin_lang": "Latin", "origin_word": "unus" },
        "dois": { "origin_lang": "Latin", "origin_word": "duos" },
        "três": { "origin_lang": "Latin", "origin_word": "tres" },
        "quatro": { "origin_lang": "Latin", "origin_word": "quattuor" },
        "cinco": { "origin_lang": "Latin", "origin_word": "quinque" },
        "seis": { "origin_lang": "Latin", "origin_word": "sex" },
        "sete": { "origin_lang": "Latin", "origin_word": "septem" },
        "oito": { "origin_lang": "Latin", "origin_word": "octo" },
        "nove": { "origin_lang": "Latin", "origin_word": "novem" },
        "dez": { "origin_lang": "Latin", "origin_word": "decem" },
        "vermelho": { "origin_lang": "Latin", "origin_word": "vermiculus" },
        "azul": { "origin_lang": "Arabic", "origin_word": "lāzaward" },
        "verde": { "origin_lang": "Latin", "origin_word": "viridis" },
        "branco": { "origin_lang": "Germanic", "origin_word": "blank" },
        "preto": { "origin_lang": "Latin", "origin_word": "appectoratus" },
        "amarelo": { "origin_lang": "Latin", "origin_word": "amarellus" },
        "cão": { "origin_lang": "Latin", "origin_word": "canis" },
        "gato": { "origin_lang": "Latin", "origin_word": "cattus" },
        "peixe": { "origin_lang": "Latin", "origin_word": "piscis" },
        "pássaro": { "origin_lang": "Latin", "origin_word": "passer" },
        "árvore": { "origin_lang": "Latin", "origin_word": "arbor" },
        "céu": { "origin_lang": "Latin", "origin_word": "caelum" },
        "chuva": { "origin_lang": "Latin", "origin_word": "pluvia" },
        "fogo": { "origin_lang": "Latin", "origin_word": "focus" },
        "longo": { "origin_lang": "Latin", "origin_word": "longus" },
        "frio": { "origin_lang": "Latin", "origin_word": "frigidus" },
        "novo": { "origin_lang": "Latin", "origin_word": "novus" },
        "homem": { "origin_lang": "Latin", "origin_word": "homo" },
        "mulher": { "origin_lang": "Latin", "origin_word": "mulier" },
        "pedra": { "origin_lang": "Latin", "origin_word": "petra" },
        "terra": { "origin_lang": "Latin", "origin_word": "terra" },
        "vento": { "origin_lang": "Latin", "origin_word": "ventus" },
        "folha": { "origin_lang": "Latin", "origin_word": "folia" },
        "vir": { "origin_lang": "Latin", "origin_word": "venire" },
        "sentar": { "origin_lang": "Latin", "origin_word": "sedere" },
        "tomar": { "origin_lang": "Latin", "origin_word": "tomare" },
        "noite": { "origin_lang": "Latin", "origin_word": "nox" },
        "dia": { "origin_lang": "Latin", "origin_word": "dies" },
        "estrella": { "origin_lang": "Latin", "origin_word": "stella" },
        "mar": { "origin_lang": "Latin", "origin_word": "mare" },
        "leite": { "origin_lang": "Latin", "origin_word": "lac" },
        "carne": { "origin_lang": "Latin", "origin_word": "caro" },
        "dente": { "origin_lang": "Latin", "origin_word": "dens" },
        "língua": { "origin_lang": "Latin", "origin_word": "lingua" },
        "mesa": { "origin_lang": "Latin", "origin_word": "mensa" },
        "cadeira": { "origin_lang": "Latin", "origin_word": "cathedra" },
        "cama": { "origin_lang": "Vulgar Latin", "origin_word": "cama" },
        "camisa": { "origin_lang": "Latin", "origin_word": "camisia" },
        "escola": { "origin_lang": "Latin", "origin_word": "schola" },
        "cidade": { "origin_lang": "Latin", "origin_word": "civitas" },
        "cavalo": { "origin_lang": "Latin", "origin_word": "caballus" },
        "vaca": { "origin_lang": "Latin", "origin_word": "vacca" },
        "porco": { "origin_lang": "Latin", "origin_word": "porcus" }
    },
    "ru": {
        "руκα": { "origin_lang": "Proto-Slavic", "origin_word": "rǫka" },
        "вода": { "origin_lang": "Proto-Slavic", "origin_word": "voda" },
        "дом": { "origin_lang": "Proto-Slavic", "origin_word": "domъ" },
        "χлеб": { "origin_lang": "Proto-Slavic", "origin_word": "xlěbъ" },
        "солнце": { "origin_lang": "Proto-Slavic", "origin_word": "sъlnьce" },
        "луνα": { "origin_lang": "Proto-Slavic", "origin_word": "luna" },
        "мать": { "origin_lang": "Proto-Slavic", "origin_word": "mati" },
        "отец": { "origin_lang": "Proto-Slavic", "origin_word": "otьcь" },
        "браτ": { "origin_lang": "Proto-Slavic", "origin_word": "bratrъ" },
        "сестρа": { "origin_lang": "Proto-Slavic", "origin_word": "sestra" },
        "сын": { "origin_lang": "Proto-Slavic", "origin_word": "synъ" },
        "дочь": { "origin_lang": "Proto-Slavic", "origin_word": "dъkti" },
        "быτь": { "origin_lang": "Proto-Slavic", "origin_word": "byti" },
        "делаτь": { "origin_lang": "Proto-Slavic", "origin_word": "dělati" },
        "есτь": { "origin_lang": "Proto-Slavic", "origin_word": "ěsti" },
        "πиτь": { "origin_lang": "Proto-Slavic", "origin_word": "piti" },
        "говоρиτь": { "origin_lang": "Proto-Slavic", "origin_word": "govoriti" },
        "ρабоτаτь": { "origin_lang": "Proto-Slavic", "origin_word": "orbota" },
        "νογα": { "origin_lang": "Proto-Slavic", "origin_word": "noga" },
        "глаз": { "origin_lang": "Proto-Slavic", "origin_word": "glazъ" },
        "νοс": { "origin_lang": "Proto-Slavic", "origin_word": "nosъ" },
        "ροτ": { "origin_lang": "Proto-Slavic", "origin_word": "rъtъ" },
        "уχο": { "origin_lang": "Proto-Slavic", "origin_word": "uxo" },
        "сеρдце": { "origin_lang": "Proto-Slavic", "origin_word": "sьrdьce" },
        "видеτь": { "origin_lang": "Proto-Slavic", "origin_word": "viděti" },
        "слышаτь": { "origin_lang": "Proto-Slavic", "origin_word": "slyšati" },
        "γολοβα": { "origin_lang": "Proto-Slavic", "origin_word": "golva" },
        "οдин": { "origin_lang": "Proto-Slavic", "origin_word": "edinъ" },
        "два": { "origin_lang": "Proto-Slavic", "origin_word": "dъva" },
        "τρи": { "origin_lang": "Proto-Slavic", "origin_word": "tri" },
        "чеτыρε": { "origin_lang": "Proto-Slavic", "origin_word": "četyre" },
        "πяτь": { "origin_lang": "Proto-Slavic", "origin_word": "pętь" },
        "sheсть": { "origin_lang": "Proto-Slavic", "origin_word": "šestь" },
        "семь": { "origin_lang": "Proto-Slavic", "origin_word": "sedmь" },
        "восемь": { "origin_lang": "Proto-Slavic", "origin_word": "ovsьmь" },
        "девяτь": { "origin_lang": "Proto-Slavic", "origin_word": "devętь" },
        "десяτь": { "origin_lang": "Proto-Slavic", "origin_word": "desętь" },
        "κρасный": { "origin_lang": "Proto-Slavic", "origin_word": "krasьnъ" },
        "синий": { "origin_lang": "Proto-Slavic", "origin_word": "sinьjь" },
        "зеленый": { "origin_lang": "Proto-Slavic", "origin_word": "zelenъ" },
        "белый": { "origin_lang": "Proto-Slavic", "origin_word": "bělъ" },
        "чеρный": { "origin_lang": "Proto-Slavic", "origin_word": "čьrnъ" },
        "жеλτый": { "origin_lang": "Proto-Slavic", "origin_word": "žьltъ" },
        "κοшκα": { "origin_lang": "Proto-Slavic", "origin_word": "košьka" },
        "ρыβα": { "origin_lang": "Proto-Slavic", "origin_word": "ryba" },
        "πτιца": { "origin_lang": "Proto-Slavic", "origin_word": "pъtica" },
        "деρεβο": { "origin_lang": "Proto-Slavic", "origin_word": "dervo" },
        "неβο": { "origin_lang": "Proto-Slavic", "origin_word": "nebo" },
        "дождь": { "origin_lang": "Proto-Slavic", "origin_word": "dъždь" },
        "ογοнь": { "origin_lang": "Proto-Slavic", "origin_word": "ognь" },
        "длинный": { "origin_lang": "Proto-Slavic", "origin_word": "dĺ̥gъ" },
        "χολοдный": { "origin_lang": "Proto-Slavic", "origin_word": "xoldьnъ" },
        "новый": { "origin_lang": "Proto-Slavic", "origin_word": "novъ" },
        "чеλοβεκ": { "origin_lang": "Proto-Slavic", "origin_word": "čelověkъ" },
        "женщина": { "origin_lang": "Proto-Slavic", "origin_word": "žena" },
        "κамень": { "origin_lang": "Proto-Slavic", "origin_word": "kamy" },
        "земля": { "origin_lang": "Proto-Slavic", "origin_word": "zemlja" },
        "βετеρ": { "origin_lang": "Proto-Slavic", "origin_word": "větrъ" },
        "лисτ": { "origin_lang": "Proto-Slavic", "origin_word": "listъ" },
        "πρийτи": { "origin_lang": "Proto-Slavic", "origin_word": "prijiti" },
        "сидеτь": { "origin_lang": "Proto-Slavic", "origin_word": "sěděti" },
        "сτοяτь": { "origin_lang": "Proto-Slavic", "origin_word": "stojati" },
        "νοчь": { "origin_lang": "Proto-Slavic", "origin_word": "noťь" },
        "день": { "origin_lang": "Proto-Slavic", "origin_word": "dьnь" },
        "зβεзδα": { "origin_lang": "Proto-Slavic", "origin_word": "zvězda" },
        "μορе": { "origin_lang": "Proto-Slavic", "origin_word": "more" },
        "γορа": { "origin_lang": "Proto-Slavic", "origin_word": "gora" },
        "моλοκο": { "origin_lang": "Proto-Slavic", "origin_word": "mleko" },
        "мяσο": { "origin_lang": "Proto-Slavic", "origin_word": "męso" },
        "зуβ": { "origin_lang": "Proto-Slavic", "origin_word": "zǫbъ" },
        "языκ": { "origin_lang": "Proto-Slavic", "origin_word": "językъ" },
        "δατь": { "origin_lang": "Proto-Slavic", "origin_word": "dati" },
        "βзяτь": { "origin_lang": "Proto-Slavic", "origin_word": "vьzęti" },
        "сπаτь": { "origin_lang": "Proto-Slavic", "origin_word": "sъpati" },
        "сτοл": { "origin_lang": "Proto-Slavic", "origin_word": "stolъ" },
        "сτуλ": { "origin_lang": "German", "origin_word": "Stuhl" },
        "κροβατь": { "origin_lang": "Greek", "origin_word": "krabbatos" },
        "ρуβαшκα": { "origin_lang": "Proto-Slavic", "origin_word": "rubъ" },
        "βαшμακ": { "origin_lang": "Turkic", "origin_word": "başmak" },
        "шκολα": { "origin_lang": "Latin", "origin_word": "schola" },
        "γοροд": { "origin_lang": "Proto-Slavic", "origin_word": "gordъ" },
        "λοшадь": { "origin_lang": "Turkic", "origin_word": "alaša" },
        "κοροβα": { "origin_lang": "Proto-Slavic", "origin_word": "korva" },
        "сβинья": { "origin_lang": "Proto-Slavic", "origin_word": "svinьja" }
    },
    "ba": {
        "һыу": { "origin_lang": "Proto-Turkic", "origin_word": "sub" },
        "баλα": { "origin_lang": "Proto-Turkic", "origin_word": "bala" },
        "ҡул": { "origin_lang": "Proto-Turkic", "origin_word": "kol" },
        "κүҙ": { "origin_lang": "Proto-Turkic", "origin_word": "köŕ" },
        "иκмәκ": { "origin_lang": "Old Turkic", "origin_word": "etmek" },
        "ҡοяш": { "origin_lang": "Proto-Turkic", "origin_word": "kuyāš" }
    },
    "tt": {
        "су": { "origin_lang": "Proto-Turkic", "origin_word": "sub" },
        "баλα": { "origin_lang": "Proto-Turkic", "origin_word": "bala" },
        "κул": { "origin_lang": "Proto-Turkic", "origin_word": "kol" },
        "κүз": { "origin_lang": "Proto-Turkic", "origin_word": "köŕ" },
        "иκмәκ": { "origin_lang": "Old Turkic", "origin_word": "etmek" },
        "κοяш": { "origin_lang": "Proto-Turkic", "origin_word": "kuyāš" }
    }
};

const emojiMap = {
    "cat": "🐈", "dog": "🐕", "bird": "🐦", "fish": "🐟", "lion": "🦁", "elephant": "🐘", "rabbit": "🐰",
    "horse": "🐴", "cow": "🐮", "pig": "🐷", "sheep": "🐑", "mouse": "🐭", "snake": "🐍", "monkey": "🐒",
    "spider": "🕷️", "bee": "🐝", "duck": "🦆", "bear": "🐻", "apple": "🍎", "banana": "🍌", "bread": "🍞",
    "milk": "🥛", "water": "🚰", "coffee": "☕", "tea": "🍵", "pizza": "🍕", "rice": "🍚", "meat": "🥩",
    "egg": "🥚", "cheese": "🧀", "potato": "🥔", "tomato": "🍅", "onion": "🧅", "carrot": "🥕", "cake": "🍰",
    "house": "🏠", "car": "🚗", "book": "📖", "sun": "☀️", "moon": "🌙", "star": "⭐", "tree": "🌳",
    "school": "🏫", "hospital": "🏥", "bank": "🏦", "restaurant": "🍴", "airport": "✈️", "city": "🏙️"
};

function findClosingBracket(str, startIdx) {
    let depth = 0;
    for (let i = startIdx; i < str.length; i++) {
        if (str[i] === '[') depth++;
        else if (str[i] === ']') {
            depth--;
            if (depth === 0) return i;
        }
    }
    return -1;
}

function standardizeEntry(entry, lang, theme, seq) {
    if (!entry.id) {
        entry.id = `${lang}_starter_${theme}_${String(seq).padStart(3, '0')}`;
    }
    if (!entry.lang) entry.lang = lang;
    if (!entry.level) entry.level = 'starter';
    if (!entry.theme) entry.theme = theme;
    if (!entry.form) entry.form = 'noun';

    if (!entry.emoji || entry.emoji === '✨') {
        const wordLower = (entry.translation || entry.word || "").toLowerCase();
        entry.emoji = emojiMap[wordLower] || '✨';
    }

    if (!entry.transcription) entry.transcription = '';
    entry.transcription = entry.transcription.replace(/[\/\[\]]/g, '').trim();

    if (!entry.definitions || !Array.isArray(entry.definitions) || entry.definitions.length === 0) {
        entry.definitions = [{ text: `The word for '${entry.word}' in ${lang}.`, examples: [] }];
    } else {
        entry.definitions.forEach(def => {
            if (def.text === "Definition required.") {
                 def.text = `The word for '${entry.word}'.`;
            }
            delete def.word;
            delete def.image;
        });
    }

    if (typeof entry.etymology === 'string') {
        const etymString = entry.etymology;
        entry.etymology = { origin_lang: 'Unknown', notes: etymString };
    }
    if (!entry.etymology || typeof entry.etymology !== 'object' || Object.keys(entry.etymology).length === 0) {
        if (etymDict[lang] && etymDict[lang][entry.word]) {
            entry.etymology = etymDict[lang][entry.word];
        }
    }
    if (entry.opposite !== undefined) {
        if (typeof entry.opposite === 'string' && entry.opposite !== "") {
            entry.antonyms = [entry.opposite];
        }
        delete entry.opposite;
    }
    delete entry.oppositeEmoji;
    delete entry.image;
    delete entry.imageUrl;
    if (entry.language) {
        if (!entry.lang) entry.lang = entry.language;
        delete entry.language;
    }
    return entry;
}

function processFile(filePath) {
    let content = fs.readFileSync(filePath, 'utf8');
    const langMatch = filePath.match(/vocabulary\/([a-z]{2,3})\/A1/);
    if (!langMatch) return;
    const lang = langMatch[1];
    const theme = path.basename(filePath, '.js');

    try {
        const dataStartMatch = content.match(/(const|let|var) data = \[/);
        if (!dataStartMatch) return;

        const arrayStartIdx = dataStartMatch.index + dataStartMatch[0].length - 1;
        const arrayEndIdx = findClosingBracket(content, arrayStartIdx);
        if (arrayEndIdx === -1) return;

        const dataStr = content.slice(arrayStartIdx, arrayEndIdx + 1);
        let data = new Function(`return ${dataStr}`)();

        data = data.map((entry, index) => standardizeEntry(entry, lang, theme, index + 1));

        const newDataStr = JSON.stringify(data, null, 4);
        const before = content.slice(0, arrayStartIdx);
        const after = content.slice(arrayEndIdx + 1);

        const newContent = before + newDataStr + after;

        fs.writeFileSync(filePath, newContent);
        console.log(`Standardized ${filePath}`);
    } catch (e) {
        console.error(`Error in ${filePath}: ${e.message}`);
    }
}

const languages = ['en', 'fr', 'it', 'es', 'ru', 'de', 'pt', 'el', 'hy', 'ka', 'tt', 'ba', 'br'];
languages.forEach(lang => {
    const a1Dir = path.join('vocabulary', lang, 'A1');
    if (fs.existsSync(a1Dir)) {
        fs.readdirSync(a1Dir).filter(f => f.endsWith('.js')).forEach(file => {
            processFile(path.join(a1Dir, file));
        });
    }
});
