(function() {
    const data = [
      { t:"Re verr eo an dibenn-sizhun.", tag:"Daily life", h:["Petra a rit d'an dibenn-sizhun?","Penaos e santit d'ar sul noz?","Petra a rafec'h gant un dibenn-sizhun tri devezh?","Hag-eñ e labourit pe e studit d'an dibenn-sizhun?","Petra eo an dibenn-sizhun peurvat evidoc'h?"] },
      { t:"Displed eo bezañ war-lerc'h.", tag:"Social life", h:["Hag-eñ e vezit d'ar mare reizh peurvuiañ?","Keit ha ma gortozit ur mignon?","Hag-eñ eo mat bezañ 10 munut war-lerc'h?","Hag-eñ eo pouezus bezañ d'ar mare reizh en ho sevenadur?","Petra a rit pa vez unan bennak kalz war-lerc'h?"] },
      { t:"Gwelloc'h eo an dud er c'hêrioù bihan.", tag:"Society", h:["Pelec'h e chomit — kêriadenn pe gêr?","Hag-eñ eo mignonel ho amezeien?","Hag-eñ e komz an dud gant an estrenien pelec'h e chomit?","Hag-eñ az peus bevet en ul lec'h disheñvel gwechall?","Petra a laka ul lec'h da vezañ mignonel?"] },
      { t:"Laouenoc'h e vezit pa az peus ul loen-ti.", tag:"Lifestyle", h:["Hag-eñ az peus ul loen-ti?","Petra eo al loen-ti gwellañ evit un den micherel?","Hag-eñ e koust ker al loened-ti?","Hag-eñ e c'hall ul loen-ti bezañ ur mignon?","Petra a rankit ober evit soursial ouzh ul loen-ti mat?"] },
      { t:"Gallout a rit lavaret kalz traoù diwar-benn unan bennak dre o botoù.", tag:"People", h:["Hag-eñ e sellit ouzh botoù an dud?","Petra a lavar ho potoù diwar-benn ac'hanoc'h?","Hag-eñ eo pouezus ar c'hiz evidoc'h?","Hag-eñ e c'hallit barn un den diwar o neuz?","Petra a lavar deoc'h traoù all diwar-benn doare un den?"] },
      { t:"Mat eo debriñ e-unan en un ti-debriñ.", tag:"Social life", h:["Hag-eñ az peus debret e-unan en un ti-debriñ c'hoazh?","Hag-eñ e kav deoc'h eo aes?","Hag-eñ eo gwelloc'h ar boued gant tud all?","Hag-eñ e welit kalz tud o debriñ o-unan?","Petra a rit pa zebrit ho-unan?"] },
      { t:"Aesoc'h eo deskiñ ur yezh pa vezit yaouank.", tag:"Language", h:["Pet bloaz e oach pa az peus kroget da zeskiñ ar yezh-mañ?","Hag-eñ e soñjit eo pouezus an oad evit deskiñ yezhoù?","Petra eo an dra diaesañ pa zesker ur yezh?","Hag-eñ ec'h anavezit unan bennak en deus desket ur yezh pa oa den deuet?","Petra a sikour ac'hanoc'h ar muiañ pa studier?"] },
      { t:"Gwelloc'h eo an dezougen boutin eget kaout ur c'harr-tan.", tag:"Lifestyle", h:["Penaos e veajit en ho kêr?","Hag-eñ eo mat an dezougen boutin pelec'h e chomit?","Petra eo ar c'hudennoù pa az peus ur c'harr-tan?","Hag-eñ eo ker veajiñ gant an dezougen boutin?","Petra a cheñchfec'h diwar-benn an dezougen en ho kêr?"] },
      { t:"Diaes eo bezañ en deus dregantiñ pa az peus ur pellgomz.", tag:"Technology", h:["Pet eurvezh bemdez e implijit ho pellgomz?","Petra a rit gantañ ar muiañ?","Hag-eñ e oach dregantet a-raok ar pellgomzoù hezoug?","Hag-eñ eo mat an dregantiñ a-wechoù?","Hag-eñ e c'hallfec'h lezel ho pellgomz er gêr e-pad un devezh?"] },
      { t:"Gwelloc'h eo poazhañ er gêr eget debriñ en un ti-debriñ.", tag:"Food", h:["Pegement e poazhit er gêr?","Petra eo an aesañ — poazhañ pe mont d'un ti-debriñ?","Hag-eñ eo ker debriñ en un ti-debriñ pelec'h e chomit?","Petra eo ho ti-debriñ karetañ?","Petra eo ho pred gwellañ poazhet er gêr?"] },
      { t:"An holl a rankfe klask bevañ en estrenvro e-pad ur bloaz.", tag:"Travel", h:["Hag-eñ az peus bevet en ur vro all?","Petra a vije diaes diwar-benn bevañ en estrenvro?","Petra a vije plijus?","Peseurt bro a zibabfec'h?","Hag-eñ e cheñch un den pa vev en estrenvro?"] },
      { t:"Dedennotoc'h eo ar gourharozed eget ar harozed wirion.", tag:"Entertainment", h:["Piv eo ho kourharoz karetañ?","Hag-eñ e c'hallit soñjal en ur haroz en deiz a hiziv?","Petra a laka un den da vezañ ur haroz?","Perak e plij ar gourharozed d'an dud?","Hag-eñ eo pouezusoc'h ar harozed wirion?"] },
      { t:"Pouezus eo ober ho kwele bemdez d'ar mintin.", tag:"Daily life", h:["Hag-eñ e rit ho kwele bemdez?","Hag-eñ e santit gwelloc'h en ur gambr kempenn?","Hag-eñ eo pouezus pe get?","Petra eo ho reolenn-vintin?","Peseurt boazioù bihan az peus?"] },
      { t:"Un dudi eo ar prenañ traoù.", tag:"Free time", h:["Hag-eñ e plij deoc'h prenañ traoù?","Hag-eñ e prenit traoù enlinenn pe er stalioù?","Pegement a amzer e tremenit o prenañ traoù?","Hag-eñ eo un dra dudi prenañ traoù?","Petra a brenit ar muiañ?"] },
      { t:"Gwelloc'h eo veajiñ ho-unan eget veajiñ gant mignoned.", tag:"Travel", h:["Hag-eñ az peus veajet ho-unan c'hoazh?","Petra a zo mat pa veajier ho-unan?","Petra a zo mat pa veajier gant tud all?","Hag-eñ e santit an digenvez pa veajiot ho-unan?","Petra eo ar veaj wellañ az peus graet?"] }
    ];
    const lang = "br";
    if (!window.speakingData) window.speakingData = {};
    if (!window.speakingData[lang]) window.speakingData[lang] = {};
    if (!window.speakingData[lang]["opinions"]) window.speakingData[lang]["opinions"] = [];
    window.speakingData[lang]["opinions"].push(...data);
})();